---
title: "Neurons in ROI/Romain trials"
output: html_notebook
---


```{r}
library(neuprintr)
library(tidyverse)
library(ggiraph)
library(neuprintrExtra)
library(cowplot)
library(patchwork)
```
```{r}
source("R/paperTheme.R")
```

  
Picking the lowest level ROIs
```{r}
roiH <- getRoiTree()
```

```{r}
haneschSaveFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/FirstDraftFigs/HaneschPlots/"
CXTypes <- supertype(read_csv("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/CX-cell-types060920") %>% rename(databaseType=n.type))
```

```{r}
## A function to filter summaries to only neuropiles where neurons make significant connections
filterROISummary <- function(ROIsummary,nBagROI,roiTypes,rois,renaming=cxRetyping){
  roiConnections <- neuronBag(filter(nBagROI$names, type %in% roiTypes$type),slctROI = unique(filter(ROIsummary,roi %in% rois$roi)$roi),verbose=TRUE,selfRef=TRUE)
  roiConnections <- renaming(roiConnections)
  goodTypes <- distinct(do.call(rbind,lapply(unique(ROIsummary$roi),function(r){
    typesUnfiltered <- roiConnections$names$type
    inputs <- roiConnections$inputs %>% filter((roi == r) & 
        (type.to %in% typesUnfiltered))
    outputs <- roiConnections$outputs %>% filter((roi ==r) & 
        (type.from %in% typesUnfiltered))
    roiTypes <- data.frame(type = unique(c(inputs$type.to, outputs$type.from))) %>% 
        mutate(databaseType = roiConnections$names$databaseType[match(type, 
            roiConnections$names$type)])
    return(roiTypes %>% mutate(roi=r))})))
  ROISummary <- inner_join(goodTypes,ROIsummary)
  ROISummary
}
```

# EB
This might take a while
```{r}
EBTypesTable <- getTypesInRoiTable("EB")
```

```{r}
EBRois <- selectRoiSet(roiH,default_level = 2,exceptions = list("EB"=2,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))
labelRoisEB <- selectRoiSet(roiH,default_level = 0,exceptions = list("EB"=2),exceptionLevelMatch = 2)
```

```{r}
EBTypes <- typesInROI(EBTypesTable,ROI = "EB") 
```

```{r}
EBSummary <- getROISummary(EBTypesTable,threshold=20) 
EBSummary_ttFiltered <- filterROISummary(EBSummary,EBTypesTable,EBTypes,EBRois)

EBTypes <- EBTypes %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
EBSummary <- EBSummary %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
EBSummary_ttFiltered  <- EBSummary_ttFiltered %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```
```{r}
haneschEB_R <- haneschPlot(EBSummary %>% filter(type %in% EBTypes$type & ((!grepl("_L.*",type) & supertype3 != "EB Columnar")| grepl("_L",type) & supertype3 == "EB Columnar")),grouping="supertype2",flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE,showCount = TRUE,theme = theme_paper_grid())
haneschEB_R
```

```{r}
haneschEB_R_ttF <- haneschPlot(EBSummary_ttFiltered %>% filter(type %in% EBTypes$type & ((!grepl("_L.*",type) & supertype3 != "EB Columnar")| grepl("_L",type) & supertype3 == "EB Columnar")),grouping="supertype2",flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE,showCount = TRUE,theme = theme_paper_grid())
haneschEB_R_ttF
```


```{r}
save_plot(paste0(haneschSaveFolder,"EB/EBTypesRightWidth2.svg"),haneschEB_R,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"EB/EBTypesRightWidth25.svg"),haneschEB_R,nrow=2,ncol=2.5,base_width = 8.5/2.5)
save_plot(paste0(haneschSaveFolder,"EB/EBTypesRightWidth2_filtered.svg"),haneschEB_R_ttF,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"EB/EBTypesRightWidth25_filtered.svg"),haneschEB_R_ttF,nrow=2,ncol=2.5,base_width = 8.5/2.5)
```

```{r}
interHaneschEB_R <- girafe(ggobj = haneschEB_R, width_svg=20,height_svg=10,
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschEB_R,paste0(haneschSaveFolder,"EB/EBTypesRight.html"))
```

```{r}
haneschExR <- haneschPlot(EBSummary %>% filter(startsWith(type,"ExR") & grepl("_R.*",type)),flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschExR_ttF <- haneschPlot(EBSummary_ttFiltered %>% filter(startsWith(type,"ExR") & grepl("_R.*",type)),flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschExR
haneschExR_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"EB/ExRs.svg"),haneschExR,nrow=1,base_width=8.5/2)
save_plot(paste0(haneschSaveFolder,"EB/ExRs_filtered.svg"),haneschExR_ttF,nrow=1,base_width=8.5/2)
```

```{r}
interHaneschExR <- girafe(ggobj = haneschExR, width_svg=6,height_svg=6)
htmlwidgets::saveWidget(interHaneschExR,paste0(haneschSaveFolder,"EB/ExRs.html"))
```

```{r}
ExRTable <- neuprint_search("ExR.*",field="type") %>% mutate(databaseType = type) %>% lateralize_types(postfix = "raw") %>% filter(grepl("_R.*",type))
```

```{r}
ExRNeurons <- neuprint_read_neurons(ExRTable$bodyid,meta = FALSE,connectors = FALSE)
```
```{r}
ExRNeuronsXY <- neuron2polygon(ExRNeurons)
ExRNeuronsXZ <- neuron2polygon(ExRNeurons,axis=c("x","z"))
ExRNeurons <- bind_rows(ExRNeuronsXY[seq(1,by=2,to=nrow(ExRNeuronsXY)),],ExRNeuronsXZ[seq(1,by=2,to=nrow(ExRNeuronsXZ)),]) %>% mutate(type = ExRTable$type[match(bodyid,ExRTable$bodyid)])
```

```{r}
EBShape <- roiOutline("EB",alpha=200)
LALRShape <- roiOutline("LAL(-GA)(R)",alpha=200)
GAShape <- roiOutline("GA(R)")
BUShape <- roiOutline("BU(R)")
outlineRois <- selectRoiSet(roiH,exceptions=list("LAL(R)"=3))
roiShapes <- bind_rows(EBShape,LALRShape,GAShape,BUShape) %>% mutate(l4 = outlineRois$level4[match(roi,outlineRois$roi)],superroi = labelRoisEB$roi[match(l4,labelRoisEB$level4)])
```


```{r}
ExRAnatPlot <- ggplot() + geom_path(data=roiShapes,aes(x=x,y=y,group=roi),color="grey50") + geom_polygon(data=roiShapes,aes(x=x,y=y,group=roi,fill=superroi),alpha=0.3) + scale_fill_manual(values=roiPal) + geom_polygon_interactive(data=ExRNeurons,aes(x=x,y=y,group=bodyid,data_id=type),fill="grey80",alpha=0.2) + facet_grid(proj~.) + theme_void() + coord_fixed()  + scale_y_reverse()
```

```{r}
ExRSummaryPlot <- plot_grid(ExRAnatPlot + theme(legend.position = "none"),haneschExR)
```

```{r}
interExRSummary <- girafe(ggobj = ExRSummaryPlot, width_svg=14,height_svg=7,options = list(
    opts_hover(css= girafe_css(css = "stroke:red;",
                               area = "fill:black;stroke:none;fill-opacity:1;"
                               ))
  ))
```

```{r}
htmlwidgets::saveWidget(interExRSummary,paste0(haneschSaveFolder,"EB/ExRSummary.html"))
```


```{r}
haneschExRFull <- haneschPlot(EBSummary %>% filter(startsWith(type,"ExR")),flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE)
```

```{r}
ggsave(paste0(haneschSaveFolder,"EB/ExRRight.svg"),haneschExR,width = 8,height=6)
ggsave(paste0(haneschSaveFolder,"EB/ExRFull.svg"),haneschExRFull,width = 10,height=6)
```

```{r}
interHaneschExR <- girafe(ggobj = haneschExR, width_svg=8,height_svg=6,
  options = list(
    opts_sizing(width=0.7)
  ))
interHaneschExRFull <- girafe(ggobj = haneschExRFull, width_svg=8,height_svg=6,
  options = list(
    opts_sizing(width=0.7)
  ))
```

```{r}
htmlwidgets::saveWidget(interHaneschExR,paste0(haneschSaveFolder,"EB/ExRRight.html"))
htmlwidgets::saveWidget(interHaneschExRFull,paste0(haneschSaveFolder,"EB/ExRFull.html"))
```

How do those compare to the Brad Types
```{r}
load("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/EB/EB_Types.RData")
```

```{r}
EB_Type[!(EB_Type %in% EBTypes$databaseType)]
```
That's fine, EQ5 is not a type anymore (it's called EL now)
```{r}
EBTypes$databaseType[!(EBTypes$databaseType %in% EB_Type)]
```

# NO

```{r}
NOTypesTable <- getTypesInRoiTable("NO(R)",lateralize=TRUE)
```

```{r}
NORTypes <- typesInROI(NOTypesTable,ROI = "NO(R)")
```

```{r}
NORois <- selectRoiSet(roiH,default_level = 2,exceptions = list("NO"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))

labelRoisNO <- selectRoiSet(roiH,default_level = 0,exceptions = list("NO"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))
```

```{r}
NOSummary <- getROISummary(NOTypesTable,threshold=20)
NOSummary_ttFiltered <- filterROISummary(NOSummary,NOTypesTable,NORTypes,NORois)
```

```{r}
haneschNOR <- haneschPlot(NOSummary %>% filter(type %in% NORTypes$type),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNOR_ttF <- haneschPlot(NOSummary_ttFiltered %>% filter(type %in% NORTypes$type),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNOR
haneschNOR_ttF
```
```{r}
haneschNORF <- haneschPlot(NOSummary %>% filter((type %in% NORTypes$type) & (databaseType %in% CXTypes$databaseType)),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNORF_ttF <- haneschPlot(NOSummary_ttFiltered %>% filter((type %in% NORTypes$type) & (databaseType %in% CXTypes$databaseType)),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNORF
haneschNORF_ttF
```


```{r}
interHaneschNOR <- girafe(ggobj = haneschNOR, width_svg=15,height_svg=8,
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschNOR,paste0(haneschSaveFolder,"NO/NO_RTypes.html"))
```


```{r}
save_plot(paste0(haneschSaveFolder,"NO/NO_RTypes.svg"),haneschNOR,ncol=2,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"NO/NO_RTypes_t2tFiltered.svg"),haneschNOR_ttF,ncol=2,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"NO/NO_RTypes_filtered.svg"),haneschNORF,ncol=1,nrow=1,base_width = 8.5)
save_plot(paste0(haneschSaveFolder,"NO/NO_RTypes_filtered_t2tFiltered.svg"),haneschNORF_ttF,ncol=1,nrow=1,base_width = 8.5)
```


How do those compare to the Brad Types

```{r}
load("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NO/NO_Types.RData")
```

```{r}
NO_Type[!(NO_Type %in% NORTypes$databaseType)]
```
```{r}
NORTypes$databaseType[!(NORTypes$databaseType %in% NO_Type)]
```

# BU

```{r}
BUTypesTable <- getTypesInRoiTable("BU(R)",verbose=TRUE)

BURTypes <- typesInROI(BUTypesTable,ROI = "BU(R)")

BURois <- selectRoiSet(roiH,default_level = 2,exceptions = list("NO"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))

labelRoisBU <- selectRoiSet(roiH,default_level = 0,exceptions = list("NO"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))

BUSummary <- getROISummary(BUTypesTable,threshold=3)
BUSummary_ttFiltered <- filterROISummary(BUSummary,BUTypesTable,BURTypes,BURois)
```

```{r}
haneschBUR <- haneschPlot(BUSummary %>% filter(type %in% BURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisBU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschBUR_ttF <- haneschPlot(BUSummary_ttFiltered %>% filter(type %in% BURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisBU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschBUR
haneschBUR_ttF
```
```{r}
save_plot(paste0(haneschSaveFolder,"BU/BU_RTypes.svg"),haneschBUR,ncol=2,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"BU/BU_RTypes_filtered.svg"),haneschBUR_ttF,ncol=2,nrow=1.5,base_width = 8.5/2)
```

# AOTU

```{r}
AOTUTypesTable <- getTypesInRoiTable("AOTU(R)",verbose=TRUE)

AOTURTypes <- typesInROI(AOTUTypesTable,ROI = "AOTU(R)")

AOTURois <- selectRoiSet(roiH,default_level = 2,exceptions = list("NO"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))

labelRoisAOTU <- selectRoiSet(roiH,default_level = 0,exceptions = list("NO"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))

AOTUSummary <- getROISummary(AOTUTypesTable,threshold=3)
AOTUSummary_ttFiltered <- filterROISummary(AOTUSummary,AOTUTypesTable,AOTURTypes,AOTURois)
```

```{r}
haneschAOTUR <- haneschPlot(AOTUSummary %>% filter(type %in% AOTURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisAOTU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschAOTUR_ttF <- haneschPlot(AOTUSummary_ttFiltered %>% filter(type %in% AOTURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisAOTU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschAOTUR
haneschAOTUR_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"AOTU/AOTU_RTypes.svg"),haneschAOTUR,ncol=8,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"AOTU/AOTU_RTypes_filtered.svg"),haneschAOTUR_ttF,ncol=8,nrow=1.5,base_width = 8.5/2)
```

# AB

```{r}
ABTypesTable <- getTypesInRoiTable("AB(R)",minTypePercentage = 0.2)

ABTypes <- typesInROI(ABTypesTable,ROI = "AB(R)")%>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))

ABRois <- selectRoiSet(roiH,default_level = 2,exceptions = list("LAL(R)"=4,"AL(R)"=1,"AL(L)"=1,"FB"=4),exceptionLevelMatch = c(2,1,1,2))

labelRoisAB <- selectRoiSet(roiH,default_level = 0,exceptions = list("FB"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))

ABSummary <- getROISummary(ABTypesTable,threshold=0) %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
ABSummary_ttFiltered <- filterROISummary(ABSummary,ABTypesTable,ABTypes,ABRois) %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```

```{r}
haneschABR <- haneschPlot(ABSummary %>% filter(type %in% ABTypes$type),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABR_ttF <- haneschPlot(ABSummary_ttFiltered %>% filter(type %in% ABTypes$type),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABR
haneschABR_ttF
```
```{r}
haneschABRF <- haneschPlot(ABSummary %>% filter((type %in% ABTypes$type) & (databaseType %in% c("SA1_a", "SA1_b", "SA1_c", "SA2_a", "SA2_b", "SA3", "SAF"))),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABRF_ttF <- haneschPlot(ABSummary_ttFiltered %>% filter((type %in% ABTypes$type) & (databaseType %in% c("SA1_a", "SA1_b", "SA1_c", "SA2_a", "SA2_b", "SA3", "SAF"))),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABRF
haneschABRF_ttF
```
```{r}
save_plot(paste0(haneschSaveFolder,"AB/AB_RTypes.svg"),haneschABR,ncol=1,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"AB/AB_RTypes_t2tFiltered.svg"),haneschABR_ttF,ncol=1,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"AB/AB_RTypes_filtered.svg"),haneschABRF,ncol=1,nrow=1,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"AB/AB_RTypes_filtered_t2tFiltered.svg"),haneschABRF_ttF,ncol=1,nrow=1,base_width = 8.5/2)
```

# PB
```{r}
PBTypesTable <- getTypesInRoiTable("PB",retyping = identity)

PBTypesTableNonLat <- PBTypesTable

PBTypesTable <- cxRetyping(PBTypesTable)

PBTypes <- typesInROI(PBTypesTable,ROI = "PB")

PBRois <- selectRoiSet(roiH,default_level = 2,exceptions = list("PB"=2,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))

labelRoisPB <- selectRoiSet(roiH,default_level = 0,exceptions = list("PB"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))

PBTypes <- mutate(PBTypes,type=stringr::str_replace(type,"Delta","\u0394"))
PBSummary <- getROISummary(PBTypesTable,threshold=0)  %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
PBSummary_ttFiltered <- filterROISummary(PBSummary,PBTypesTable,PBTypes,PBRois) %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```

```{r}
haneschPB <- haneschPlot(PBSummary %>% filter(type %in% PBTypes$type & !(databaseType %in% "SIFa")),roiSelect = PBRois,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPB_ttF <- haneschPlot(PBSummary_ttFiltered %>% filter(type %in% PBTypes$type & !(databaseType %in% "SIFa")),roiSelect = PBRois,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPB
haneschPB_ttF
```

```{r}
interHaneschPB <- girafe(ggobj = haneschPB, width_svg=19,height_svg=8
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschPB,paste0(haneschSaveFolder,"PB/PBTypes.html"))
```

```{r}
save_plot(paste0(haneschSaveFolder,"PB/PBTypes.svg"),haneschPB,nrow=1,ncol=2.5,base_width = 8.5/2.5)
save_plot(paste0(haneschSaveFolder,"PB/PBTypes_filtered.svg"),haneschPB_ttF,nrow=1,ncol=2.5,base_width = 8.5/2.5)
```

#### PB glomeruli innervation

```{r}
PBTypesNonLat <- typesInROI(PBTypesTableNonLat,ROI = "PB")
PBRoisDetailed <- selectRoiSet(roiH,default_level = 2,exceptions = list("PB"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))
PBRoisDetailedOnly <- filter(PBRoisDetailed,startsWith(as.character(roi),"PB(")) %>% mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),paste0("PB(L",1:9,")")))) 

PBSummaryNonLat <- getROISummary(PBTypesTableNonLat,threshold=0) %>% filter(startsWith(roi,"PB(")) %>% mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),paste0("PB(L",1:9,")"))))
PBSummaryNonLat_ttFiltered <- filterROISummary(PBSummaryNonLat,PBTypesTableNonLat,PBTypesNonLat,filter(PBRoisDetailed,startsWith(as.character(roi),"PB(")),renaming=identity) %>% mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),paste0("PB(L",1:9,")")))) %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```

```{r}
haneschPBLoc <- haneschPlot(PBSummary %>% filter(databaseType %in% c("Δ7","P1-9","LPsP","P6-8P9","SpsP")),roiSelect = PBRoisDetailed,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPBLoc_ttF <- haneschPlot(PBSummary_ttFiltered %>% filter(databaseType %in% c("Δ7","P1-9","LPsP","P6-8P9","SpsP")),roiSelect = PBRoisDetailed,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPBLoc
haneschPBLoc_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"PB/PBTypesLocal.svg"),haneschPBLoc,nrow=1,ncol=1,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"PB/PBTypesLocal_filtered.svg"),haneschPBLoc_ttF,nrow=1,ncol=1,base_width = 8.5/2)
```


```{r}
haneschPBLoc2 <- haneschPlot(PBSummaryNonLat %>% filter(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","EPGt")),roiSelect = PBRoisDetailedOnly,flip = F,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid(),regionOutlines = F)
haneschPBLoc2_ttF <- haneschPlot(PBSummaryNonLat_ttFiltered %>% filter(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","EPGt")),roiSelect = PBRoisDetailedOnly,flip = F,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid(),regionOutlines = F)
haneschPBLoc2
haneschPBLoc2_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"PB/PBTypesLocal2.svg"),haneschPBLoc2,nrow=1,ncol=1,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"PB/PBTypesLocal2_filtered.svg"),haneschPBLoc2_ttF,nrow=1,ncol=1,base_width = 8.5/2)
```

```{r}
haneschPBColumn <- haneschPlot(PBSummaryNonLat %>% filter(type %in% PBTypesNonLat$type & !(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","SIFamide","EPGt"))),roiSelect = PBRoisDetailedOnly,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid(),regionOutlines = F)
haneschPBColumn_ttF <- haneschPlot(PBSummaryNonLat_ttFiltered %>% filter(type %in% PBTypesNonLat$type & !(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","SIFamide","EPGt"))),roiSelect = PBRoisDetailedOnly,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid(),regionOutlines = F)
haneschPBColumn
```

```{r}
haneschPBDetails <- haneschPBLoc2 / haneschPBColumn + plot_layout(guides="collect",heights=c(1,4))
haneschPBDetails_ttF <- haneschPBLoc2_ttF / haneschPBColumn_ttF + plot_layout(guides="collect",heights=c(1,4))
haneschPBDetails
haneschPBDetails_ttF
```
```{r}
save_plot(paste0(haneschSaveFolder,"PB/PBDetails.svg"),haneschPBDetails,nrow=2,ncol=1,base_width=8.5/2)
save_plot(paste0(haneschSaveFolder,"PB/PBDetails_filtered.svg"),haneschPBDetails_ttF,nrow=2,ncol=1,base_width=8.5/2)
```

# FB
Tighten your seat belts, there are many neurons here.
```{r}
FBTypesTable <- getTypesInRoiTable("FB",verbose=T)


FBTypes <- typesInROI(FBTypesTable,ROI = "FB")#%>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))

FBRois <- selectRoiSet(roiH,default_level = 2,exceptions = list("FB"=4,"LAL(R)"=4,"CRE(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,2,1,1))
labelRoisFB <- selectRoiSet(roiH,default_level = 0,exceptions = list("FB"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))
FBTypes <- mutate(FBTypes,type=stringr::str_replace(type,"Delta","\u0394"))

FBSummary <- getROISummary(FBTypesTable,threshold=0) #%>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
FBSummary_ttFiltered <- filterROISummary(FBSummary,FBTypesTable,FBTypes,FBRois)# %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))

FBSummary <- FBSummary %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
FBSummary_ttFiltered <- FBSummary_ttFiltered %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
FBTypes <- FBTypes %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```

```{r}
haneschFB14R <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & grepl("FB[1-4]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid()) 
haneschFB14R_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & grepl("FB[1-4]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid()) 
haneschFB14R
haneschFB14R_ttF
```
```{r}
haneschFB56R <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & grepl("FB[5-6]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid())
haneschFB56R_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & grepl("FB[5-6]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid()) 
haneschFB56R 
haneschFB56R_ttF
```
```{r}
haneschFB79R <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & grepl("FB[7-9]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid()) 
haneschFB79R_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & grepl("FB[7-9]",type) & !grepl("_L",type)),roiSelect=FBRois,flip = T,roiLabel = labelRoisFB,grouping="supertype1",interactive = TRUE,showCount = T,theme=theme_paper_grid())
haneschFB79R
haneschFB79R_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight1-4.svg"),haneschFB14R,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight5-6.svg"),haneschFB56R,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight7-9.svg"),haneschFB79R,nrow=1,ncol=2,base_width = 8.5/2)

save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight1-4_filtered.svg"),haneschFB14R_ttF,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight5-6_filtered.svg"),haneschFB56R_ttF,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBTangentialsRight7-9_filtered.svg"),haneschFB79R_ttF,nrow=1,ncol=2,base_width = 8.5/2)
```

```{r}
haneschFBOutLay <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBOutLay_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBOutLay
haneschFBOutLay_ttF
```

```{r}
interHaneschFBQL <- girafe(ggobj = haneschFBOutLay, width_svg=12,height_svg=8,
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBQL,paste0(haneschSaveFolder,"FB/FBQsLeft.html"))
```

```{r}
save_plot(paste0(haneschSaveFolder,"FB/FBQsLeft.svg"),haneschFBOutLay,nrow=1,ncol=1.5,base_width=8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBQsLeft_filtered.svg"),haneschFBOutLay_ttF,nrow=1,ncol=1.5,base_width=8.5/2)
```

```{r}
haneschFBColL <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Columnar") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBColL_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Columnar") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBColL
haneschFBColL_ttF
```
```{r}
interHaneschFBColL <- girafe(ggobj = haneschFBColL, width_svg=12,height_svg=8
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBColL,paste0(haneschSaveFolder,"FB/FBColumnarLeft.html"))
```

```{r}
save_plot(paste0(haneschSaveFolder,"FB/FBColsLeft.svg"),haneschFBColL,nrow=1,ncol=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBColsLeft_filtered.svg"),haneschFBColL_ttF,nrow=1,ncol=1.5,base_width = 8.5/2)
```

```{r}
haneschDeltas <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Interneuron") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschDeltas_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Interneuron") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschDeltas
haneschDeltas_ttF
```
```{r}
interHaneschDelta <- girafe(ggobj = haneschDeltas, width_svg=10,height_svg=7)
```

```{r}
htmlwidgets::saveWidget(interHaneschDelta,paste0(haneschSaveFolder,"FB/FBDeltas.html"))
```

```{r}
save_plot(paste0(haneschSaveFolder,"FB/FBDeltas.svg"),haneschDeltas,nrow=1,ncol=1.5,base_width = 8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBDeltas_filtered.svg"),haneschDeltas_ttF,nrow=1,ncol=1.5,base_width = 8.5/2)
```

### Full FB schematic?

```{r}
summaryFB <- FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output" | supertype3 == "FB Interneuron" | supertype3 == "FB Columnar") & !grepl("_R",type))
summaryFB$supertype2 <- factor(summaryFB$supertype2,levels=c("PFN","vΔ","hΔ","PFGs","PFR","PFL","FC","FS","FR"))
summaryFB_ttF <- FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output" | supertype3 == "FB Interneuron" | supertype3 == "FB Columnar") & !grepl("_R",type))
summaryFB_ttF$supertype2 <- factor(summaryFB_ttF$supertype2,levels=c("PFN","vΔ","hΔ","PFGs","PFR","PFL","FC","FS","FR"))
```


```{r}
haneschFBSummary <- haneschPlot(summaryFB,roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBSummary_ttF <- haneschPlot(summaryFB_ttF,roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBSummary
haneschFBSummary_ttF
```

```{r}
save_plot(paste0(haneschSaveFolder,"FB/FBSummary.svg"),haneschFBSummary,nrow=1,ncol=2,base_width=8.5/2)
save_plot(paste0(haneschSaveFolder,"FB/FBSummary_filtered.svg"),haneschFBSummary_ttF,nrow=1,ncol=2,base_width=8.5/2)
```

```{r}
interHaneschFBSummary <- girafe(ggobj = haneschFBSummary, width_svg=13,height_svg=7
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBSummary,paste0(haneschSaveFolder,"FB/FBSummary.html"))
```

