---
title: "PB Figure 3"
output: html_notebook
---


```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(neuprintrExtra)
library(reshape2)
library(patchwork)
library(ggnewscale)
library(gridExtra)

source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\PBAnalysisUtils.R")
```

Specify plotting text sizes
```{r}
tickLabSz <- 6
axLabSz <- 8
legSz <- 6
legTitSz <- 8
pltTit <- 8

theme_set(theme(axis.title = element_text(size = axLabSz), 
      axis.text = element_text(size = tickLabSz),
      legend.text = element_text(size = legSz),
      legend.title = element_text(size = legTitSz),
      plot.title = element_text(size = pltTit)))

```

Get the connection tables from EPGs, D7s, IBSpsP, and SpsP Neurons to other FB types
```{r}
nronTypes <- c("EPG","Delta7","IbSpsP","SpsP",
               "PEN_a(PEN1)","PEN_b(PEN2)","PEG",
               "PFNa","PFNd","PFNm_a","PFNm_b","PFNp_a","PFNp_b","PFNp_c","PFNp_d","PFNp_e","PFNv",
               "PFGs","PFR_a","PFR_b","PFL1","PFL2","PFL3")
ROI = "PB"
  
# Get the connection tables
conTab <- getConnectionTable(getTypesTable(nronTypes)$bodyid,
                             "POST",ROI) %>% filter(type.to %in% nronTypes)

conTab$nameid <- PBRename(conTab$name.from,conTab$from)
conTab$partnerid <- PBRename(conTab$name.to,conTab$to)

conmatPlot <- ggplot(conTab) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(conTab$weightRelative),
                       limits=c(0,max(conTab$weightRelative))) +
  geom_tile(aes(partnerid,nameid,fill=weightRelative)) +
  theme_cowplot() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,size=4,hjust=1),
        axis.text.y = element_text(size=4)) +
  xlab("pre-synaptic neuron") + ylab("post-synaptic neuron")

print(conmatPlot)
```

```{r}
typeToType <- getTypeToTypeTable(conTab)

plt_order = c("Delta7","EPG","IbSpsP", "PEN_a(PEN1)","PEN_b(PEN2)","PEG","PFGs",
              "PFNa","PFNd","PFNm_a","PFNm_b","PFNp_a","PFNp_b","PFNp_c","PFNp_d","PFNp_e","PFNv",
              "PFL1","PFL2","PFL3","PFR_a","PFR_b","SpsP")
typeToType$type.from <- factor(typeToType$type.from,levels=plt_order)
typeToType$type.to <- factor(typeToType$type.to,levels=plt_order)

conmatPlot_T2T <- ggplot(typeToType %>% filter(type.from != "PFR_b")) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(typeToType$weightRelative),
                       limits=c(0,max(typeToType$weightRelative))) +
  geom_tile(aes(type.to,type.from,fill=weightRelative)) +
  theme_minimal() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,hjust=1)) +
  xlab("post-synaptic type") + ylab("pre-synaptic type") +
  geom_hline(yintercept = 0.5) + geom_hline(yintercept = 3.5) + geom_hline(yintercept = 5.5) +
  geom_vline(xintercept = 0.5) + geom_vline(xintercept = 3.5) + geom_vline(xintercept = 23.5) 

print(conmatPlot_T2T)
```

```{r}
conmatPlot_T2T
save_plot('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\PB\\ForPaper\\PBTypeToType.pdf',conmatPlot_T2T)
```

Look at PFNv connectivity in the FB
```{r}
nronTypes <- c("PFNv")
ROI = "CX"
  
# Get the connection tables
conTab_PFNv_PRE <- getConnectionTable(getTypesTable(nronTypes)$bodyid,"PRE",ROI)

typeToType_PFNv_PRE <- getTypeToTypeTable(conTab_PFNv_PRE)

plt_order = c("Delta7","EPG","IbSpsP","LPsP","ExR5","OA-VPM3","FB1H","FB4B","FB4M","PFR_b","LNO2","LNO3","PFNv")
typeToType_PFNv_PRE$type.from = factor(typeToType_PFNv_PRE$type.from, levels = plt_order)

conmatPlot_PFNv <- ggplot(typeToType_PFNv_PRE %>% filter(type.from != "PFR_b")) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", 
                       midpoint =0.5*max(typeToType_PFNv_PRE$weightRelative),
                       limits=c(0,max(typeToType_PFNv_PRE$weightRelative))) +
  geom_tile(aes(type.to,type.from,fill=weightRelative)) +
  theme_cowplot() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,hjust=1)) +
  xlab("post-synaptic neuron") + ylab("pre-synaptic neuron")

conmatPlot_PFNv
save_plot('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\PB\\ForPaper\\PFNvInputs.pdf',conmatPlot_PFNv)
```

Create a Hanesch plot showing where the IbSpsP neurons get their input
```{r}

IbSpsPs <- getTypesTable("IbSpsP")
#IbSpsPs[which(IbSpsPs$cellBodyFiber == 'PDM21'),]$type = "IbSpsP_R"
#IbSpsPs[which(grepl('_R',IbSpsPs$name)),]$type = "IbSpsP_R"
#IbSpsPs[which(is.na(IbSpsPs$cellBodyFiber)),]$type = "IbSpsP_L"
#IbSpsPs[which(grepl('_L',IbSpsPs$name)),]$type = "IbSpsP_L"

ISP_ins <- getROISummary(IbSpsPs)

IbSpsP_in_ROIs <- haneschPlot(ISP_ins)

IbSpsP_in_ROIs
save_plot('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\PB\\ForPaper\\IbSpsPIns.pdf',IbSpsP_in_ROIs)
```



Create a type-to-type table for P1-9, LPsP
```{r}
NM_CT_PB_POST <- getConnectionTable(getTypesTable(c("LPsP","P1-9"))$bodyid,"POST","PB")
NM_CT_PB_POST <- NM_CT_PB_POST %>% filter(!is.na(type.to) & !is.na(type.from)) %>%
  filter(type.to !="SIFa" & type.from !="SIFa")

NM_T2T_PB_POST <- getTypeToTypeTable(NM_CT_PB_POST)

T2TPlot_NM_PB_POST <- ggplot(NM_T2T_PB_POST) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black",
                       midpoint =0.5*max(NM_T2T_PB_POST$outputContribution),
                       limits=c(0,max(NM_T2T_PB_POST$outputContribution))) +
  geom_tile(aes(type.to,type.from,fill=outputContribution)) +
  theme_cowplot() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,hjust=1)) +
  xlab("pre-synaptic type") + ylab("post-synaptic type")

print(T2TPlot_NM_PB_POST)
```

