---
title: "Delta7 naming"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\visualizeConnectivityTables.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\neuprintQueryUtils.R")
options(nat.plotengine = 'rgl')
```

Connect to neuprint
```{r}
neuprint_login()
```

Sort the Delta 7s according to their max output column
```{r}
# Get the connection matrix from the Delta 7s to the PEN2s
Delta7_2_PEN2 <- getConnectionTable_forSubset(
  unique(neuprint_search("Delta7.*")$bodyid),
  unique(neuprint_search("EPG.*")$bodyid),
  "PB")

# Create a lookup table of bodyids to names for the Delta 7s based off of where they strongly output to the PEN2s
Delta7bodyids = Delta7_2_PEN2$partner %>% unique()
Delta7names= c()

for (d in 1:length(Delta7bodyids)){
  
  # Find the P-EN2 glomeruli that receives the max output from the given D7 and 
  datNow = Delta7_2_PEN2[which(Delta7_2_PEN2$partner == Delta7bodyids[d]),]
  PENnmPrts1 = datNow$name[which.max(datNow$weight)] %>% as.character() %>% strsplit('_')
  Glom1 = PENnmPrts1[[1]][[2]]
  
  datNow <- datNow[which(!grepl(Glom1,datNow$name)),]
  PENnmPrts2 = datNow$name[which.max(datNow$weight)] %>% as.character %>% strsplit('_')
  Glom2 = PENnmPrts2[[1]][[2]]
  
  while (grepl(substring(Glom1,1,1),substring(Glom2,1,1)) &
         ((as.integer(substring(Glom1,2,2)) == as.integer(substring(Glom2,2,2))+1)|
          (as.integer(substring(Glom1,2,2)) == as.integer(substring(Glom2,2,2))-1))) {
    datNow <- datNow[which(!grepl(Glom2,datNow$name)),]
    PENnmPrts2 = datNow$name[which.max(datNow$weight)] %>% as.character %>% strsplit('_')
    Glom2 = PENnmPrts2[[1]][[2]]
          }
  
  D7nmPrts = datNow$partnerName[which.max(datNow$weight)] %>% as.character() %>% strsplit('_')
  
  Delta7names = append(Delta7names,
                       paste(D7nmPrts[[1]][[1]], Glom1, Glom2, D7nmPrts[[1]][[3]], sep = '_'))
}

Delta7Lookup = data.frame(bodyids = Delta7bodyids, name = Delta7names)

```

A function to replace Delta 7 names according to the lookup table in connection matrices
```{r}

Delta7Rename <- function(df,Delta7Lookup){

  dfNames = df$name %>% as.character()
  dfPartnerNames = df$partnerName %>% as.character()
  dfBodyIds = df$bodyid %>% as.numeric()
  dfPartnerBodyIds = df$partner %>% as.numeric()
  for (bid in 1:nrow(Delta7Lookup)){
    dfNames[which(dfBodyIds == Delta7Lookup$bodyids[bid])] <- Delta7Lookup$name[bid] %>% as.character()
    dfPartnerNames[which(dfPartnerBodyIds == Delta7Lookup$bodyids[bid])] <- Delta7Lookup$name[bid] %>% as.character()
  }
  
  D7Gloms = strsplit(as.character(Delta7Lookup$name),"_") %>% lapply(function(x){x[3]}) %>% unlist()
  D7Names = Delta7Lookup$name %>% as.character()
  
  df$name <- factor(dfNames,
                  levels = unique(append(append(
                    sort(
                      D7Names[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      D7Names[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfNames[which(!(dfNames %in% D7Names))])))
  
  df$partnerName <- factor(dfPartnerNames,
                  levels = unique(append(append(
                    sort(
                      D7Names[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      D7Names[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfPartnerNames[which(!(dfPartnerNames %in% D7Names))])))
  
  
  df$nameid <- paste(as.character(df$name), as.character(df$bodyid), sep = "_")
  dfNameIds = df$nameid %>% as.character()
  D7Gloms = strsplit(dfNameIds,"_") %>% lapply(function(x){x[3]}) %>% unlist()
  df$nameid <- factor(dfNameIds,
                  levels = unique(append(append(
                    sort(
                      dfNameIds[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      dfNameIds[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfNameIds[which(!grepl("Delta7",dfNameIds))])))
  
  
  df$partnerid <- paste(as.character(df$partnerName), as.character(df$partner), sep = "_")
  dfPartnerIds = df$partnerid %>% as.character()
  D7Gloms = strsplit(dfPartnerIds,"_") %>% lapply(function(x){x[3]}) %>% unlist()
  df$partnerid <- factor(dfPartnerIds,
                  levels = unique(append(append(
                    sort(
                      dfPartnerIds[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      dfPartnerIds[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfPartnerIds[which(!grepl("Delta7",dfPartnerIds))])))
  
  return(df)
}
```


Check that the D7s are sorted properly
```{r}
Delta7_2_PEN2 <- Delta7Rename(Delta7_2_PEN2,Delta7Lookup)

D7Gloms = strsplit(as.character(Delta7_2_PEN2$partnerid),"_") %>% lapply(function(x){x[3]}) %>% unlist()
D7Gloms <- strsplit(D7Gloms,"-") %>% lapply(function(x){x[1]}) %>% unlist()
D7Names = Delta7_2_PEN2$partnerid %>% as.character()

Delta7_2_PEN2$nameid <- factor(Delta7_2_PEN2$nameid,
        levels = glomSort(Delta7_2_PEN2$nameid))

plotConnectivityMatrix(Delta7_2_PEN2, synapseCutOff = 2, 0)
```