---
title: "Dynamic visualizations"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(gridExtra)
library(paletteer)
library(visNetwork) 
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\pathways.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\R\\supertypeUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\visualizeConnectivityTables.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\neuprintQueryUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\colorCodeLookup.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\FBNetworkVisUtils.R")
options(nat.plotengine = 'rgl')
```

Connect to neuprint
```{r}
neuprint_login()
```

Get a connection table (type to type)
```{r}
nronTypes <- c("PFN","Delta0","Delta6","PFR_a","PFG","FC","PFL","^FR","FS","PFR_b")
ROI = "FB"
  
# Get the connection table
conTab <- getConnectionTable_forSubset(getBodyIdsForList(nronTypes)$bodyid,
                                         getBodyIdsForList(nronTypes)$bodyid,
                                         ROI)

typeToType_Clean <- getTypeToTypeTable(conTab)
```

Specify an x and y lookup table of the location for each neuron type
```{r}
xyLookup <- xyLookupTableInner()
```

Create a dynamic visualization of the FB network data
```{r}
# Get the table of nodes (types)
nodes = data.frame(name = unique(c(typeToType_Clean$type.from,typeToType_Clean$type.to)))
nodes$id <- 1:nrow(nodes)
nodes$superType <- nodes$name %>% as.character %>% supertype()

# Position the nodes according to the lookup table
nodes$x <- sapply(nodes$name, function(x) xyLookup$x[match(x,xyLookup$type)])
nodes$y <- sapply(nodes$name, function(x) xyLookup$y[match(x,xyLookup$type)])

# Get the edges from the connection table
edges <- typeToType_Clean[which((typeToType_Clean$type.from %in% nodes$name) & (typeToType_Clean$type.to %in% nodes$name)),] %>%
  mutate(to = sapply(type.to, function(f) which(f == nodes$name)),
         from = sapply(type.from, function(f) which(f == nodes$name)))
edges$superType <- edges$type.from %>% as.character %>% supertype()
  
# Specify colors for the supertypes
sTs <- xyLookup$type %>% as.character() %>% supertype() %>% unique() %>% sort()
pcCols <- paletteer_d("Polychrome::palette36")
sTCols <- c(pcCols[35],pcCols[32],pcCols[9],pcCols[3],pcCols[25],pcCols[27],pcCols[7],pcCols[26],pcCols[1])

# Set the node properties for the visulization
vis.nodes <- nodes[,c("name","id")]
vis.nodes$type.name <- nodes$name %>% as.character()
vis.nodes$title <- nodes$name %>% as.character()
vis.nodes$label <- ""
vis.nodes$font.size <- 12
vis.nodes$x <- nodes$y*500
vis.nodes$y <- nodes$x*500
vis.nodes$size <- 10
vis.nodes$color.background <- sTCols[match(nodes$superType,as.factor(sTs))]
vis.nodes$color.highlight <- sTCols[match(nodes$superType,as.factor(sTs))]
vis.nodes$color.border <- "black"
vis.nodes$color.highlight.border <- "orange"
vis.nodes$group <- as.character(nodes$superType)

# Set the link properties for the visualization
vis.links <- edges[,c("to","from")]
vis.links$width <- edges$weightRelative*20
vis.links$arrows <- "to"
vis.links$smooth <- TRUE
vis.links$color <- sTCols[match(edges$superType,as.factor(sTs))]

# Create the visualization
v <- visNetwork(vis.nodes, vis.links, width="100%", height="800px",main= "inputs -> outputs") %>% 
  visNodes(fixed = TRUE) %>% 
  visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE, degree = 1,algorithm="hierarchical"), selectedBy = "type.name") 

# Set a color for each group (need to do this for the legend)
for (st in 1:length(sTs)){
  v <- v %>% visGroups(groupname = sTs[st], color = sTCols[st])
}

# Add a legend and the ability to select multiple nodes
v <- v %>% visLegend(width=0.2, main="super type",ncol=3) %>% visInteraction(multiselect = TRUE)

# Save the plot
visSave(v, "C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FB\\NetworkDiagrams\\AllColumnarConnections.html", selfcontained = TRUE, background = "white")
```