---
title: "Notebook for analysing information flow between Ring neurons inside the EB"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
library(dplyr)
options(nat.plotengine = 'rgl')
```

```{r}
neuprint_login()
```

### Look at what are major inputs/outputs to a neuron type
```{r}
mytype = "TuBu"
postIDs = neuprint_search(paste(mytype,'.*',sep=""))

slctROI = "AOTU(R)"

myConnections = neuprint_connection_table(postIDs$bodyid, "PRE",slctROI)

myConnections = myConnections %>%
                       mutate(partnerName = neuprint_get_meta(as.numeric(partner))[["name"]],
                              name = neuprint_get_meta(as.numeric(bodyid))[["name"]],
                              partnertype = neuprint_get_meta(as.numeric(partner))[["type"]],
                              type = neuprint_get_meta(as.numeric(bodyid))[["type"]]) %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup()

```

```{r}
ggplot(myConnections, aes(x=partnertype, fill=partnertype)) + geom_bar() + theme_classic() + 
  theme(axis.text.x = element_text(angle = 90)) + guides(fill=FALSE)
```


### Connectivity matrix

```{r}
preNeuron = c("ExR","R3","R2","R4","R5","R6","EPG")#c("ExR","R3","R2","R4","EPG")#c("MC","TuBu")#c("R3","R2","R4","TuBu")#
postNeuron = c("ExR","R3","R2","R4","R5","R6","EPG")#c("ExR","R3","R2","R4","EPG")#c("MC","TuBu")#c("R3","R2","R4","TuBu")#

preName =  "ExRs, R2-6 & EPG"#"MCs and TuBus"#"R2-4 and TuBus"#"ExRs, R2-4 & EPG"
postName =  "ExRs, R2-6 & EPG"#"MCs and TuBus"#"R2-4 and TuBus"#"ExRs, R2-4 & EPG"

saveName = "_ExR_R2-6_EPG"#"_MCs_TuBus"#"_R2-4s_TuBU"#"_ExR_R2-4_EPG"

slctROI = "EB"

preIDs = neuprint_search(paste(preNeuron[1],'.*',sep=""))
postIDs = neuprint_search(paste(postNeuron[1],'.*',sep=""))

if (length(preNeuron) > 1){
  for (i in seq(2,length(preNeuron))){
      preIDs = bind_rows(preIDs, neuprint_search(paste(preNeuron[i],'.*',sep="")))
  }
}

if (length(postNeuron) > 1){
  for (i in seq(2,length(postNeuron))){
      postIDs = bind_rows(postIDs, neuprint_search(paste(postNeuron[i],'.*',sep="")))
  }
}
myConnections = neuprint_connection_table(preIDs$bodyid, "POST",slctROI)

myConnections = myConnections %>%
                       mutate(partnerName = neuprint_get_meta(as.numeric(partner))[["name"]],
                              name = neuprint_get_meta(as.numeric(bodyid))[["name"]],
                              partnertype = neuprint_get_meta(as.numeric(partner))[["type"]],
                              type = neuprint_get_meta(as.numeric(bodyid))[["type"]]) %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup()  %>% filter(partner %in% postIDs$bodyid) 

myConnections$nameid = paste(as.character(myConnections$name), as.character(myConnections$bodyid), sep = "_")
myConnections$partnerid = paste(as.character(myConnections$partnerName), as.character(myConnections$partner), sep = "_")
```

```{r}
ggplot(myConnections  %>% filter(weight > 3)) + geom_tile(aes(partnerName,name,fill=weight)) + 
  theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low = "grey", mid = "tan", high = "maroon4")+
  xlab("Post-synaptic neuron")+ylab("Pre-synaptic neuron") + labs(fill="# synapses") +
  labs(title=paste(preName,'to', postName, 'Connectivity within', slctROI, sep=' '))

ggsave( paste("connectivityMatrix",saveName, '.pdf', sep=''), plot = last_plot(), device='pdf', path = "../neuprintR_analysis_plots/",
  scale = 1.5, width = 20, height = 15, units ="cm", dpi = 600, limitsize = TRUE)
```

```{r}

ggplot(myConnections  %>% filter(weight > 3)) + geom_tile(aes(partnerid,nameid,fill=weight)) + 
  theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low = "grey", mid = "tan", high = "maroon4")+
  xlab("Post-synaptic neuron")+ylab("Pre-synaptic neuron") + labs(fill="# synapses in EB") +
  labs(title=paste(preName,'to', postName, 'Connectivity within EB', sep=' '))

ggsave(paste("connectivityMatrix",saveName, '_byID.pdf', sep=''), plot = last_plot(), device='pdf', path = "../neuprintR_analysis_plots/",
  scale = 1.5, width = 20, height = 16, units ="cm", dpi = 600, limitsize = TRUE)
```


###  Draw graph
```{r}

preNeuron = c("ExR","R3","R2","R4","R5","R6","EPG")#c("ExR","R3","R2","R4","EPG")#c("MC","TuBu")#c("R3","R2","R4","TuBu")#
postNeuron = c("ExR","R3","R2","R4","R5","R6","EPG")#c("ExR","R3","R2","R4","EPG")#c("MC","TuBu")#c("R3","R2","R4","TuBu")#

preName =  "ExRs, R2-6 & EPG"#"MCs and TuBus"#"R2-4 and TuBus"#"ExRs, R2-4 & EPG"
postName =  "ExRs, R2-6 & EPG"#"MCs and TuBus"#"R2-4 and TuBus"#"ExRs, R2-4 & EPG"

saveName = "_ExR_R2-6_EPG"#"_MCs_TuBus"#"_R2-4s_TuBU"#"_ExR_R2-4_EPG"

slctROI = "EB"


preIDs = neuprint_search(paste(preNeuron[1],'.*',sep=""))
postIDs = neuprint_search(paste(postNeuron[1],'.*',sep=""))

if (length(preNeuron) > 1){
  for (i in seq(2,length(preNeuron))){
      preIDs = bind_rows(preIDs, neuprint_search(paste(preNeuron[i],'.*',sep="")))
  }
}

if (length(postNeuron) > 1){
  for (i in seq(2,length(postNeuron))){
      postIDs = bind_rows(postIDs, neuprint_search(paste(postNeuron[i],'.*',sep="")))
  }
}

myConnections = neuprint_connection_table(preIDs$bodyid, "POST",slctROI)

myConnections = myConnections %>%
                       mutate(partnerName = neuprint_get_meta(as.numeric(partner))[["name"]],
                              name = neuprint_get_meta(as.numeric(bodyid))[["name"]],
                              partnertype = neuprint_get_meta(as.numeric(partner))[["type"]],
                              type = neuprint_get_meta(as.numeric(bodyid))[["type"]]) %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup()  %>% filter(partner %in% postIDs$bodyid) 

myConnections$nameid = paste(as.character(myConnections$name), as.character(myConnections$bodyid), sep = "_")
myConnections$partnerid = paste(as.character(myConnections$partnerName), as.character(myConnections$partner), sep = "_")
```


Reroganize to make graph with types instead of bodyids
```{r}
graphData = data.frame(from = myConnections$type, to = myConnections$partnertype, weight = myConnections$weight)
graphData_compressed = graphData %>% group_by(from, to) %>% summarise(weight = mean(weight, na.rm = TRUE)) %>% ungroup()
```

```{r, message=FALSE}
require(igraph)
sp_graph = graph_from_data_frame(graphData_compressed)
sp_graph
```

```{r}
nodes  = union(unique(graphData_compressed$from), unique(graphData_compressed$to))
nodes
typepal = colors()[c(76, 76, 97, 97, 97, 96, 97, 92, 92, 10, 10, 20, 20, 20, 25, 25, 25, 36, 33, 33, 58, 58, 58, 12, 12, 74, 44, 87)] # R2-6, EPGs,PENs
#colors()[c(10, 10, 20, 20, 20, 25, 25, 36, 33, 33, 58, 58, 58, 12, 12, 74, 44,44,44,44,44,87,87,87)]
#colors()[c(76, 76, 62, 62, 97, 97, 97, 96, 97, 92, 92, 10, 10, 20, 20, 20, 25, 25, 25, 36, 33, 33, 58, 58, 58, 12, 12, 74)] # R2-4, EPGs,PENs
#colors()[c(76, 76, 10, 10, 20,20,20, 25, 25, 25, 36, 33, 33, 55, 55, 55, 12, 12, 15)] # R2-4 + EPGs
#colors()[c(70, 55, 20, 20, 33, 12, 25, 76, 12, 25, 33, 25, 25, 25, 55, 33, 10,  10, 76)] # no EPGs
typepal
```

```{r}
l <- layout_with_fr(sp_graph)#layout_in_circle(sp_graph)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)
edge.start <- ends(sp_graph, es=E(sp_graph), names=F)[,1]
edge.col = V(sp_graph)$color[edge.start]
plot(sp_graph, edge.arrow.size=0.5, 
     vertex.size=20,vertex.vertex.frame.color="gray", vertex.color=typepal,
     vertex.label.cex=0.8,vertex.label.color="black", vertex.label.dist=0,
     edge.width=E(sp_graph)$weight/10, layout=l)

```

```{r}
#hist(graphData$weight)
cutoff <- 3
sp_graph_trimmed <- delete_edges(sp_graph, E(sp_graph)[weight<cutoff])

# Set node size based on audience size:
#V(sp_graph_trimmed)$size <- V(sp_graph_trimmed)$...

# The labels are currently node IDs. Setting them to NA will render no labels
V(sp_graph_trimmed)$label.color="black"
V(sp_graph_trimmed)$label.cex=0.8
V(sp_graph_trimmed)$label.dist=0

V(sp_graph_trimmed)$size=7
V(sp_graph_trimmed)$vertex.frame.color="gray"
V(sp_graph_trimmed)$color=typepal

# Set edge width based on weight:
E(sp_graph_trimmed)$width <- E(sp_graph_trimmed)$weight/10.
#change arrow size and edge color:
E(sp_graph_trimmed)$arrow.size <- .2
#E(sp_graph_trimmed)$edge.color <- "gray80"
edge.start <- ends(sp_graph_trimmed, es=E(sp_graph_trimmed), names=F)[,1]
edge.col = V(sp_graph_trimmed)$color[edge.start]

l <- layout_with_fr(sp_graph_trimmed) # layout_components
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

#pdf("../neuprintR_analysis_plots/connectivityGraph_R2-R4andEPGs.pdf", width = 200, height = 200)#, units ="cm", dpi = 600)
plot(sp_graph_trimmed,edge.color=edge.col, edge.curved=0.5, layout=l)
#dev.off()
dev.print(pdf, paste("../neuprintR_analysis_plots/connectivityGraph",saveName, "_in", slctROI,".pdf", sep=""), width=15, height=15)
#ggsave("connectivityGraph_R2-R4andEPGs.pdf", plot = last_plot(), device='pdf', path = "../neuprintR_analysis_plots/",
#  scale = 1.5, width = 20, height = 15, units ="cm", dpi = 600, limitsize = TRUE)
```

```{r}
hs <- hub_score(sp_graph_trimmed, weights=NA)$vector
as <- authority_score(sp_graph_trimmed, weights=NA)$vector

par(mfrow=c(1,2))
plot(sp_graph_trimmed, vertex.size=hs*40, main="Hubs", layout = l)
plot(sp_graph_trimmed, vertex.size=as*40, main="Authorities", layout = l)

```
```{r}
cfg <- cluster_edge_betweenness(as.undirected(sp_graph_trimmed))
#plot(cfg, as.undirected(sp_graph_trimmed))

V(sp_graph_trimmed)$community <- cfg$membership
colrs <- adjustcolor( c("seagreen", "orange", "tomato",  "gold", "plum","yellowgreen","cyan"), alpha=.6)
plot(sp_graph_trimmed, vertex.color=colrs[V(sp_graph_trimmed)$community])
```

```{r}
deg <- degree(sp_graph_trimmed, mode="all")
deg.dist <- degree_distribution(sp_graph_trimmed, cumulative=T, mode="all")
plot( x=0:max(deg), y=1-deg.dist, pch=19, cex=1.2, col="orange",
      xlab="Degree", ylab="Cumulative Frequency")
```


Interactive graph
```{r}
library(networkD3)
require(igraph)

# Plot
p <- simpleNetwork(graphData, height="100px", width="100px",        
        Source = 1,                 # column number of source
        Target = 2,                 # column number of target
        linkDistance = 10,          # distance between node. Increase this value to have more space between nodes
        charge = -900,              # numeric value indicating either the strength of the node repulsion (negative value) or attraction (positive value)
        fontSize = 14,               # size of the node names
        fontFamily = "serif",       # font og node names
        linkColour = "#666",        # colour of edges, MUST be a common colour for the whole graph
        nodeColour = "#69b3a2",     # colour of nodes, MUST be a common colour for the whole graph
        opacity = 0.9,              # opacity of nodes. 0=transparent. 1=no transparency
        zoom = T                    # Can you zoom on the figure?
        )

p

# save the widget
# library(htmlwidgets)
# saveWidget(p, file=paste0( getwd(), "/HtmlWidget/networkInteractive1.html"))

```

```{r}
# Thus we can plot it
p <- sankeyNetwork(Links = data.frame(source = graphData$from,
                                      target = graphData$to,
                                      value = graphData$weight), 
                   Nodes = myConnections["bodyid"], Source = "source",
                   Target = "target", Value = "value", NodeID = "bodyid",
                   units = "TWh", fontSize = 12, nodeWidth = 30)
p

```

```{r}
library(ggraph)

# Basic graph
ggraph(graphData) + 
  geom_conn_bundle(data = get_con(from = graphData$from, to = graphData$to), alpha=0.2, colour="skyblue", tension = .5) + 
  geom_node_point(aes(filter = leaf, x = x*1.05, y=y*1.05)) +
  theme_void()

```

### Path analysis
```{r}
body_pre = 1077459077 # TuBu1
body_post = 387364605 # EPG
pathlen = 3

pathTU_2_EPG = neuprint_get_paths(
  body_pre,
  body_post,
  pathlen,
  weightT = 3,
  #roi = NULL,
)

head(pathTU_2_EPG)
```


```{r}
body_pre = 1077459077 # TuBu1
body_post = 387364605 # EPG

shortest_pathTU_2_EPG = neuprint_get_shortest_paths(
  body_pre,
  body_post,
  weightT = 5,
  #roi = NULL,
)

shortest_pathTU_2_EPG
```

Reroganize to make graph with types instead of bodyids
```{r}
pathTU_2_EPG_type = data.frame(from = pathTU_2_EPG$name.from, to = pathTU_2_EPG$name.to, weight = pathTU_2_EPG$weight)
```

Make color palatte for nodes (neuron types)
```{r}
nodes  = union(unique(pathTU_2_EPG_type$from), unique(pathTU_2_EPG_type$to))
typepal = colors()[c(10,14,20,40)]
typepal
```

```{r, message=FALSE}
require(igraph)
sp_graph = graph_from_data_frame(pathTU_2_EPG_type)
sp_graph
```

```{r}
plot(sp_graph, edge.arrow.size=0.8, 
     vertex.size=40,vertex.vertex.frame.color="gray", vertex.color=typepal,
     vertex.label.cex=0.8,vertex.label.color="black", vertex.label.dist=0,
     edge.width=E(sp_graph)$weight/20)

```

```{r}



```


```{r}

queryNow = "MATCH p = (src :`hemibrain_Neuron` { bodyId: 974627674 })-[:ConnectsTo*0..3]->(dest:`hemibrain_Neuron`{ bodyId: 757694775 }) WHERE ALL (x in relationships(p) WHERE x.weight >= 10 AND EXISTS(apoc.convert.fromJsonMap(x.roiInfo).FB)) RETURN length(p) AS `length(path)`, [n in nodes(p) | [n.bodyId, n.type]] AS path, [x in relationships(p) | x.weight] AS weights"

# )

pathsQuery = neuprint_fetch_custom(cypher = queryNow)

```