---
title: "Look for left/right asymmetry in synapse counts"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
library(dplyr)
options(nat.plotengine = 'rgl')

neuprint_login()
```

```{r, messages=FALSE, warning=FALSE}
# Get some custom functions
source("neuprintQueryUtils.R")
source("visualizeConnectivityTables.R")
source("InputOutputByTypeUtils.R")
source("romainNeuronsInRoi.R")
```


### Make selection of neurons to be used in connecitivy analysis
This should be done based on some broadly used criteria. Alternatively, one could read in previously curated lists of neurons.
```{r}
ROI = "NO"
neuronName = paste0("LRasymmetry ExR", ROI)#paste0("Ring & EPG connectivity ", ROI)
saveName = paste0("LRasymmetry_ExR")

useCuratedList = FALSE#TRUE#

if (useCuratedList) {
  # load list
  
  load(paste0("/Users/haberkernh/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/",ROI,"/",ROI,"_Types.RData"))
  
  # select neurons from there
  neuronList = get(paste0(ROI,"_Type"))
  neuronList <- gsub("\\(.*\\)", "", neuronList)
  
  neuronIDs = getBodyIdsForList(neuronList, field="type")  %>% mutate(databaseType = type)

} else{
  neuronList = c("ExR")#c("PEN", "EPG", "PEG")
  neuronIDs = getBodyIdsForList(neuronList, field="type")  %>% mutate(databaseType = type)
}

```

```{r}
myNBag = buildInputsOutputsByType(neuronIDs,fixed=FALSE,big=TRUE, nc = 5)
```

```{r}
myNBag = lateralizeInputOutputList(myNBag)
myNBagROISummary = getROISummary(myNBag,filter=FALSE)
```

```{r}
myRoiTree = getRoiTree()
myRoiTree = selectRoiSet(myRoiTree,default_level=2,exceptions=list("NO" = 2),exceptionLevelMatch = 2)
myRoiTree = myRoiTree %>% mutate(myRoi = paste(level2, side4, sep = "_"))

myNBagROISummaryFilt = myNBagROISummary %>% filter(roi %in% myRoiTree$customRois) #%>% filter(roi %in% c("NO", "FB", "PB"))
```

```{r}
plotW = length(unique(myNBagROISummaryFilt$roi))*1.2
plotH = length(unique(neuronIDs$databaseType))*1.2 + 2

regionPlot <- function(myplot, cmax){
  myplot = myplot +
    theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
    scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", 
                       midpoint =cmax/2, limits=c(0,cmax))  + 
    theme(axis.text.x = element_blank(),#axis.text.y = element_blank(), 
          strip.placement = "outside", strip.background = element_rect(fill=NA, colour="grey50")) +
    facet_grid(reorder(databaseType, desc(databaseType)) ~ roi, space="free", scales="free",switch="both")
  
  return(myplot)
}

lrRegionPlot = ggplot(myNBagROISummaryFilt) + geom_tile(aes(y=type,x=roi, fill=InputWeight))
lrRegionPlot = regionPlot(lrRegionPlot, cmax=10000)
print(lrRegionPlot)
ggsave(paste("lrRegionPlot_",saveName,'_inputWeight.pdf', sep=''), 
    plot = lrRegionPlot, device='pdf', path = "../neuprintR_analysis_plots/",
    scale = 2, width = plotW, height =plotH, units ="cm", dpi = 600, limitsize = TRUE)

lrRegionPlot = ggplot(myNBagROISummaryFilt)  + geom_tile(aes(y=type,x=roi, fill=OutputWeight))
lrRegionPlot = regionPlot(lrRegionPlot, cmax=12000)

print(lrRegionPlot)
ggsave(paste("lrRegionPlot_",saveName,'_outputWeight.pdf', sep=''), 
    plot = lrRegionPlot, device='pdf', path = "../neuprintR_analysis_plots/",
    scale = 2, width = plotW, height =plotH, units ="cm", dpi = 600, limitsize = TRUE)

```
