---
title: "MB-CX connections"
output: html_notebook
---

Load the libraries
```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
source("/Users/danc/Repos/neuprintR-notebooks/pathways.R")
source("/Users/danc/Repos/neuprintR-notebooks/visualizeConnectivityTables.R")
source("/Users/danc/Repos/neuprintR-notebooks/neuprintQueryUtils.R")
source("/Users/danc/Repos/neuprintR-notebooks/inputOutputRegionsVis.R")
options(nat.plotengine = 'rgl')
```

Connect to neuprint
```{r}
neuprint_login()
```

Get the MBONs
```{r}
# Find all MBONs
MBON_Names <- neuprint_search("MBON.*")
head(MBON_Names)
```

Find who the MBONs talk to
```{r}
# Find the postsynaptic partners of all MBONs
MBON_PostConnections <- getConnectionTable.data.frame(MBON_Names,synapseType = "POST",synThresh=3)
head(MBON_PostConnections)
```

Among these, find who innervate the CX
```{r}
# Find the MBON postsynaptic partners that innervate the FB


```


Get the FB neuron types
```{r}
```

Find all connections between all MBONs and FB neurons
