---
title: "Noduli"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
options(nat.plotengine = 'rgl')
```

```{r}
neuprint_login()
```

```{r}
no1Connect = neuprint_find_neurons("NO1",all_segments = FALSE)

no2Connect = neuprint_find_neurons("NO2",all_segments = FALSE)

no3Connect = neuprint_find_neurons("NO3",all_segments = FALSE)

```

### Use nat to restrict to neurons really innervating a structure

```{r}
no1Neurons = neuprint_read_neurons(no1Connect$bodyid)
no2Neurons = neuprint_read_neurons(no2Connect$bodyid)
no3Neurons = neuprint_read_neurons(no3Connect$bodyid)
```
```{r}
getROIMesh <- function(ROI){
  roiQuery = neuprintr:::neuprint_fetch(path=paste("api/roimeshes/mesh/hemibrain/",ROI,sep=""),parse.json = FALSE,include_headers = FALSE)
  meshObj = textConnection(httr::content(roiQuery,as="text"))
  rgl::readOBJ(meshObj)
}
```


```{r}
no1Mesh = getROIMesh("NO1")
no2Mesh = getROIMesh("NO2")
no3Mesh = getROIMesh("NO3")
ebMesh = getROIMesh("EB")
pbMesh = getROIMesh("PB")
```
```{r}
plot3d(no1Mesh,alpha=0.2,color="blue")
plot3d(no2Mesh,alpha=0.2,color="orange",add=TRUE)
plot3d(no3Mesh,alpha=0.2,color="green",add=TRUE)
```



```{r}
inNO1 = function(x){subset(x,pointsinside(x,no1Mesh))}
no1NeuronsInNO1 = nlapply(no1Neurons,inNO1,OmitFailures = TRUE)

inNO2 = function(x){subset(x,pointsinside(x,no2Mesh))}
no2NeuronsInNO2 = nlapply(no2Neurons,inNO2,OmitFailures = TRUE)

inNO3 = function(x){subset(x,pointsinside(x,no3Mesh))}
no3NeuronsInNO3 = nlapply(no3Neurons,inNO3,OmitFailures = TRUE)

```
```{r}
summaryNO1 = summary(no1NeuronsInNO1, include.attached.dataframe = TRUE)
summaryNO2 = summary(no2NeuronsInNO2, include.attached.dataframe = TRUE)
summaryNO3 = summary(no3NeuronsInNO3, include.attached.dataframe = TRUE)
```

```{r}
ggplot(summaryNO2) + geom_histogram(aes(endpoints))
```
```{r}
innervatesNO1 = summaryNO1 %>% filter(endpoints>20)
no1Table = neuprint_connection_table(innervatesNO1$bodyid,"POST","NO1")   %>%
                       mutate(partnerName = neuprint_get_meta(partner)[["name"]],name =neuprint_get_meta(bodyid)[["name"]])   %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup() %>% filter(partner %in% bodyid)

innervatesNO2 = summaryNO2 %>% filter(endpoints>20)
no2Table = neuprint_connection_table(innervatesNO2$bodyid,"POST","NO2")   %>%
                       mutate(partnerName = neuprint_get_meta(partner)[["name"]],name =neuprint_get_meta(bodyid)[["name"]])   %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup() %>% filter(partner %in% bodyid)

innervatesNO3 = summaryNO3 %>% filter(endpoints>20)
no3Table = neuprint_connection_table(innervatesNO3$bodyid,"POST","NO3")   %>%
                       mutate(partnerName = neuprint_get_meta(partner)[["name"]],name =neuprint_get_meta(bodyid)[["name"]])   %>% 
                       group_by(name) %>% 
                       mutate(weightRelative = weight/sum(weight)) %>%
                       ungroup() %>% filter(partner %in% bodyid)
```


```{r}
clear3d()
plot3d(no1Neurons[[4]])
plot3d(no1Mesh,alpha=0.2,color="grey",add=TRUE)
plot3d(ebMesh,alpha=0.2,color="grey",add=TRUE)
#plot3d(pbMesh,alpha=0.2,color="grey",add=TRUE)
plot3d(no1NeuronsInNO1[[4]],color="red",add=TRUE,lwd=3)
```



```{r}
ggplot(no1Table) + geom_tile(aes(name,partnerName,fill=weightRelative)) + theme(axis.text.x = element_text(angle = 90)) + xlab("Post-synaptic neuron")+ylab("Pre-synaptic neuron")+labs(fill="Input % in NO1")

ggplot(no2Table) + geom_tile(aes(name,partnerName,fill=weightRelative)) + theme(axis.text.x = element_text(angle = 90)) + xlab("Post-synaptic neuron")+ylab("Pre-synaptic neuron")+labs(fill="Input % in NO2")

ggplot(no3Table) + geom_tile(aes(name,partnerName,fill=weightRelative)) + theme(axis.text.x = element_text(angle = 90)) + xlab("Post-synaptic neuron")+ylab("Pre-synaptic neuron")+labs(fill="Input % in NO3")
```