---
title: "Outputs"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
```

## Building the outputs neuron bag
Building connection table.
```{r}
outputBag <- create_neuronBag("FC[1|2].*|FS.*|^FR.*|ExR[2|3|5|7|8].*|PFL.*|PFR.*|EL.*|EPG.*|PEG.*|PFG.*",verbose=TRUE)
```

### Renaming
```{r}
outputBag <- cxRetyping(outputBag)
```
Consider only "right side" neurons
```{r}
reducedBag <- filter(outputBag,filterPartners = FALSE,(grepl("_L.*",type) & !startsWith(type,"ExR")) | type == "ExR8_R" | type == "ExR7_R" | type == "ExR5_R" | type == "ExR2_R" | type == "ExR3_R")
```

## What do their respective innervation patterns look like ?
```{r}
roiH <- getRoiTree()
roisOut <- selectRoiSet(roiH,exceptions=list("LAL(R)"=4,"CRE(R)"=4))
roisOut <- roisOut %>% filter(!(level2 %in% c("ATL(L)","ICL(L)")))
roiOutLabels <- selectRoiSet(roiH,default_level = 0)
```
```{r}
outputsByRoi <- getROISummary(reducedBag,threshold = 20)
```


```{r}
outputsInnervation_L <- haneschPlot(outputsByRoi,roiSelect = roisOut,grouping = "supertype2",roiLabel = roiOutLabels,flip=TRUE,interactive=TRUE,theme = theme_minimal_grid(),showCount = T)
outputsInnervation_L
```

```{r}
save_plot("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/CXoutputsHaneschL.svg",outputsInnervation_L,ncol=2,nrow=2)
```

## Who are those neurons they talk to?
We'll select all their partners in "output" regions

```{r}
allOutsTable <- (reducedBag$outputs %>% filter(roi %in% c("WED(R)","SLP(R)","SIP(R)","SMP(R)","SPS","IPS","CRE(R)","RUB(R)","ROB(R)","BU(R)","LAL(R)","AB(R)","GNG") & !(databaseType.to %in% reducedBag$names$databaseType)))
allOuts <- reducedBag$outputsTableRef %>% filter(type %in% allOutsTable$type.to)
```


```{r}
outputsInOutBag <- create_neuronBag(allOuts,selfRef = TRUE,verbose=TRUE,computeKnownRatio=TRUE,synThresh=0)
```

```{r}
outputsInOutBag <- cxRetyping(outputsInOutBag)
```

Look at those targets at a "global" output region level?
```{r}
outputsOverview <- combineRois(outputsInOutBag,c("VLNP(R)","SNP(R)","VMNP(R)","INP","LX(R)","LX(L)"),"Output regions",singleNeuronThreshold=0.001)
## One cleans up anything not getting significant CX input
signifOutputs <- unique(filter(outputsOverview$inputs,type.from %in% outputBag$names$type)$type.to)
outputsOverview <- filter(outputsOverview,filterPartner=FALSE,type %in% signifOutputs)
```

```{r}
CXtypes <- supertype(read_csv("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/CX-cell-types3") %>% rename(databaseType=n.type))
```

```{r}
outputTypes <- selectSupertypeSet(CXtypes,default_level = 2,exceptions=list("PFL1"=1,"PFL2"=1,"PFL3"=1,"FS1"=1,"FS4"=1,"ExR5"=1,"ExR7"=1,"ExR8"=1),exceptionLevelMatch = 1)
```

```{r}
inputs_toOutputs <- outputsOverview$inputs %>% mutate(customSupertype = outputTypes$type[match(supertype.from1,outputTypes$supertype1)])
inputs_toOutputs <- replace_na(inputs_toOutputs,list("customSupertype" = "Other"))
```

```{r}
inputs_toOutputsMat <- connectivityMatrix(connObj = inputs_toOutputs,slctROIs = "Output regions",allToAll = FALSE,from = "type.from",to="type.to")
```
```{r}
CXtoOutputs <- filter(inputs_toOutputs,customSupertype !="Other") %>% group_by(type.to,databaseType.to) %>% summarize(totalCX = sum(knownWeightRelative)) %>% ungroup() %>% filter(!(databaseType.to %in% CXtypes$databaseType)) %>% arrange(desc(totalCX))
```

```{r}
outputsIDs <- neuprint_get_meta(unique(outputsOverview$inputs_raw$to[(outputsOverview$inputs_raw$type.to %in% CXtoOutputs$type.to)])) %>% filter(statusLabel != "Leaves") %>% mutate(typeF = factor( as.character(outputsOverview$inputs_raw$type.to[match(bodyid,outputsOverview$inputs_raw$to)]),levels=CXtoOutputs$type.to)) %>% arrange(typeF) %>% filter(!grepl("ring.*",name))
```

```{r}
write.csv(outputsIDs,file="~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/outputsList.csv")
```


```{r}
outputs_FromOutputs <- bind_rows(outputsInOutBag$outputs %>% filter(roi=="CX"),outputsOverview$outputs)
```

```{r}
outputs_fromOutputsMat <- connectivityMatrix(outputs_FromOutputs,slctROI=c("CX","Output regions"),allToAll=FALSE,from = "type.from","type.to",ref="outputs")
```

```{r}
#Clustering on the input strengths only of "output" CX neurons 
inputsCl_Out <- hClust_connMat(inputs_toOutputsMat,rowSelect=outputBag$names$type)
inputsCl_All <- hClust_connMat(inputs_toOutputsMat)
inputsCl_Other <- hClust_connMat(inputs_toOutputsMat,rowSelect=rownames(inputs_toOutputsMat)[!(rownames(inputs_toOutputsMat) %in% outputBag$names$type)])
```

```{r}
inputs_toOutputs$type.toF <- factor(inputs_toOutputs$type.to,levels=colnames(inputs_toOutputsMat)[inputsCl_Out$order])
```


```{r}
inputProportions <- ggplot(inputs_toOutputs,aes(x=type.to)) + geom_col(aes(y=weightRelative,fill=customSupertype),alpha=0.8) + scale_fill_manual(values=typesPalette(outputTypes$type),name="Input types",guide=guide_legend(ncol=2)) + theme_classic()  + theme(axis.text.x = element_text(angle = 90)) + labs(y="Relative weight",x="Output type")
inputProportions
```

```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/outputsInputProportions.svg",inputProportions,width=35,height=8)
```


## Find feedback pathways in there.
```{r}

CXRois <- unique(unlist(roiH %>% filter(level1=="CX")))
```
```{r}
feedbackNeurons <- unique((outputsInOutBag$outputs %>% filter((databaseType.to %in% CXtypes$n.type) & (roi %in% CXRois)))$type.from)
feedbackBag <- filter(outputsInOutBag,filterPartners=FALSE,type %in% feedbackNeurons)
```

```{r}
roisFeedback <- selectRoiSet(roiH,exceptions=list("LAL(R)"=4,"CRE(R)"=4,"EB"=4,"FB"=4))
```


```{r}
feedbackRoiSummary <- getROISummary(feedbackBag,filter=FALSE)
```

```{r}
feedbackHanesch <- haneschPlot(feedbackRoiSummary,grouping="supertype2",flip=TRUE,roiSelect=roisOut,roiLabel=roiOutLabels)
feedbackHanesch
```

```{r}
feedbackHaneschUnpacked <- haneschPlot(feedbackRoiSummary,grouping="supertype2",flip=TRUE,roiSelect=roisFeedback,roiLabel=roiOutLabels)
feedbackHaneschUnpacked
```

```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/feedbacksHanesch.svg",feedbackHanesch,width=12,height=7)
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/feedbacksHaneschLayers.svg",feedbackHaneschUnpacked,width=14,height=7)
```

```{r}
feedbackPathwaysG <- makeGraph(feedbackBag$inputs %>% filter(type.from %in% outputBag$names$type),roiSelect = (roisOut %>% filter(level1 != "CX")),roiLabel = roiOutLabels)
```

```{r}
feedbackGraphPlot <- ggraph(feedbackPathwaysG$graph,layout="stress") + 
      geom_edge_fan(aes(width=weightRelative,color=roi),alpha=0.5,color="grey") + 
      geom_edge_loop(aes(direction=10,span=10,width=weightRelative),alpha=0.5) +
      geom_node_point(aes(color=supertype2,shape=as.factor(layers)),size=8,alpha=0.5) +
      scale_color_paletteer_d("Polychrome::palette36") +
      geom_node_text(aes(label=name),size=4) +
      scale_edge_width(name="Relative weight") +
      scale_edge_color_discrete() + theme_void()
feedbackGraphPlot + facet_edges(region~.)
```

```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/feedbacksGraph.svg",feedbackGraphPlot,width=12)
```




```{r}
PFL1Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,inputType="PFL1_L*")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL1Summary.svg",PFL1Summary)
PFL1Summary
```


```{r}
PFL1Outputs <- outputsOutputPlot(outputBag,outputsOutputsByRoi,inputType = "PFL1_L*")
```

```{r}
PFL1Outputs
```


```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL1Outs.svg",PFL1Outputs)
```

```{r}
PFL2Outputs <- outputsOutputPlot(outputBag,outputsOutputsByRoi,"PFL2_L")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL2Outs.svg",PFL2Outputs,height=12)
PFL2Outputs
```
```{r}
PFL2Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,inputType="PFL2_L")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL2Summary.svg",PFL2Summary,height=9)
PFL2Summary
```

```{r}
PFL3Outputs <- outputsOutputPlot(outputBag,outputsOutputsByRoi,"PFL3_L*")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL3Outs.svg",PFL3Outputs,height=15)
PFL3Outputs
```
```{r}
PFL3Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,inputType="PFL3_L*")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/PFL3Summary.svg",PFL3Summary,height=10)
PFL3Summary
```

```{r}
ExR7Outputs <- outputsOutputPlot(outputBag,outputsOutputsByRoi,"ExR7_L")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/ExR7Outs.svg",ExR7Outputs,height=12)
ExR7Outputs
```

```{r}
ExR7Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,inputType="ExR7_L")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/ExR7Summary.svg",ExR7Summary,height=9)
ExR7Summary
```


```{r}
ExR8Outputs <- outputsOutputPlot(outputBag,outputsOutputsByRoi,"ExR8_R")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/ExR8Outs.svg",ExR8Outputs,height=12)
ExR8Outputs
```
```{r}
ExR8Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,inputType="ExR8_R")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/ExR8Summary.svg",ExR8Summary,height=9)
ExR8Summary
```


```{r}
FC1Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,"FC1",inputCol = "supertypeFrom1")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/FC1Summary.svg",FC1Summary,height=10)
FC1Summary
```
```{r}
FC2Summary <- outputsOutputPlotSummary(outputBag,outputsSuperSummary,"FC2",inputCol = "supertypeFrom1")
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/FC2Summary.svg",FC2Summary,height=10)
FC2Summary
```

```{r}
DNOutOut <- outputsInOutBag$outputs %>% filter(startsWith(databaseTypeTo,"DN"))
```

```{r}
unique(DNOutOut$type.to)
```

```{r}

```

### In the LAL
```{r}
LALOutPyramid <- makePyramidGraph(outputBag,ROIs = "LAL(-GA)(R)",polarity = "outputs",plot = TRUE)
LALOutPyramid
```

```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/LALOutPyramid.svg",LALOutPyramid,width=49,height=10)
```

```{r}
CREOutPyramid <- makePyramidGraph(outputBag,ROIs = "CRE(-ROB,-RUB)(R)",polarity = "outputs",plot = TRUE)
CREOutPyramid
```
```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/CREOutPyramid.svg",CREOutPyramid,width=49,height=10)
```

```{r}
ROBOutPyramid <- makePyramidGraph(outputBag,ROIs = "ROB(R)",polarity = "outputs",plot = TRUE)
ROBOutPyramid
```
```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/ROBOutPyramid.svg",ROBOutPyramid,width=18,height=10)
```

```{r}
RUBOutPyramid <- makePyramidGraph(outputBag,ROIs = "RUB(R)",polarity = "outputs",plot = TRUE)
RUBOutPyramid
```
```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/RUBOutPyramid.svg",RUBOutPyramid,width=18,height=10)
```

```{r}
SMPOutPyramid <- makePyramidGraph(outputBag,ROIs = "SMP(R)",polarity = "outputs",plot = TRUE)
SMPOutPyramid
```

```{r}
ggsave("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/SMPOutPyramid.svg",SMPOutPyramid,width=30,height=10)
```


## "Homogeneity" plots
```{r}
lalOutputsF <- PFLInOut$outputs_raw %>% filter(paste0(type.from,type.to) %in% paste0(PFLInOut$outputs$type.from,PFLInOut$outputs$type.to) & roi == "LAL(-GA)(R)" & !(grepl("PFL1|PFL2|PFL3",type.to)))
```


```{r}
PFL_breakdown <- ggplot(lalOutputsF,aes(x=name.from,y=weightRelative,group=to,color=as.factor(to))) + geom_point() + geom_line() + facet_wrap(~databaseTypeFrom+type.to ,drop=TRUE,scales = "free_x") + theme_minimal() + theme(axis.text.x = element_text(angle = 90))+  guides(color="none")+ labs(y="Relative weight in the LAL",x="Input Neuron")
PFL_breakdown
```


