pathDf2graphDf <- function(pathDf){
  #' Convert a type-to-type pathway dataframe to a graph dataframe
  #' @param pathDf Dataframe generated by get_type2typePath()
  #' @return Dataframe specifiying the graph resulting from combining the pathways in pathDF by listing all edges and their weights.
  
  pathColNames = colnames(pathDf)
  fromCols = c("type.from",pathColNames[grep("type_",pathColNames)])
  toCols = c(pathColNames[grep("type_",pathColNames)], "type.to")
  weights = c(pathColNames[grep("weightRelative_N",pathColNames)])
  
  for (i in seq(3)){
    assign( paste0("fromSupertype",i), c(paste0("supertype",i,".from"),pathColNames[grep(paste0("supertype",i,"_N"),pathColNames)]) )
    assign( paste0("toSupertype",i),  c(pathColNames[grep(paste0("supertype",i,"_N"),pathColNames)], paste0("supertype",i,".to")) )
  }
  
  graphDataFrame = data.frame(from = character(),
                              to = character(),
                              relWeight = numeric())
  
  for (step in seq(length(fromCols)) ){
    toNodes = pathDf[[toCols[step]]]
    toST1 = pathDf[[toSupertype1[step]]]
    toST2 = pathDf[[toSupertype2[step]]]
    toST3 = pathDf[[toSupertype3[step]]]
    
    nas = is.na(toNodes)
    toNodes[nas] = pathDf$type.to[nas]
    pathDf$type.to[nas] = NA
    
    toST1[nas] =pathDf$supertype1.to[nas]
    pathDf$supertype1.to[nas] = NA
    
    toST2[nas] = pathDf$supertype2.to[nas]
    pathDf$supertype2.to[nas] = NA
    
    toST3[nas] = pathDf$supertype3.to[nas]
    pathDf$supertype3.to[nas] = NA
    
    tmp = data.frame(from = pathDf[[fromCols[step]]],
                     to = toNodes,
                     relWeight = pathDf[[weights[step]]],
                     supertype1.from = pathDf[[fromSupertype1[step]]],
                     supertype1.to = toST1,
                     supertype2.from = pathDf[[fromSupertype2[step]]],
                     supertype2.to = toST2,
                     supertype3.from = pathDf[[fromSupertype3[step]]],
                     supertype3.to = toST3)
    graphDataFrame = bind_rows(graphDataFrame,unique(drop_na(tmp)))
  }
  
  return(graphDataFrame)
}



'
# Example use case using functions in vizualizeConnectivityTables.R

APN3 = neuprint_search("SAD077_.*")
WLL = neuprint_search("LAL138.*")

myPath = get_type2typePath(APN3, WLL, by.roi = FALSE, n_steps = seq(4))

pathDf = myPath %>% filter(weightRelative_path >= 1e-06)

graphDataFrame = pathDf2graphDf(pathDf)

myGraph = constructConnectivityGraph(graphDataFrame, cutoff, vertexSize, selfFBscale=1, arrowSize=0, edgeNorm)
plot(myGraph,edge.curved=edcurve, layout=layout_with_dh(myGraph), edge.color = customizeGraphEdges(myGraph))
'
