---
title: "PB explorations"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\pathways.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\visualizeConnectivityTables.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\neuprintQueryUtils.R")
options(nat.plotengine = 'rgl')
```

Connect to neuprint
```{r}
neuprint_login()
```

Identify types that arborize within the PB
```{r}
PBNronTypes = neuprint_find_neurons("PB")$bodytype %>% unique()
PBNronTypes <- PBNronTypes[which(!is.na(PBNronTypes))]
```

Split the PB types into inputs, outputs, and inner neurons
```{r}
PBpreNpostRatios <- preNpostRatios(PBNronTypes,"PB")

PBpreNpostRatios <- PBpreNpostRatios[which(PBpreNpostRatios$preRelative > 0.02 | PBpreNpostRatios$postRelative > 0.02),]
PBpreNpostRatios <- PBpreNpostRatios[order(PBpreNpostRatios$prePostDiff),]

PBpreNpostRatios['classification'] = 'inner'
PBpreNpostRatios[which(PBpreNpostRatios$prePostDiff > 0.15),]$classification = 'input'
PBpreNpostRatios[which(PBpreNpostRatios$prePostDiff < -0.1),]$classification = 'output'
PBpreNpostRatios$classification <- factor(PBpreNpostRatios$classification, levels = c('input','inner','output'))

p <- ggplot(data = PBpreNpostRatios, aes()) + 
  geom_hline(yintercept = 0) +
  geom_point(aes(x= reorder(as.factor(type), -prePostRatio),
                 y=prePostDiff,
                 color=classification),
                 size = 3,
                 alpha = 0.2) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_color_manual(values = c('green','blue','red')) +
  xlab('neuron type') + ylab('pre ratio - post ratio')
print(p)
```

Sort the Delta 7s according to their max output column
```{r}
# Get the connection matrix from the Delta 7s to the PEN2s
Delta7_2_PEN2 <- getConnectionTable_forSubset(
  unique(neuprint_search("Delta7.*")$bodyid),
  unique(neuprint_search("PEN\\\\\\\\(PB06\\\\\\\\)_b.*")$bodyid),
  "PB")

# Create a lookup table of bodyids to names for the Delta 7s based off of where they strongly output to the PEN2s
Delta7bodyids = Delta7_2_PEN2$partner %>% unique()
Delta7names= c()

for (d in 1:length(Delta7bodyids)){
  
  # Find the P-EN2 glomeruli that receives the max output from the given D7 and 
  datNow = Delta7_2_PEN2[which(Delta7_2_PEN2$partner == Delta7bodyids[d]),]
  PENnmPrts1 = datNow$name[which.max(datNow$weight)] %>% as.character() %>% strsplit('_')
  Glom1 = PENnmPrts1[[1]][[3]]
  
  datNow <- datNow[which(!grepl(Glom1,datNow$name)),]
  PENnmPrts2 = datNow$name[which.max(datNow$weight)] %>% as.character %>% strsplit('_')
  Glom2 = PENnmPrts2[[1]][[3]]
  
  while (grepl(substring(Glom1,1,1),substring(Glom2,1,1)) &
         ((as.integer(substring(Glom1,2,2)) == as.integer(substring(Glom2,2,2))+1)|
          (as.integer(substring(Glom1,2,2)) == as.integer(substring(Glom2,2,2))-1))) {
    datNow <- datNow[which(!grepl(Glom2,datNow$name)),]
    PENnmPrts2 = datNow$name[which.max(datNow$weight)] %>% as.character %>% strsplit('_')
    Glom2 = PENnmPrts2[[1]][[3]]
          }
  
  D7nmPrts = datNow$partnerName[which.max(datNow$weight)] %>% as.character() %>% strsplit('_')
  
  Delta7names = append(Delta7names,
                       paste(D7nmPrts[[1]][[1]], Glom1, Glom2, D7nmPrts[[1]][[3]], sep = '_'))
}

Delta7Lookup = data.frame(bodyids = Delta7bodyids, name = Delta7names)

```

A function to replace Delta 7 names according to the lookup table in connection matrices
```{r}

Delta7Rename <- function(df,Delta7Lookup){

  dfNames = df$name %>% as.character()
  dfPartnerNames = df$partnerName %>% as.character()
  dfBodyIds = df$bodyid %>% as.numeric()
  dfPartnerBodyIds = df$partner %>% as.numeric()
  for (bid in 1:nrow(Delta7Lookup)){
    dfNames[which(dfBodyIds == Delta7Lookup$bodyids[bid])] <- Delta7Lookup$name[bid] %>% as.character()
    dfPartnerNames[which(dfPartnerBodyIds == Delta7Lookup$bodyids[bid])] <- Delta7Lookup$name[bid] %>% as.character()
  }
  
  D7Gloms = strsplit(as.character(Delta7Lookup$name),"_") %>% lapply(function(x){x[3]}) %>% unlist()
  D7Names = Delta7Lookup$name %>% as.character()
  
  df$name <- factor(dfNames,
                  levels = unique(append(append(
                    sort(
                      D7Names[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      D7Names[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfNames[which(!(dfNames %in% D7Names))])))
  
  df$partnerName <- factor(dfPartnerNames,
                  levels = unique(append(append(
                    sort(
                      D7Names[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      D7Names[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfPartnerNames[which(!(dfPartnerNames %in% D7Names))])))
  
  
  df$nameid <- paste(as.character(df$name), as.character(df$bodyid), sep = "_")
  dfNameIds = df$nameid %>% as.character()
  D7Gloms = strsplit(dfNameIds,"_") %>% lapply(function(x){x[3]}) %>% unlist()
  df$nameid <- factor(dfNameIds,
                  levels = unique(append(append(
                    sort(
                      dfNameIds[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      dfNameIds[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfNameIds[which(!grepl("Delta7",dfNameIds))])))
  
  
  df$partnerid <- paste(as.character(df$partnerName), as.character(df$partner), sep = "_")
  dfPartnerIds = df$partnerid %>% as.character()
  D7Gloms = strsplit(dfPartnerIds,"_") %>% lapply(function(x){x[3]}) %>% unlist()
  df$partnerid <- factor(dfPartnerIds,
                  levels = unique(append(append(
                    sort(
                      dfPartnerIds[which(grepl("L",D7Gloms))],
                      decreasing = TRUE),
                    sort(
                      dfPartnerIds[which(grepl("R",D7Gloms))],
                      decreasing = FALSE)
                    ),
                    dfPartnerIds[which(!grepl("Delta7",dfPartnerIds))])))
  
  return(df)
}
```

```{r}

glomSort <- function(names){
  sortedNames = unique(append(
    sort(
      as.character(names[which(grepl("_L",names))]),
      decreasing = TRUE),
    sort(
      as.character(names[which(grepl("_R",names))]),
      decreasing = FALSE))
  )
  return(sortedNames)
}

```

```{r}
Delta7_2_PEN2 <- Delta7Rename(Delta7_2_PEN2,Delta7Lookup)

D7Gloms = strsplit(as.character(Delta7_2_PEN2$partnerid),"_") %>% lapply(function(x){x[3]}) %>% unlist()
D7Gloms <- strsplit(D7Gloms,"-") %>% lapply(function(x){x[1]}) %>% unlist()
D7Names = Delta7_2_PEN2$partnerid %>% as.character()

Delta7_2_PEN2$nameid <- factor(Delta7_2_PEN2$nameid,
        levels = glomSort(Delta7_2_PEN2$nameid))

plotConnectivityMatrix(Delta7_2_PEN2, synapseCutOff = 2, 0)
```

Look at the E-PG to Delta7 connections
```{r}
# Get the connection matrix from the EPGs to the Delta7s
EPG_2_Delta7 <- getConnectionTable_forSubset(
  unique(neuprint_search("EPG.*")$bodyid),
  unique(neuprint_search("Delta7.*")$bodyid),
  "PB")

EPG_2_Delta7 <- Delta7Rename(EPG_2_Delta7,Delta7Lookup)

EPG_2_Delta7$partnerid <- factor(EPG_2_Delta7$partnerid,
        levels = glomSort(EPG_2_Delta7$partnerid))

plotConnectivityMatrix(EPG_2_Delta7, synapseCutOff = 2, 0)


```

```{r}
allD7ids = EPG_2_Delta7$nameid %>% as.character() %>% unique()
D7Gloms = strsplit(allD7ids,"_") %>% lapply(function(x){x[3]}) %>% unlist()
allD7ids <- append(
  sort(allD7ids[which(grepl("L",D7Gloms))],decreasing = TRUE),
  sort(allD7ids[which(grepl("R",D7Gloms))],decreasing = FALSE))
allEPGids = EPG_2_Delta7$partnerid %>% as.character() %>% unique() %>% glomSort()

justWeights = matrix(0L,nrow=length(allD7ids),ncol=length(allEPGids))

for (i in 1:length(allD7ids)){
  for (j in 1:length(allEPGids)){
    w = EPG_2_Delta7[which(EPG_2_Delta7$nameid == allD7ids[i] & EPG_2_Delta7$partnerid == allEPGids[j]),]$weight
    if (length(w) > 0)
      justWeights[i,j] = w
  }
}

p1 <- ggplot()
for (i in 1:length(allD7ids)){
  wNow = justWeights[i,]
  shift = which.max(wNow)-10
  if (shift == 0)
    wNow
  else
    wNow <- c(tail(wNow, -shift), head(wNow, shift))
  
  pts = c(1:length(wNow))
  
  df = data.frame(pts = pts, wNow = wNow)
  fit <- nls(wNow ~ (C1 * exp(-(pts-mean1)**2/(2 * sigma1**2)) +
    C2 * exp(-(pts-mean2)**2/(2 * sigma2**2))), data=df,
    start=list(C1=20, mean1=15, sigma1=5,
               C2=20, mean2=35, sigma2=5), algorithm="port") 
  dffit <- data.frame(pts)
  dffit$wNow <- predict(fit, newdata=dffit)
  
  if (as.numeric(coef(fit)['C1'])>as.numeric(coef(fit)['C2']))
    shift = coef(fit)['mean1'] %>% as.numeric()-25
  else
    shift = coef(fit)['mean2'] %>% as.numeric()-25

  if (shift == 0)
    wNow
  else
    wNow <- c(tail(wNow, -shift), head(wNow, shift))
  justWeights[i,] <- wNow
  
  p1 <- p1 + geom_line(data = data.frame(x = pts, y = wNow), aes(x=x,y=y))
  
}
p1 <- p1 + geom_line(data = data.frame(x = pts, y = colMeans(justWeights)), aes(x=x,y=y),color="red",size=3)

df = data.frame(pts = pts, wMean = colMeans(justWeights))
fit <- nls(wMean ~ (C1 * cos(-C2*(pts-theta))+C3), data=df,
  start=list(C1=20, C2=0.4, C3=10, theta=35), algorithm="port") 
dffit <- data.frame(pts)
dffit$wMean <- predict(fit, newdata=dffit)
p1 <- p1 + geom_line(data = dffit, aes(x=pts,y=wMean),color="green",size=2)

p1 <- p1 + xlab('EPG input position') + ylab('# of synapses')
print(p1)

library(reshape2)
ggplot(melt(justWeights), aes(Var1,Var2, fill=value)) + geom_raster()

```

```{r}

```

