---
title: "PB hanesch plots"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(ggiraph)
library(neuprintrExtra)
library(cowplot)
library(patchwork)
```

Picking the lowest level ROIs
```{r}
## Basic roi hierarchy
roiH <- getRoiTree()
```

```{r}
## The set of rois to color label in the plot
labelRoisPB <- selectRoiSet(roiH,default_level = 0,exceptions = list("PB"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))
```


```{r}
haneschSaveFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/FirstDraftFigs/HaneschPlots/"
```

```{r}
PBTypes <-c("Delta7","P6-8P9","P1-9","LPsP","SpsP","EPGt","EPG","IbSpsP","PEN_b(PEN2)","PEN_a(PEN1)","PFNv",paste0("PFNp_",c("e","d","c","b","a")),"PFNm_b","PFNm_a","PFNd","PFNa","PEG","PFGs",paste0("PFL",1:3),"PFR_b","PFR_a")
## Create a summary per roi of the types of interest and select only PB glomeruli rois (and reorder them)
PBInts <- getTypesTable(PBTypes)
PBSummaryNonLat <- getROISummary(PBInts,threshold = 0) %>% filter(startsWith(roi,"PB(")) %>% mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),paste0("PB(L",1:9,")"))))

## Order the types
PBSummaryNonLat$type <- factor(PBSummaryNonLat$type,levels=PBTypes)
PBSummaryNonLat$databaseType <- factor(PBSummaryNonLat$databaseType,levels=PBTypes)
## Order the supertypes
PBSummaryNonLat$supertype2 <- factor(PBSummaryNonLat$supertype2,levels=c("Delta7","P","LPsP","SPS-PB","EPGt","EPG","PEN","PFN","PEG","PFGs","PFL","PFR"))
```

```{r}
## ROIs to use in the plot
PBRoisDetailed <- selectRoiSet(roiH,default_level = 2,exceptions = list("PB"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))
PBRoisDetailedOnly <- filter(PBRoisDetailed,startsWith(as.character(roi),"PB(")) %>% mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),paste0("PB(L",1:9,")"))))
```
```{r}
## Make the Hanesch plot (this one for the multi glomeruli)
haneschPBLoc <- haneschPlot(PBSummaryNonLat %>% filter(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","EPGt")),roiSelect = PBRoisDetailedOnly,flip = F,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_minimal_grid(),regionOutlines = F)
haneschPBLoc
```


```{r}
## Make the interactive plot
interHaneschPBLoc <- girafe(ggobj = haneschPBLoc, width_svg=6,height_svg=6
  )
```

```{r}
## Save the interactive plot
htmlwidgets::saveWidget(interHaneschPBLoc,paste0(haneschSaveFolder,"PB/PBTypesLocal.html"))
```

```{r}
## Save the svg
save_plot(paste0(haneschSaveFolder,"PB/PBTypesLocal.svg"),haneschPBLoc,nrow=1.5,ncol=1.5)
```

Same thing with columnar neurons
```{r}
haneschPBColumn <- haneschPlot(PBSummaryNonLat %>% filter(type %in% PBTypes & !(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","SIFamide","EPGt"))),roiSelect = PBRoisDetailedOnly,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_minimal_grid(),regionOutlines = F)
haneschPBColumn
```

Combine the plots with patchwork

```{r}
haneschPBDetails <- haneschPBLoc / haneschPBColumn + plot_layout(guides="collect",heights=c(1,4))
haneschPBDetails
```
```{r}
save_plot(paste0(haneschSaveFolder,"PB/PBDetails.svg"),haneschPBDetails,nrow=3,ncol=1.5)
save_plot(paste0(haneschSaveFolder,"PB/PBDetails.png"),haneschPBDetails,nrow=3,ncol=1.5)
```