---
title: "Pie charts"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
library(dplyr)
library(plotly)
library(paletteer)
library(neuprintrExtra)
options(nat.plotengine = 'rgl')
```

```{r}
neuprint_login()
```

```{r messages=FALSE, warning=FALSE}
# Get some custom functions
source("connectionPieChart.R")
```

### Construct neuron bag for type of interest
```{r}
myType = "ER3a_b"
myType_bag = neuronBag(myType)

saveDir = "../neuprintR_analysis_plots/ExR/"
dir.create(saveDir)
```

```{r}
roiTree = getRoiTree()
slctROIs = selectRoiSet(roiTree, default_level = 1, 
                        exceptions = list("INP"=2, "LX(R)"=3, "LX(L)"=3,"CX"=2, "VLNP(R)"=2,"VLNP(L)"=2), exceptionLevelMatch = 1)
#unique(roiTree[["level2"]])
slctROIs = unique(slctROIs$roi)

rpal = paletteer_d("Polychrome::palette36")[1:length(slctROIs)]
#paletteer_c("grDevices::Set 3",n=length(slctROIs))
#roisPalette(favoriteRegion="CX",my_palette=paletteer_d("Polychrome::palette36"))
roiCol = data.frame(roi = slctROIs, col=as.character(rpal))
```

Saving figures to static images is a bit tricky and requires installation of a command line tool (orca). I had to install it through conda and then need to point it too the binaries manually:
```{r}
Sys.setenv("PATH" = paste(Sys.getenv("PATH"), "/Users/haberkernh/anaconda3/bin", sep = .Platform$path.sep))
```

### Generate data for pie chart and plot chart that illustrates input and output fraction per region
```{r,warnings=FALSE}
singleNeuronThreshold=0.005 #
singleNeuronThresholdN=3
mintextsize = 12
# Filter out neurons from left side?
splitLR = TRUE
if(splitLR){
  
  for(side in c("_R","_L")){
    myTypelat = paste0(myType,side)
    for(dir in c("input", "output")){
      myTypeDir = prepData4pieChart(myType_bag,partnerDirection=dir,slctRoi=slctROIs, splitLR,
                                myTypelat,minweight=singleNeuronThresholdN, minrelweight=singleNeuronThreshold)
      
      if(length(myTypeDir$roi)>0){
        pieDat = generatePieChartData(myTypeDir, myTypelat, rootlab = paste(myTypelat,dir))
        
        # Select colors
        labs = pieDat %>% filter(labels %in% slctROIs) %>% arrange(desc(values)) %>% select(labels)
        labsorder = data.frame(roi=as.character(labs$labels), ind = seq(length(as.character(labs$labels))))
        mycols = roiCol %>% filter(roi %in% pieDat$labels)
        mycols =  full_join(mycols,labsorder) %>% arrange(ind)
        print(mycols)
        print(labs$labels)
        
        fig <- plot_ly(data=pieDat, ids = ~ids, labels = ~labels, parents = ~parents, values = ~values, 
                     type = 'sunburst',branchvalues = 'total') %>%
        layout(sunburstcolorway = mycols$col, uniformtext=list(minsize=mintextsize, mode="show"), font.family="sans") #paletteer_d("awtools::a_palette")
        
        print(fig)
        
        orca(fig, file = paste0(saveDir,"pieChart_",myTypelat,"_",dir,".svg"))
      }
    }
  }
  
}else{
  for(dir in c("input", "output")){
    myTypeDir = prepData4pieChart(myType_bag,partnerDirection=dir,slctRoi=slctROIs, splitLR,
                              myType,minweight=singleNeuronThresholdN, minrelweight=singleNeuronThreshold)

    if(length(myTypeDir$roi)>0){
      pieDat = generatePieChartData(myTypeDir, myType, rootlab = paste(myType,dir))
      # Select colors
      labs = pieDat %>% filter(labels %in% slctROIs) %>% arrange(desc(values)) %>% select(labels)
      labsorder = data.frame(roi=as.character(labs$labels), ind = seq(length(as.character(labs$labels))))
      mycols = roiCol %>% filter(roi %in% pieDat$labels)
      mycols =  full_join(mycols,labsorder) %>% arrange(ind)
    
      fig <- plot_ly(data=pieDat, ids = ~ids, labels = ~labels, parents = ~parents, values = ~values, 
                   type = 'sunburst',branchvalues = 'total') %>%
      layout(sunburstcolorway = mycols$col, uniformtext=list(minsize=mintextsize, mode="show"), font.family="sans") #paletteer_d("awtools::a_palette")
      
      orca(fig, file = paste0(saveDir,"pieChart_",myType,"_",dir,".svg"))
    }
  }
  fig
}
```


```{r}

```