---
title: "Contrast connectivity within region with connectivity between neuron types"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
library(dplyr)
options(nat.plotengine = 'rgl')

neuprint_login()
```

```{r, messages=FALSE, warning=FALSE}
# Get some custom functions
source("neuprintQueryUtils.R")
source("visualizeConnectivityTables.R")

# To be able to use ? for accessing doc strings in custom functions, please install the "docstring" package. Alternatively use docstring(function)
library(docstring)
```


### Make selection of neurons to be used in connecitivy analysis
Here we select neurons that are part of what we think is a little "sub network" that can reasonably be looked at in isolation.

```{r}
source = "R6"
sourceIDs = getBodyIdsForList(source)
slctROI = "EB"

splitLR = TRUE

noPost = FALSE
noPre = TRUE
# get post connections
#TODO: Handle this as try/except statement
if(!noPost){
  postConnections <- getConnectionTable(sourceIDs$bodyid,synapseType = "POST",slctROI,  synThresh=10, by.roi = TRUE)
  postTypes = unique(postConnections$type.to)
}

# get pre connections
if(!noPre){
  preConnections <- getConnectionTable(sourceIDs$bodyid,synapseType = "PRE",slctROI, synThresh=10, by.roi = TRUE)
  preTypes = unique(preConnections$type.from)
}
# all the types
if(noPost){
  print(unique(c(preTypes,source)))
  circuit = unique(c(preTypes,source))
}else if(noPre){
  print(unique(c(postTypes,source)))
  circuit = unique(c(postTypes,source))
}else{
  print(unique(c(postTypes, preTypes, source)))
  circuit =  unique(c(postTypes, preTypes,source))
}
```


```{r}
circuitName = paste0(source,"Circuit", slctROI)
if (splitLR){
  circuitName = paste0(circuitName,"_LR")
}
preName = paste0(source," and partners")
postName = paste0(source," and partners")
circuitIDs = getBodyIdsForList(circuit)

#circuit = c(
#  "LNa","PFNa", #NO
#  "PDM14a_b_pct","PDM14a_c_pct", "PDM14r_pct", #LAL
#  "FB2A", "FB2A"#FB
#)
#c(
#  "LCNp","PFNp_a", "FB1H", "OA_VPM3", # NO: neglecting LN1, LN2 and PFNd connectivity with OA-VMP3 
#  "PFL3","PVL04og_pct","ADM10m_pct", "AVM18f_pct", # LAL inputs to LCNp, OA-VPM3
#  "FB1H", "FB1C" #FB: FB1H is output of PFNp_a, FB1C is input
#)
```

### Get connectivity table
```{r, warning=FALSE}
myConnections = getConnectionTable_forSubset(circuitIDs$bodyid,circuitIDs$bodyid, slctROI)
```

```{r}
myConnections_simple = simplifyConnectionTable(myConnections)

typesTable <- getTypesTable(unique(myConnections_simple$databaseType.to))

if (splitLR){
  # Subdevide types and build a custom types table
  myConnections_simple = lrSplit(myConnections_simple, nameCol="name.to",typeCol="type.to")
  myConnections_simple = lrSplit(myConnections_simple, nameCol="name.from",typeCol="type.from")
  typesTable = lrSplit(typesTable, nameCol="name",typeCol="type")
}
```

```{r}
#majorOutputThreshold=0.8
#singleNeuronThreshold=0.01
#singleNeuronThresholdN=3
#pThresh = 0.05

myConnectionsT2T = getTypeToTypeTable(myConnections_simple, typesTable = typesTable)#, majorOutputThreshold,singleNeuronThreshold, singleNeuronThresholdN, pThresh)
```


###  Draw graph
```{r, warning=FALSE}
source("visualizeConnectivityTables.R")
require(igraph)

connectionMeasures = c("weightRelative","weightRelativeTotal", "absoluteWeight")
connectionMeasure = connectionMeasures[1]
cutoff = 0.05 # for weight 0.05, 0.01

showself = FALSE#TRUE

# drop na in "to" column
myConnectionsT2T = myConnectionsT2T %>% drop_na(type.to)
graphData = data.frame(from = myConnectionsT2T$type.from, to = myConnectionsT2T$type.to, relWeight = myConnectionsT2T[[connectionMeasure]])

graphData_noSelf = getNoSelfGraphData(graphData)  
graphData_self = getSelfFBGraphData(graphData)

if (showself){
  graphData = graphData
  graphName = circuitName
} else {
  graphData = left_join(graphData_noSelf, graphData_self)
  graphName = paste(circuitName, "_noSelf")
}

# Graph parameter
largeGraph = FALSE
selfFeedbackScale = 10
edcurve = 0.2# 0.5
if(largeGraph){
  vertexSize = 7#+ 7 * graphData$relWeightSelf * selfFeedbackScale
  plotSize = 15
}else{
  vertexSize = 12 #+ 12 * graphData$relWeightSelf * selfFeedbackScale
  
  plotSize = 10
}

selfFBscale = vertexSize
arrowSize= 0

edgeNorm = 0.03#0.05#0.07#

myGraph = constructConnectivityGraph(graphData, cutoff, vertexSize, selfFBscale, arrowSize, edgeNorm)


# remove isolated nodes
Isolated = which(degree(myGraph) == 0)
myGraph = delete.vertices(myGraph, Isolated)

l = layout_with_fr(myGraph)#layout_with_dh(myGraph)#

myGraph$main = paste0("Connectivity within the ",slctROI) 
plot(myGraph,edge.curved=edcurve, layout=l, edge.color = customizeGraphEdges(myGraph)) # use 0.5 curved if edges overlap

dev.print(pdf, paste0("../neuprintR_analysis_plots/connectivityGraph_",circuitName,'post_',
                      connectionMeasure, cutoff,".pdf"), width=plotSize, height=plotSize)
```


### Connectivity matrix
```{r}
plotW = 55#20 # 20
plotH = 40#17  #15
connectionMeasures = c("weightRelative","ROIweight") #"weightROIRelativeTotal", 

for (connectionMeasure in connectionMeasures){
  
  conMatPlot = plotConnectivityMatrix(myConnections_simple, byGroup = "type", connectionMeasure)
  conMatPlot = addMatrixPlotLabs(conMatPlot, preName,  postName, slctROI, connectionMeasure)
  #conMatPlot = structureMatrixPlotByType(conMatPlot)
  print(conMatPlot)
  ggsave( paste("connectivityMatrix_",circuitName,'_',connectionMeasure,'_byType.pdf', sep=''),
  plot = conMatPlot, device='pdf', path = "../neuprintR_analysis_plots/",
    scale = 1.5, width = plotW*0.8, height = plotH*0.8, units ="cm", dpi = 600, limitsize = TRUE)

  conMatPlot = plotConnectivityMatrix(myConnections_simple, byGroup = "name", connectionMeasure)
  conMatPlot = addMatrixPlotLabs(conMatPlot, preName,  postName, slctROI, connectionMeasure)
  conMatPlot = structureMatrixPlotByType(conMatPlot)
  print(conMatPlot)
  ggsave( paste("connectivityMatrix_",circuitName,'_in_',slctROI,'_',connectionMeasure,'_byName.pdf', sep=''), 
    plot = conMatPlot, device='pdf', path = "../neuprintR_analysis_plots/",
    scale = 1.5, width = plotW*0.8, height = plotH*0.8, units ="cm", dpi = 600, limitsize = TRUE)
  
  conMatPlot = plotConnectivityMatrix(myConnections, byGroup = "id", connectionMeasure)
  conMatPlot = addMatrixPlotLabs(conMatPlot, preName,  postName, slctROI, connectionMeasure)
  conMatPlot = structureMatrixPlotByType(conMatPlot)
  print(conMatPlot)
  #ggsave(paste("connectivityMatrix_",circuitName,'_',connectionMeasure,'_byID.pdf', sep=''), 
  #  plot = conMatPlot, device='pdf', path = "../neuprintR_analysis_plots/",
  #  scale = 2, width = plotW, height =plotH, units ="cm", dpi = 600, limitsize = TRUE)
}
```



```{r}



````