---
title: "Synaptic distances"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(gridExtra)
library(paletteer)
library(igraph)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\pathways.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\R\\supertypeUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\visualizeConnectivityTables.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\neuprintQueryUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\colorCodeLookup.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\FBNetworkVisUtils.R")
options(nat.plotengine = 'rgl')
```

Connect to neuprint
```{r}
neuprint_login()
```

Insert synapse locations into a neuron skeleton
```{r}
insertSyns <- function(nronSkelDat,syns,synID){
  
  # Insert each synapse in the skeleton
  for (s in 1:nrow(syns)){
    
    # Find the closest point in the skeleton
    closestPt <- nronSkelDat %>% filter(PointNo == syns[s,]$treenode_id)
    
    # If the synapse is already located at the closest point, continue
    if ((syns[s,]$x == closestPt$X) & 
        (syns[s,]$y == closestPt$Y) &
        (syns[s,]$z == closestPt$Z)){
      nronSkelDat[which(nronSkelDat$PointNo == closestPt$PointNo),]$synID <- synID
      next
    }
      
    
    # Find the neighbors nodes of the closest point
    nbors <- nronSkelDat %>% filter(Parent == closestPt$PointNo | PointNo == closestPt$Parent) %>%
      mutate(syndist = ((syns[s,]$x-X)^2+(syns[s,]$y-Y)^2+(syns[s,]$z-Z)^2))
    
    # Determine which one is closer to the synapse
    edgePartner <- nbors[which(nbors$syndist == min(nbors$syndist))[1],]
    
    # Insert the synapse inbetween the closest point and its neighbor
    newPtId <- max(nronSkelDat$PointNo) + 1
    if (closestPt$Parent == edgePartner$PointNo){
      nronSkelDat[which(nronSkelDat$PointNo == closestPt$PointNo),]$Parent <- newPtId
      newPt <- data.frame(PointNo = newPtId,
                          Label = 2,
                          X = syns[s,]$x,
                          Y = syns[s,]$y,
                          Z = syns[s,]$z,
                          W = 1/2*(closestPt$W +edgePartner$W),
                          Parent = edgePartner$PointNo,
                          synID = synID)
    } else {
      nronSkelDat[which(nronSkelDat$PointNo == edgePartner$PointNo),]$Parent <- newPtId
      newPt <- data.frame(PointNo = newPtId,
                          Label = 2,
                          X = syns[s,]$x,
                          Y = syns[s,]$y,
                          Z = syns[s,]$z,
                          W = 1/2*(closestPt$W +edgePartner$W),
                          Parent = closestPt$PointNo,
                          synID = synID)
    }
    nronSkelDat <- rbind(nronSkelDat,newPt)
  }
  
  return(nronSkelDat)
}
```

Plot a distribution of distance between two types of synapses from/on a given neuron type
```{r}
synDDist <- function(nronSkel,ROI,type1,prepost1,type2,prepost2){

  # Create a vector to hold the nearest neighbors
  nn_dists <- vector(mode="numeric")
  
  # Step through each neuron of interest
  for (n in 1:length(nrons)){
    print(paste0(n,'/',length(nrons)))
    
    # Pull out the skeleton
    nronSkelDat <- nronSkel[[n]]$d
    nronSkelDat$synID <- 0 # add a variable to label these as nodes rather than as synapses
    
    # Get the synapses in the specific ROI
    syns_inROI <- neuprint_get_synapses(nrons[n],ROI)
    
    # Find the location of the first group of synapses and place them in the skeleton
    syns1 <- nronSkel[[n]]$connectors %>% 
      mutate(type = neuprint_get_meta(partner)$type) %>% 
      filter(type == type1, prepost == prepost1, connector_id %in% syns_inROI$connector_id)
    if (nrow(syns1) == 0)
      next
    nronSkelDat <- insertSyns(nronSkelDat,syns1,1)
    

    # Find the location of the second group of synapses and place them in the skeleton
    syns2 <- nronSkel[[n]]$connectors %>% 
      mutate(type = neuprint_get_meta(partner)$type) %>% 
      filter(type == type2, prepost == prepost2, connector_id %in% syns_inROI$connector_id)
    if (nrow(syns2) == 0)
      next
    nronSkelDat2 <- insertSyns(nronSkelDat,syns2,2)
    
    # Form a graph from the skeleton
    nGraph <- as.ngraph(nronSkelDat2,weights=TRUE)
    
    # Find the nearest neighbor distance between synapses
    synVs1 <- nronSkelDat2[which(nronSkelDat2$synID==1),]$PointNo
    synVs2 <- nronSkelDat2[which(nronSkelDat2$synID==2),]$PointNo
    if (length(synVs2) > 0){
      for (s in 1:length(synVs2)){
        nn_dists <- nn_dists %>% append(min(igraph::distances(nGraph,v=synVs2[s],to=synVs1)))
      }
    }
  }
  
  return(nn_dists)
}
```

Inspect the Kenyon cell's in the right alpha lobe.
```{r}
# Specify the bodyids of the neurons of interest and the ROI to consider
nronsOfInterest <- "KCab-p"
nrons <- getBodyIdsForList(nronsOfInterest) %>% select(bodyid) %>% unlist() %>% as.numeric()
ROI <- "aL(R)"

# Get the neuron data
nronSkel <- neuprint_read_neurons(nrons)

# Specify the first population of synapses to consider
type1 <- "PAM11"
prepost1 <- 1

# Specify the second population of synapses to consider
type2 <- "MBON07"
prepost2 <- 0

nn_dists <- synDDist(nronSkel,ROI,type1,prepost1,type2,prepost2)
nn_dists <- data.frame(dist = nn_dists) 

ggplot(nn_dists) + geom_histogram(aes(dist),binwidth=20) +
  xlim(-100, 2000) +
  ggtitle(paste0("For the ",nronsOfInterest,", the distance between the ",
                 type2,'-',prepost2,' synapses and the ',
                 type1,'-',prepost1,' synapses'))
```