---
title: "CX2CX connections figure"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
library(nat)
library(Cairo)
library(paletteer)
```

```{r message=FALSE}
source("outputFunctions-display.R")
source("outputFunctions-core.R")
source("../R/paperTheme_linux.R")
#source("../R/table2ggraphUtils.R")
outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/figure3-4-CX2CX/"
load("outputsBasics.RData")
```


```{r}
CXOutputTypes <- unique(CXOutputNeurons$type)
CXInfluence <- readRDS("cx-influence.rds")
CXoutFull <- readRDS("pathwayWeightsTable.rds")
CXoutAllSteps <- readRDS("pathways-allsteps.rds")
```


```{r}
CXInfluenceSummary <- group_by(filter(CXInfluence,type.from %in% CXOutputTypes),type.from,kind) %>% summarize(totalOC=sum(Path_weight)) %>% ungroup() %>% mutate(databaseType.from=type.from) %>% supertype()
CXInfluenceSummaryPlot <- ggplot(CXInfluenceSummary,aes(x=type.from,y=totalOC)) + geom_col(aes(fill=kind)) + theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + scale_fill_paletteer_d("ggthemes::Tableau_20",name="Target type") + ylab("normalized pathway weight") + xlab("")
CXInfluenceSummaryPlot
```




```{r}
CXInfluenceFull <- filter(CXInfluence,type.from %in% CXOutputTypes) %>% group_by(type.from) %>% mutate(normalizedWeight=Path_weight/sum(Path_weight)) %>% ungroup() %>% group_by(supertype3.to,type.from,supertype3.from) %>% summarize(Path_weight=sum(Path_weight),normalizedWeight=sum(normalizedWeight)) %>% ungroup()

backCXCompositionFull <- ggplot(CXInfluenceFull,aes(x=type.from,y=Path_weight)) + geom_col(aes(fill=supertype3.to)) + scale_fill_manual(name="Target supertype",values=supertype3Palette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("normalized pathway weight") + xlab("CX output type")
backCXCompositionFull
```
```{r}
localNeuropileNeurons <- c("EL","EPG","PEG","ER6","ExR1","ExR2","ExR3","ExR5","ExR6","PFR_a","PFR_b","FR1","FR2")

CXInfluenceLocal <- filter(CXInfluence,databaseType.from %in% localNeuropileNeurons) %>% group_by(type.from) %>% mutate(normalizedWeight=Path_weight/sum(Path_weight)) %>% ungroup() %>% group_by(supertype3.to,type.from,supertype3.from) %>% summarize(Path_weight=sum(Path_weight),normalizedWeight=sum(normalizedWeight)) %>% ungroup()

backCXCompositionLocal <- ggplot(CXInfluenceLocal,aes(x=type.from,y=Path_weight)) + geom_col(aes(fill=supertype3.to)) + scale_fill_manual(name="Target supertype",values=supertype3Palette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("normalized pathway weight") + xlab("CX output type")
backCXCompositionLocal
```
```{r}
CXInfluenceOther <- filter(CXInfluence,!(databaseType.from %in% localNeuropileNeurons) & type.from %in% CXOutputTypes) %>% group_by(type.from) %>% mutate(normalizedWeight=Path_weight/sum(Path_weight)) %>% ungroup() %>% group_by(supertype3.to,type.from,supertype3.from) %>% summarize(Path_weight=sum(Path_weight),normalizedWeight=sum(normalizedWeight)) %>% ungroup()

backCXCompositionOther <- ggplot(CXInfluenceOther,aes(x=type.from,y=Path_weight)) + geom_col(aes(fill=supertype3.to)) + scale_fill_manual(name="Target supertype",values=supertype3Palette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("normalized pathway weight") + xlab("CX output type")
backCXCompositionOther
```



```{r}
CXInfluenceAD <- filter(CXInfluence,kind=="To dendritic",type.from %in% CXOutputTypes) %>% group_by(type.from) %>% mutate(normalizedWeight=Path_weight/sum(Path_weight)) %>% ungroup() %>% group_by(supertype3.to,type.from,supertype3.from) %>% summarize(Path_weight=sum(Path_weight),normalizedWeight=sum(normalizedWeight)) %>% ungroup()

backCXComposition <- ggplot(CXInfluenceAD,aes(x=type.from,y=Path_weight)) + geom_col(aes(fill=supertype3.to)) + scale_fill_manual(name="Target supertype",values=supertype3Palette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + ggtitle("Connections to dendrites") + ylab("normalized pathway weight") + xlab("CX output type")
backCXCompositionNorm <- ggplot(CXInfluenceAD,aes(x=type.from,y=normalizedWeight)) + geom_col(aes(fill=supertype3.to)) + scale_fill_manual(name="Target supertype",values=supertype3Palette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") + ggtitle("Connections to axons")
backCXComposition
```

The connectivity matrix for axo-dendritic connections:
```{r}
CXOutAxonals <- filter(CXOutsideTypes,downstreamRatio>0.75)

CX2CXFullMat <- filter(CXoutFull,databaseType.to %in% CXOutsideTypes$databaseType) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)

CX2CXFullMat1 <- filter(CXoutAllSteps,n_steps==1 & databaseType.to %in% CXOutsideTypes$databaseType) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)

CX2CXaxDendMat <- filter(CXoutFull,databaseType.to %in% CXOutsideTypes$databaseType & !databaseType.to %in% CXOutAxonals$databaseType & databaseType.from != databaseType.to) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)
CX2CXaxDendMat1 <- filter(CXoutAllSteps,n_steps==1 & databaseType.to %in% CXOutsideTypes$databaseType & !databaseType.to %in% CXOutAxonals$databaseType & databaseType.from != databaseType.to) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)
CX2CXaxDendPlot <- plotConnectivity(CX2CXaxDendMat,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",orderIn = typesCXOrder,orderOut=typesCXOrder,cmax=0.7,theme=theme_paper_grid())+ xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight")) +theme(legend.position=c(0.1,0.2),strip.text.x=element_blank(),strip.text.y=element_blank()) + scale_fill_paletteer_c("ggthemes::Blue")
CX2CXaxDendPlot1 <- plotConnectivity(CX2CXaxDendMat1,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",orderIn = typesCXOrder,orderOut=typesCXOrder,theme=theme_paper_grid()) + xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight"))+ scale_fill_paletteer_c("ggthemes::Blue")

CX2CXFullPlot1 <- plotConnectivity(CX2CXFullMat1,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",orderIn = typesCXOrder,orderOut=typesCXOrder,theme=theme_paper_grid()) + xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight"))+ scale_fill_paletteer_c("ggthemes::Blue")+ theme(legend.position = c(0.1,0.2),strip.text.x = element_text(angle=90))

CX2CXFullPlot <- plotConnectivity(CX2CXFullMat,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",orderIn = typesCXOrder,orderOut=typesCXOrder,theme=theme_paper_grid()) + xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight"))+ scale_fill_paletteer_c("ggthemes::Blue") + theme(legend.position = c(0.1,0.2),strip.text.x = element_text(angle=90))
CX2CXaxDendPlot
CX2CXFullPlot

CX2CXFullPLotRedux <- plotConnectivity(filter(CX2CXFullMat,supertype2.from != "FBt" & supertype2.to != "FBt" & !(databaseType.from %in% localNeuropileNeurons)),grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",orderIn = typesCXOrder,orderOut=typesCXOrder,theme=theme_paper_grid()) + xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight"))+ scale_fill_paletteer_c("ggthemes::Blue") + theme(strip.text.x = element_text(angle=90))
CX2CXFullPLotRedux
```
## The synapses labeled by their target influence
```{r}
CXInfluenceFullSummary <- group_by(CXInfluence,type.from) %>% summarize(totalOC=sum(Path_weight)) %>% ungroup() 
CXInfluenceFullSummary$totalOC[CXInfluenceFullSummary$type.from %in% CXNeurons$type] <- 1
```


```{r}
CXOutSyn <- readRDS("CX-outsideSynapses.rds")
allTargets <- neuprint_get_meta(CXOutSyn$partner) %>% mutate(databaseType=type) %>% customRetyping() %>% supertype() %>% selectSupertypeSet(default_level = 1) %>%  customOutputSupertype(postfix="raw")

CXOutSyn <- mutate(CXOutSyn,
                   partnerType=allTargets$type[match(partner,allTargets$bodyid)],
                   totalOC=CXInfluenceFullSummary$totalOC[match(partnerType,CXInfluenceFullSummary$type.from)]) %>% na.omit() %>%
  mutate(colLevs = cut(totalOC,breaks=seq(0,1,length.out=100),labels=1:99))
            

cPal <- paletteer_c("viridis::plasma",n=100)
names(cPal) <- 1:99

displayAnatomies(synapses=CXOutSyn,
                 ROIs=c("EB","FB","PB","NO","LAL(R)","BU(R)","CRE(R)","SMP(R)","WED(R)","SLP(R)","SIP(R)","SPS(R)","IPS(R)"),
                 saveName = "allOuts-CX2CXLab-pale",
                 synapsePalette = cPal,
                 synapseCluster = "colLevs"
                 )

```

```{r}
allInflViews <- ggdraw(xlim = c(0,2)) + 
   draw_image(paste0(outputsFolder,"allOuts-CX2CXLab-front.png"),scale=1.6,clip="on") + 
   draw_image(paste0(outputsFolder,"allOuts-CX2CXLab-side.png"),scale=1.6,hjust=-0.9,clip="on") + theme_paper_map()
allInflViews
```
```{r}
legendSource <- cowplot::get_legend(ggplot(data.frame(x=1,y=1,c=0.5),aes(x=1,y=1)) + geom_point(aes(color=c)) + theme_paper_map() + scale_color_paletteer_c("viridis::plasma",limits=c(0,1),name="CX to CX fraction"))
```


```{r}
CXInfluenceAA <- filter(CXInfluence,kind=="To axonal",type.from %in% CXOutputTypes) %>% group_by(type.from) %>% mutate(totalWeight=sum(Path_weight),normalizedWeight=Path_weight/totalWeight) %>% ungroup()
backCXCompositionAA <- ggplot(filter(CXInfluenceAA,Path_weight>0.005),aes(x=type.from,y=Path_weight)) + geom_col(aes(fill=supertype2.to)) + theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") +scale_fill_CX_supertype("Target supertype")+ ggtitle("Axo-axonal connections")+ ylab("normalized pathway weight") + xlab("CX output type")
backCXCompositionAANorm <- ggplot(CXInfluenceAA,aes(x=type.from,y=normalizedWeight)) + geom_col(aes(fill=supertype2.to)) + theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~supertype3.from,scales = "free",space="free") +scale_fill_CX_supertype("Target supertype")+ ggtitle("Connections to axons")
backCXCompositionAA
#backCXCompositionAANorm
```

The connectivity matrix for axo-axonal connections:
```{r}
CX2CXaxAxMat <- filter(CXoutFull,databaseType.to %in% CXOutAxonals$databaseType) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)
CX2CXaxAxMat1 <- filter(CXoutAllSteps,n_steps==1 & databaseType.to %in% CXOutAxonals$databaseType) %>% mutate(roi="outside") %>% supertype() %>% filter(Path_weight>0.005)
CX2CXaxAxPlot <- plotConnectivity(CX2CXaxAxMat,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight",cmax=0.7,theme=theme_paper_grid())+ xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight")) + theme(strip.text.x=element_blank(),strip.text.y=element_blank())+ scale_fill_paletteer_c("ggthemes::Blue")
CX2CXaxAxPlot1 <- plotConnectivity(CX2CXaxAxMat1,grouping = "type",facetInputs="supertype3.from",facetOutputs = "supertype3.to",xaxis = "outputs",connectionMeasure = "Path_weight")+ xlab("target type") + ylab("CX output type")+guides(fill=guide_colorbar(title="Pathway weight"))+ scale_fill_paletteer_c("ggthemes::Blue")
CX2CXaxAxPlot
```

```{r}
save_plot(paste0(outputsFolder,"outputs-CXInfluenceSummary.svg"),CXInfluenceSummaryPlot,ncol=1.3,nrow=6,base_width = 8.5,base_height = 11/25)
save_plot(paste0(outputsFolder,"outputs-CXInfluenceCompositionLocal.svg"),backCXCompositionLocal,ncol=0.5,nrow=6,base_width = 8.5,base_height = 11/35)
save_plot(paste0(outputsFolder,"outputs-CXInfluenceCompositionOther.svg"),backCXCompositionOther,ncol=1,nrow=6,base_width = 8.5,base_height = 11/35)
save_plot(paste0(outputsFolder,"outputs-CX2CXFullMat.svg"),CX2CXFullPlot,ncol=1.3,nrow=19,base_width = 8.5,base_height = 11/35)

save_plot(paste0(outputsFolder,"outputs-CX2CXReduxMat.svg"),CX2CXFullPLotRedux,base_width = 6.5,base_height = 4)

layout <- c(
  area(t=2,b=4,l=2,r=10),
  area(t=5,b=7,l=2,r=10),
  area(t=8,b=18,l=2,r=9),
  area(t=8,b=18,l=9,r=10),
  area(t=19,b=35,l=2,r=10)
)

figure3 <- CXInfluenceSummaryPlot + backCXCompositionFull + allInflViews + legendSource + CX2CXFullPlot + plot_layout(design=layout) +plot_annotation(tag_levels = "A",title="Outputs figure 3 -- CX to CX interactions",theme=theme(title=element_text(size=12,face="bold")))& theme(plot.tag.position = c(-0.03, 1.05))

figure3 <- CXInfluenceSummaryPlot + backCXCompositionFull + plot_spacer() + legendSource + CX2CXFullPlot + plot_layout(design=layout) +plot_annotation(tag_levels = "A",title="Outputs figure 3 -- CX to CX interactions",theme=theme(title=element_text(size=12*1.111111,face="bold",family="arial")))& theme(plot.tag.position = c(-0.03, 1.05))
```


```{r}

#figure3 <- CXInfluenceSummaryPlot / backCXComposition / CX2CXaxDendPlot / (backCXCompositionAA + CX2CXaxAxPlot) + plot_layout(heights=c(1,1,3,1.5)) + plot_annotation(tag_levels="A")
#igure3
```
```{r}
#save_plot(paste0(outputsFolder,"outputs-Figure3.pdf"),figure3,ncol=1,nrow=4,base_width = 8.5,base_height = 11/4,device=cairo_pdf)
save_plot(paste0(outputsFolder,"outputs-Figure3.svg"),figure3,base_width = 8.5*1.333333,base_height = 11*1.333333)
```

## SI2 A large fraction of those are one step connections
```{r}
#save_plot(paste0(outputsFolder,"outputs-CX2CXFullMat.svg"),CX2CXFullPlot,ncol=1.3,nrow=19,base_width = 8.5,base_height = 11/35)

compAllTo1 <- (CX2CXFullPlot + ggtitle("All steps")) / (CX2CXFullPlot1 + ggtitle("1 step")) + plot_annotation(title="Outputs figure 3 SI2: comparison of pathway connections to 1 step connections",theme=theme(title=element_text(size=12*1.111111,face="bold",family="arial")))
```
```{r}
save_plot(paste0(outputsFolder,"outputs-Figure3-SI2.svg"),compAllTo1,base_width = 8.5*1.333333,base_height = 11*1.333333)
```

## SI3 Connections to dendritic vs connections to axonal compartments
```{r}
figure3SI3 <-backCXComposition / CX2CXaxDendPlot / (backCXCompositionAA + CX2CXaxAxPlot) + plot_layout(heights=c(1,3,1.5)) + plot_annotation(tag_levels="A",title="Outputs figure 3 - SI3. CX2CX connections per process reached",theme=theme(title=element_text(size=12,face="bold")))
```

```{r}
save_plot(paste0(outputsFolder,"outputs-Figure3-SI3.pdf"),figure3SI3,ncol=1,nrow=4,base_width = 8.5,base_height = 11/4,device=cairo_pdf)
save_plot(paste0(outputsFolder,"outputs-Figure3-SI3.svg"),figure3SI3,ncol=1,nrow=4,base_width = 8.5,base_height = 11/4)
```
