---
title: "Paths to MBONs and PPLs figure"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
library(nat)
library(Cairo)
library(paletteer)
library(tidygraph)
library(ggraph)
library(igraph)
```

```{r message=FALSE}
source("outputFunctions-display.R")
source("outputFunctions-core.R")
source("../R/paperTheme_linux.R")
source("../R/neuronMeshes.R")
#source("../R/table2ggraphUtils.R")
outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/figure7-MBONsPPLs//"
```

```{r}
CX_outGraphRed <- readRDS("output_graph_reduced.rds")
CX_outGraph <- readRDS("output_graph.rds")
CX_outGraphBi <- readRDS("output_graph_FullBilateral.rds")
load("mainTargetsAndConns.Rdata")
load("outputsBasics.RData")
knownTypesTable <- readRDS("known-table.rds")
CXoutFull <- readRDS("pathwayWeightsTable.rds")
```

```{r}
customGraphPalette <- supertype3Palette[names(supertype3Palette) %in% filter(mainFFConns, Path_weight>0.005)$supertype3.to]
extraPal <- p36[!p36 %in% customSupertypePalette & !p36 %in% customGraphPalette]
extraLevs <- unique(mainFFConns$supertype2.to[mainFFConns$supertype3.to=="Terra incognita"])
extraPal <- extraPal[1:length(extraLevs)]
names(extraPal) <- extraLevs
customGraphPalette <- c(customGraphPalette,extraPal)
names(customGraphPalette)[2] <- "Source"
```

## What are all MBONs and PPLs in the (reduced) network?

```{r}

CXoutFFEndpointMBONPPLs <- filter(CXoutFull,(supertype3.to == "MBON" | supertype1.to=="PPL" | supertype3.to == "Antennal lobe") & fullCXwr>0.0005) %>% mutate(supertype.to=knownTypesTable$supertype[match(type.to,knownTypesTable$type)],
                                                                                                                         supertype.from=CXOutputNeurons$supertype[match(databaseType.from,CXOutputNeurons$databaseType)],
                                                                                                                         customSupertype = case_when(supertype.from=="PFL" ~ databaseType.from,
                                                                                                                                                     supertype.from=="PFR" ~ databaseType.from,
                                                                                                                                                     grepl("ExR[7-8]",supertype.from) ~ as.character(supertype.from),
                                                                                                                                                     grepl("FB[8-9]",supertype.from) ~ "FB8-9",
                                                                                                                                                     supertype.from %in% c("FR1","FR2","FS1","FS2","FC1") ~ as.character(supertype.from),
                                                                                                                                                     TRUE ~ "Other")
                                                                                                                         )


moreMBONPPLPlot <- ggplot(CXoutFFEndpointMBONPPLs,aes(x=type.to,y=Path_weight)) + geom_col(aes(fill=customSupertype))+ scale_fill_manual(name="Source type",values=c(customSupertypePalette,"Other"="grey90"))+theme_paper() +  theme(axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5)) + ylab("Total pathway weight") + xlab("") + facet_grid(.~supertype3.to,scale="free_x",space="free_x",switch = "x") + theme(strip.text.x = element_text(angle=60),strip.background = element_rect(fill="grey90"))

moreMBONPPLPlot
```

## All paths 
```{r}

graphToMBONs<- getLocalSubgraph(c("PFR_b_L*","FS1A_L","FS1B_L","ExR7_R","FS2_L","FR1_L","FR2_L","FB8F_a_R"),c("mALD1_L","PPL102_L","PPL103_R","PPL104_R","PPL105_R","PPL107_R","MBON13_R","MBON20_R","MBON23_R","MBON27_R","MBON30_R"),CX_outGraphBi,order=1)%>% selectSupertypeSet(default_level = 1)  %>%
    customOutputSupertype(extraTypes = filter(knownTypesTable,supertype != "CX")$type) %>% 
    mutate(
           layer=case_when(supertype2 == "FBt"~1,
                           supertype2 %in% c("ExR","PFR","FS","FR","FBt","PFL") ~ 5,
                           supertype2 %in% c("LAL","CRE","SMP") ~ 4,
                           supertype3 == "MBON" ~ 2,
                           supertype3 == "DAN" ~ 3,
                           TRUE~3)) %E>% 
    mutate(customSupertype.from = .N()$customSupertype[match(type.from,.N()$type)],weight=weightRelative) %>% filter(weightRelative > 0.005)

set.seed(20)
graphToMBONsPlot <- ggraph(graphToMBONs,layout="dh") + geom_edge_fan(aes(color=customSupertype.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,
                   arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=customSupertype),size=4)+geom_node_text(aes(label=type))+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,customSupertypePalette))+ scale_edge_color_manual(values=c(customGraphPalette,customSupertypePalette)) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") + guides(edge_color="none") + coord_cartesian(clip = "off")+ theme(legend.position=c(0.9,0.5))

graphToMBONsPlot
```
## Anatomy plots

### FB8 loop
```{r}
mb23 <- getTypesTable("MBON23") %>% cxRetyping()

displayAnatomies(list("FB Tangential"=filter(CXNeurons,type=="FB8F_a_R")$bodyid,
                   "DAN"=filter(mainFFTargetsNeurons,type=="PPL105_R")$bodyid,
                   "MBON"=filter(mb23,type=="MBON23_R")$bodyid),ROIs = c("FB","SMP(R)"),saveName = "FB8PPL105",neuronPalette = supertype3Palette)
```

```{r}
FB8PPLAnat <- ggdraw(xlim = c(0.2,1)) + 
   draw_image(paste0(outputsFolder,"FB8PPL105-side.png"),scale=1.6) + theme_paper_map()
```


### FR2 to PPL107
```{r}
displayAnatomies(list("FR2"=filter(CXNeurons,type=="FR2_L")$bodyid,
                       "DAN"=filter(mainFFTargetsNeurons,type=="PPL107_R")$bodyid,
                   "CRE"=filter(mainFFTargetsNeurons,type=="CRE054_R")$bodyid
                   ),ROIs = c("FB","CRE(R)"),saveName = "FR2PPL107",neuronPalette = c(customSupertypePalette,customGraphPalette))
```

```{r}
FR2PPLAnat <- ggdraw(xlim = c(0.2,1)) + 
   draw_image(paste0(outputsFolder,"FR2PPL107-front.png"),scale=1.6) + 
    theme_paper_map()
```

## FS2 - PPL104

```{r}
displayAnatomies(list("FB Output"=filter(CXNeurons,type=="FS2_L")$bodyid,
                   "DAN"=filter(mainFFTargetsNeurons,type=="PPL104_R")$bodyid),ROIs = c("FB","SMP(R)"),saveName = "FS2PPL104",neuronPalette = supertype3Palette)
```

```{r}
FS2PPLAnat <- ggdraw(xlim = c(0,2)) + 
   draw_image(paste0(outputsFolder,"FS2PPL104-front.png"),scale=1.6,clip="on") + 
   draw_image(paste0(outputsFolder,"FS2PPL104-side.png"),scale=1.6,hjust=-1,clip="on") + theme_paper_map()
```

### PFR_b MBON20/mALD1

```{r}
displayAnatomies(list("FB Columnar"=filter(CXNeurons,type=="PFR_b_L*")$bodyid,
                   "LAL"=filter(mainFFTargetsNeurons,type=="LAL002_R")$bodyid),ROIs = c("FB","PB","CRE(R)"),saveName = "PFR-LAL002",neuronPalette = c(supertype3Palette,customGraphPalette))
```

```{r}
displayAnatomies(list("LAL"=filter(mainFFTargetsNeurons,type=="LAL002_R")$bodyid,
                   "Antennal lobe"=filter(mainFFTargetsNeurons,type=="mALD1_L")$bodyid,
                   "MBON"=filter(mainFFTargetsNeurons,type=="MBON20_R")$bodyid),ROIs = c("FB","PB","CRE(R)"),saveName = "LAL002-MBONAL",neuronPalette = c(supertype3Palette,customGraphPalette))

```

```{r}
PFRStep1 <- ggdraw(xlim = c(0.2,1)) + 
   draw_image(paste0(outputsFolder,"PFR-LAL002-side.png"),scale=1.6) + 
    theme_paper_map()
#PFRStep1
```

```{r}
PFRStep2 <- ggdraw(xlim = c(0.2,1)) + 
   draw_image(paste0(outputsFolder,"LAL002-MBONAL-side.png"),scale=1.6) + theme_paper_map()
#PFRStep2
```

### FR1 to MBON30

```{r}
displayAnatomies(neurons=list("FR1"=filter(CXNeurons,type=="FR1_L")$bodyid,
                   "MBON"=filter(mainFFTargetsNeurons,type=="MBON30_R")$bodyid,
                   "DAN"=filter(mainFFTargetsNeurons,type=="PPL102_L")$bodyid
                   ),ROIs = c("FB","CRE(R)"),saveName = "FR1MB30",neuronPalette = c(customSupertypePalette,customGraphPalette))
```

```{r}
FR1MB30Anat <- ggdraw(xlim = c(0.2,1)) + 
   draw_image(paste0(outputsFolder,"FR1MB30-side.png"),scale=1.6) + theme_paper_map()
```

## figure 7

```{r}
layout <- c(
    area(t=3,b=5,l=2,r=5),
    area(t=8,b=15,l=2,r=10),
   area(t=2,b=6,l=7,r=10),
   area(t=17,b=22,l=2,r=5),
   area(t=17,b=22,l=7,r=10)
)

#MBPPLPlot <- moreMBONPPLPlot + graphToMBONsPlot + FR1MB30Anat + FR2PPLAnat + FB8PPLAnat +  plot_layout(design=layout) + plot_annotation(title="Outputs figure 7: paths to MBONs and DANs",tag_levels = "A",theme=theme(title=element_text(size=12,face="bold"))) &theme(plot.tag.position = c(-0.05, 1.05))

MBPPLPlot <- moreMBONPPLPlot + graphToMBONsPlot + plot_spacer() + plot_spacer() + plot_spacer() +  plot_layout(design=layout) + plot_annotation(title="Outputs figure 7: paths to MBONs and DANs",tag_levels = "A",theme=theme(title=element_text(size=12*1.111111,face="bold",family="arial"))) &theme(plot.tag.position = c(-0.05, 1.05))
```

```{r}
#save_plot(paste0(outputsFolder,"outputs-Figure7-MBONPPLs.pdf"),MBPPLPlot,nrow=3,ncol=3,base_height = 11/3,base_width = 8.5/3,device=cairo_pdf)
save_plot(paste0(outputsFolder,"outputs-Figure7-MBONPPLs.svg"),MBPPLPlot,base_height = 11*1.333333,base_width = 8.5*1.333333)
```

## SI

```{r}
PFR2mALDMBON20_1 <- getLocalSubgraph(c("PFR_b_L*","ExR7_R","ExR7_L"),c("mALD1_L","MBON20_R"),CX_outGraphBi,order=1) %>% selectSupertypeSet(default_level = 1) %>%#%N>%
    customOutputSupertype(extraTypes = filter(knownTypesTable,supertype != "CX")$type)  %E>% 
    mutate(customSupertype.from = .N()$customSupertype[match(type.from,.N()$type)]) 
PFR2mALDMBON20Plot <- standardGraph(PFR2mALDMBON20_1,pal=c(customGraphPalette,customSupertypePalette)) + coord_cartesian(clip="off") + scale_y_continuous(trans="reverse")
PFR2mALDMBON20Plot
```
```{r}
#figure7SI1 <- PFR2mALDMBON20Plot / PFRStep1 / PFRStep2 + plot_annotation(tag_levels = "A",title="Outputs figure 7 SI1: PFR_b to MBON 20 and mALD1",theme=theme(title=element_text(size=12,face="bold")))
```

```{r}
#save_plot(paste0(outputsFolder,"outputs-Figure7-SI1.pdf"),figure7SI1,nrow=3,ncol=3,base_height = 11/3,base_width = 8.5/3,device=cairo_pdf)
```


### Paths to oviIN and MBON27 + FS2 to PPL104?
```{r}
FCFStoOviMBON27<- getLocalSubgraph(c("FC2B_L","FS1A_L","FS1A_R","FS1B_L","FS1B_R"),c("oviIN_R","MBON27_R"),CX_outGraphRed,order=1) %>% selectSupertypeSet(default_level = 1) %>%#%N>%
    customOutputSupertype(extraTypes = filter(knownTypesTable,supertype != "CX")$type)  %E>% 
    mutate(customSupertype.from = .N()$customSupertype[match(type.from,.N()$type)]) 
FCFStoOviPlot <- standardGraph(FCFStoOviMBON27,layout="sugiyama",pal=c(customGraphPalette,customSupertypePalette))+ coord_cartesian(clip="off") 
FCFStoOviPlot
```

```{r}
displayAnatomies(list(
    "FS1"= CXNeurons$bodyid[match( c("FS1A_L","FS1A_R","FS1B_L"),CXNeurons$type)],
    "FC2"=CXNeurons$bodyid[match( c("FC2B_L"),CXNeurons$type)],
    "Fru"=filter(mainFFTargetsNeurons,type=="oviIN_R")$bodyid,
    "MBON"=filter(mainFFTargetsNeurons,type=="MBON27_R")$bodyid
),ROIs = c("FB","CRE(R)"),saveName = "FCFSOvi",neuronPalette = c(customSupertypePalette,customGraphPalette))
```

```{r}
FCFSOviAnat <- ggdraw(xlim = c(0,2)) + 
   draw_image(paste0(outputsFolder,"FCFSOvi-front.png"),scale=1.6,clip="on") + 
   draw_image(paste0(outputsFolder,"FCFSOvi-side.png"),scale=1.6,hjust=-1,clip="on") + theme_paper_map()
```

```{r}
FCFSKnownOutputsFig <- (FCFStoOviPlot ) / plot_spacer() + plot_annotation(title="Outputs figure 7 SI1 : FC FS to oviIn and MBON27",tag_levels = "A",theme=theme(title=element_text(size=12*1.111111,face="bold",family="arial"))) + plot_layout(heights = c(1,3))
```

```{r}
save_plot(paste0(outputsFolder,"outputs-Figure7-SI1.svg"),FCFSKnownOutputsFig,base_height = 11*1.333333,base_width = 8.5*1.333333)
```

