---
title: "PFL3 figure"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
library(nat)
library(Cairo)
library(paletteer)
library(tidygraph)
library(ggraph)
library(igraph)
```

```{r message=FALSE}
source("outputFunctions-display.R")
source("outputFunctions-core.R")
source("../R/paperTheme.R")
source("../R/neuronMeshes.R")
#source("../R/table2ggraphUtils.R")
outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/figure10-PFL3//"
```

```{r}
load("outputsBasics.RData")
load("mainTargetsAndConns.Rdata")
```


```{r}
PFLBag <- neuronBag(filter(CXNeurons,type %in% c("PFL3_L*","PFL1_L*","PFL2_R","PFL2_L")),selfRef = T,slctROI=outsideRegions,omitInputs = T,renaming = cxRetyping) %>% combineRois(outsideRegions,"Outside")
PFL3Glom <- plotGlomMat(PFLBag,"PFL3_L*",grouping="gl")
```
```{r}
save_plot(paste0(outputsFolder,"outputs-Figure10-PFL3.svg"),PFL3Glom,base_height = 11/5,base_width = 8.5*1.333333)
```
