---
title: "Outputs figure 1: CX neurons innervation outside the CX"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
library(nat)
library(Cairo)
library(paletteer)
```

```{r message=FALSE}
source("outputFunctions-display.R")
source("../R/paperTheme_linux.R")
#source("../R/table2ggraphUtils.R")
outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/figure1-CXOutputs/"
load("outputsBasics.RData")
```


## What do their respective innervation patterns look like ?
### As a Hanesch plot
```{r}
roiH <- getRoiTree()
roisOut <- selectRoiSet(roiH,exceptions=list("LAL(R)"=4,"CRE(R)"=4))
roisOut <- roisOut %>% filter((!(level2 %in% c("ATL(L)","ICL(L)"))) & (!level1 %in% "CX")) 
roiOutLabels <- selectRoiSet(roiH,default_level = 0)
rPal <- roisPalette(rois = roiOutLabels)
```

```{r}
CXOutputSummary <- getROISummary(CXOutputNeurons,threshold=20) %>% filter(downstream>20)
```

```{r}
outputsInnervation_R <- haneschPlot(CXOutputSummary,roiSelect = roisOut,grouping = "supertype3",roiLabel = roiOutLabels,flip=T,interactive=TRUE,theme = theme_paper_grid(),showCount = T)
outputsInnervation_R
save_plot(paste0(outputsFolder,"outputs-Hanesch.svg"),outputsInnervation_R,ncol=1.3,nrow=7,base_width = 8.5,base_height = 11/15)
```
```{r}
CXOutSyn <- readRDS("CX-outsideSynapses.rds")
displayAnatomies(synapses=CXOutSyn,
                 ROIs=c("EB","FB","PB","NO","LAL(R)","BU(R)","CRE(R)","SMP(R)","WED(R)","SLP(R)","SIP(R)","SPS(R)","IPS(R)"),
                 saveName = "allOuts",
                 synapsePalette = customSupertypePalette,
                 synapseCluster = "customSupertype",
                 size = c(3000,3000))
```

```{r}
allOutViews <- ggdraw(xlim = c(0,2)) + 
   draw_image(paste0(outputsFolder,"allOuts-front.png"),scale=1.6,clip="on") + 
   draw_image(paste0(outputsFolder,"allOuts-side.png"),scale=1.6,hjust=-0.9,clip="on") + theme_paper_map()
allOutViews
```


### Total weight relative contributed by individual types

Get the bag for just the first stage
```{r}
firstStep <- readRDS("output_paths.rds")[[1]]
```

Taking a look at the first stage.
```{r}
firstStageSummary <- firstStep %>% supertype() %>% 
   group_by(type.from,supertype3.from) %>% 
   summarize(totalWeight=sum(weightRelative),totalWeightRaw=sum(absoluteWeight),totalDown=sum(totalPreROIweight*n_from),meanDown=sum(totalPreROIweight)) %>% 
   filter(totalWeightRaw>20)
firstStageSummary$supertype.from <- CXOutputNeurons$customSupertype[match(firstStageSummary$type.from,CXOutputNeurons$type)]
```

```{r}
countsSummary <- ggplot(firstStageSummary,aes(x=type.from,y=totalWeightRaw,color=supertype.from)) + geom_point() + 
   scale_color_manual(name="Synapses from",values=customSupertypePalette) + theme_paper_grid() + 
   facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("# downstream synapses") + xlab("CX type") + theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5)) + scale_y_log10()
totalCountsSummary <- ggplot(firstStageSummary,aes(x=type.from,y=totalDown,color=supertype.from)) + geom_point() + 
   scale_color_manual(name="Synapses from",values=customSupertypePalette) + theme_paper_grid() + 
   facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("# downstream synapses") + xlab("CX type") + theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5)) + scale_y_log10()
meanCountsSummary <- ggplot(firstStageSummary,aes(x=type.from,y=meanDown,color=supertype.from)) + geom_point() + 
   scale_color_manual(name="Synapses from",values=customSupertypePalette) + theme_paper_grid() + 
   facet_grid(.~supertype3.from,scales = "free",space="free") + ylab("mean # downstream synapses") + xlab("CX type") + theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5)) + scale_y_log10()
meanCountsSummary + totalCountsSummary + countsSummary

save_plot(paste0(outputsFolder,"outputs-Counts.svg"),countsSummary,ncol=1.3,nrow=3,base_width = 8.5,base_height = 11/15)
```


### Figure 1: synapses of CX neurons outside the CX
```{r}
#layout <- c(
#   area(t=2,b=4,l=2,r=9),
#   area(t=6,b=12,l=2,r=9),
#   area(t=14,b=15,l=2,r=9)
#)

#outputFig1 <- (outputsInnervation_R + theme(strip.text.x=element_text(angle=90)))+
#   allOutViews + 
#   countsSummary + plot_layout(design = layout)+plot_annotation(tag_levels = "A",title = "Figure 1 - Outputs: CX neurons downstream synapses outside the CX",theme=theme(title=element_text(size=12,face="bold"))) & theme(plot.tag.position = c(-0.05, 1.1))
#save_plot(paste0(outputsFolder,"outputs-Figure1.pdf"),outputFig1,ncol=1,nrow=4,base_width = 8.5,base_height = 11/4,device=cairo_pdf)
```
