---
title: "PFL to NO"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(patchwork)
library(neuprintrExtra)
library(nat)
library(Cairo)
library(paletteer)
library(tidygraph)
library(ggraph)
library(igraph)
```

```{r message=FALSE}
source("outputFunctions-display.R")
source("outputFunctions-core.R")
source("../R/paperTheme_linux.R")
source("../R/neuronMeshes.R")
#source("../R/table2ggraphUtils.R")
outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NewOutputs/figure3-4-CX2CX/"
```

```{r}
CX_outGraphRed <- readRDS("output_graph_reduced.rds")
CX_outGraph <- readRDS("output_graph.rds")
CX_outGraphBi <- readRDS("output_graph_FullBilateral.rds")
load("mainTargetsAndConns.Rdata")
load("outputsBasics.RData")
knownTypesTable <- readRDS("known-table.rds")
CXoutFull <- readRDS("pathwayWeightsTable.rds")
```

```{r}
customGraphPalette <- supertype3Palette[names(supertype3Palette) %in% filter(mainFFConns, Path_weight>0.005)$supertype3.to]
extraPal <- p36[!p36 %in% customSupertypePalette & !p36 %in% customGraphPalette]
extraLevs <- unique(mainFFConns$supertype2.to[mainFFConns$supertype3.to=="Terra incognita"])
extraPal <- extraPal[1:length(extraLevs)]
names(extraPal) <- extraLevs
customGraphPalette <- c(customGraphPalette,extraPal)
names(customGraphPalette)[1] <- "Source"
```

```{r}
PFL2toLNO <- getLocalSubgraph(c("PFL2_L","PFL2_R"),c("LNO3_R"),CX_outGraph,order=1)

PFL2toLNOGraph <- ggraph(PFL2toLNO,layout="sugiyama") + geom_edge_fan(aes(color=supertype2.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=supertype2),size=4)+geom_node_text(aes(label=type),nudge_y = 0.05)+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],supertype3Palette),name="Type")+ scale_edge_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],"LC"=supertype3Palette[["Visual PNs"]])) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") +  guides(edge_color="none",color="none") + theme(legend.position=c(0.8,0.8)) + coord_cartesian(clip="off")

PFL3toLCNOGraph
PFL1toERGraph
PFL2toLNOGraph
```

```{r}
PFL3_toEB <- as_tbl_graph(induced_subgraph(CX_outGraph,c(
                                               "PFL3_L*",
                                               "LAL121_R",
                                               "LAL076_R",
                                               "CRE041_R",
                                               "LCNOp_R",
                                               "ER6_L",
                                               "ExR6_L",
                                               "ExR4_L"))) %N>% mutate(x=case_when(
                                                  type %in% c("PFL3_L*","LCNOp_R") ~ 1,
                                                  type %in% c("LAL121_R","LAL076_R") ~ 1.25,
                                                  type %in% c("CRE041_R") ~ 0.8,
                                                  type == "ER6_L" ~ 1.3,
                                                  type == "ExR6_L" ~ 1.4,
                                                  type == "ExR4_L" ~ 1.5
                                                  ),
                                                  y=case_when(
                                                     type %in% c("PFL3_L*") ~ 3,
                                                     type %in% c("CRE041_R") ~ 2.3,
                                                     type %in% c("LAL076_R") ~ 2.5,
                                                     type %in% c("LAL121_R") ~ 2.0,
                                                     type %in% c("LCNOp_R","ER6_L","ExR4_L") ~ 1.5,
                                                     type == "ExR6_L" ~ 1.6)
                                                  ) %>% selectSupertypeSet(default_level = 1) %>%
   customOutputSupertype()  %E>% mutate(customSupertype.from = .N()$customSupertype[match(type.from,.N()$type)])



PFL3toEBPlot <- ggraph(PFL3_toEB,layout="manual",x=x,y=y) + geom_vline(xintercept = 1.25,lty=2,color="grey50")+ geom_edge_fan(aes(color=customSupertype.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,
                   arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=customSupertype),size=4)+geom_node_text(aes(label=type))+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,customSupertypePalette))+ scale_edge_color_manual(values=c(customGraphPalette,customSupertypePalette)) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") + guides(color="none",edge_color="none") + coord_cartesian(clip="off")

#PFL2DN23Plot <- baseGraph(PFL_toDN2_3bi,minW=0.001,layout="manual",x=x,y=y)
PFL3toEBPlot 
```

```{r}
PFL1_toEB <- as_tbl_graph(induced_subgraph(CX_outGraph,c(
                                               "PFL1_L*",
                                               "LAL047_R",
                                               "LAL188_R",
                                               "WED034_R",
                                               "WED035_R",
                                               "LAL138_R",
                                               "ER1_b_L",
                                               "ER1_a_R")))%N>% mutate(x=case_when(
                                                  type %in% c("PFL1_L*","LAL047_R","WED034_R") ~ 1,
                                                  type %in% c("WED035_R","ER1_a_R") ~ 0.75,
                                                  type %in% c("LAL188_R") ~ 1.2,
                                                  type == "LAL138_R" ~ 1.25,
                                                  type == "ER1_b_L" ~ 1.4
                                                  ),
                                                  y=case_when(
                                                     type %in% c("PFL1_L*") ~ 3,
                                                     type %in% c("LAL047_R") ~ 2.8,
                                                     type %in% c("LAL188_R","WED035_R","WED034_R","LAL188_R") ~ 2.5,
                                                     type %in% c("LAL138_R") ~ 2.2,
                                                     type %in% c("ER1_a_R","ER1_b_L") ~ 1.8)
                                                  ) %>% selectSupertypeSet(default_level = 1) %>%
   customOutputSupertype()  %E>% mutate(customSupertype.from = .N()$customSupertype[match(type.from,.N()$type)])



PFL1toEBPlot <- ggraph(PFL1_toEB,layout="manual",x=x,y=y) + geom_vline(xintercept = 1.25,lty=2,color="grey50")+ geom_edge_fan(aes(color=customSupertype.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,
                   arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=customSupertype),size=4)+geom_node_text(aes(label=type))+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,customSupertypePalette))+ scale_edge_color_manual(values=c(customGraphPalette,customSupertypePalette)) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") + guides(color="none",edge_color="none") + coord_cartesian(clip="off")

#PFL2DN23Plot <- baseGraph(PFL_toDN2_3bi,minW=0.001,layout="manual",x=x,y=y)
PFL1toEBPlot 
```


```{r}
displayAnatomies(list("FB Columnar"=filter(CXNeurons,type=="PFL3_L*")$bodyid,
                   "CRE"=filter(mainFFTargetsNeurons,type=="CRE041_R")$bodyid,
                   "LAL"=filter(CXNeurons,type=="LCNOp_R")$bodyid
                   ),ROIs = c("FB","PB","LAL(R)","NO"),saveName = "PFL3toLCNO",neuronPalette = c(customGraphPalette,supertype3Palette))
```


```{r}
displayAnatomies(list("FB Columnar"=filter(CXNeurons,type=="PFL2_L")$bodyid,
                   "CRE"=filter(mainFFTargetsNeurons,type=="LAL052_R")$bodyid,
                   "LAL"=filter(CXNeurons,type=="LNO3_R")$bodyid
                   ),ROIs = c("FB","PB","LAL(R)","NO"),saveName = "PFL2toLNO3",neuronPalette = c(customGraphPalette,supertype3Palette))
```

```{r}
save_plot(paste0(outputsFolder,"PFL3toEBNO.svg"),PFL3toEBPlot,base_height = 2,base_width = 5)
save_plot(paste0(outputsFolder,"PFL1toEB.svg"),PFL1toEBPlot,base_height = 2,base_width = 5)
save_plot(paste0(outputsFolder,"PFL2toLNO3Graph.svg"),PFL2toLNOGraph,nrow=1,ncol=1,base_height = 11/5,base_width = 8.5/3)
```




```{r}
ExR8toLCNO2 <- getLocalSubgraph(c("ExR8_R"),c("GLNO_R","LNO3_R","LNO2_R"),CX_outGraph,order=1)
ExR8toLCNO4 <- getLocalSubgraph(c("ExR8_R"),c("GLNO_R","LNO3_R","LNO2_R"),CX_outGraph,order=2)
ExR8Graph2 <- ggraph(ExR8toLCNO2,layout="sugiyama") + geom_edge_fan(aes(color=supertype2.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=supertype2),size=4)+geom_node_text(aes(label=type),size = 6*mm2pt,nudge_y = 0.05)+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],supertype3Palette),name="Type")+ scale_edge_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],supertype3Palette)) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") +  guides(edge_color="none",color="none") + theme(legend.position=c(0.8,0.8)) + coord_cartesian(clip="off")

ExR8Graph4 <- ggraph(ExR8toLCNO4,layout="stress") + geom_edge_fan(aes(color=supertype2.from,width=weightRelative),end_cap = circle(3, "mm"),linejoin = "mitre",linemitre=3,arrow =arrow(length = unit(1, 'mm'),type = "closed")) + geom_node_point(aes(color=supertype2),size=4)+geom_node_text(aes(label=type),size = 6*mm2pt,nudge_y = 0.05)+theme_paper_map()+scale_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],supertype3Palette),name="Type")+ scale_edge_color_manual(values=c(customGraphPalette,"PFL"=supertype3Palette[["FB Columnar"]],supertype3Palette)) + scale_edge_width(range=c(0.2,3),limits=c(0.001,NA),name="Relative weight") +  guides(edge_color="none",color="none") + theme(legend.position=c(0.8,0.8)) + coord_cartesian(clip="off")

save_plot(paste0(outputsFolder,"ExR8toLNO2StepsGraph.svg"),ExR8Graph2,nrow=1,ncol=1,base_height = 11/5,base_width = 8.5/3)
save_plot(paste0(outputsFolder,"ExR8toLNO4StepsGraph.svg"),ExR8Graph4,nrow=2,ncol=2,base_height = 11/5,base_width = 8.5/3)

ExR8Graph4
```


