---
title: "FB Analysis - Intra FB FBts"
output: html_notebook
---

```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(neuprintrExtra)
library(reshape2)
library(patchwork)
source("C:\\Users\\dantu\\Documents\\neuprintR-notebooks\\R\\visualizeConnectivityTables.R")
source("C:\\Users\\dantu\\Documents\\neuprintR-notebooks\\FBNetworkVisUtils.R")
```

Get the neuron bags
```{r}
FBtIntraTypes <- c("FB4Z","FB5R","FB5S","FB6J","FB6L","FB7D","FB7J")
FBtBag <- neuronBag(getTypesTable(FBtIntraTypes))
```

Plot the inputs
```{r}
FBt_in_plts <- list()
for (t in 1:length(FBtIntraTypes)){
  FBtIns <- FBtBag$inputs_raw %>% filter(roi=="FB" & type.to == FBtIntraTypes[t])
  FBtIns$nameOrder.from <- FBRename(FBtIns$name.from,FBtIns$from)
  FBtIns$nameOrder.to <- FBRename(FBtIns$name.to,FBtIns$to)
  
  FBt_ins <- plotConnectivityMatrix(FBtIns, byGroup = "id_sort",cmax=0.05)
  FBt_ins <- structureMatrixPlotByType(FBt_ins)
  FBt_ins <- FBt_ins + xlab("postsynaptic neuron") + ylab("presynaptic neuron")
  FBt_in_plts[[t]] <- FBt_ins
}

allFBt_in_plts <- FBt_in_plts[[1]]+FBt_in_plts[[2]]+FBt_in_plts[[3]]+FBt_in_plts[[4]]+FBt_in_plts[[5]]+FBt_in_plts[[6]]+FBt_in_plts[[7]] + 
  plot_layout(nrow=1, guides='collect')
ggsave("C:\\Users\\dantu\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_TanConnectivity\\IntraFB_FBt_ins.pdf",
       allFBt_in_plts,
       width=8,height=10.5,units="in")
```

Plot the outputs
```{r}
FBt_out_plts <- list()
for (t in 1:length(FBtIntraTypes)){
  FBtOuts <- FBtBag$outputs_raw %>% filter(roi=="FB" & type.from == FBtIntraTypes[t])
  FBtOuts$nameOrder.from <- FBRename(FBtOuts$name.from,FBtOuts$from)
  FBtOuts$nameOrder.to <- FBRename(FBtOuts$name.to,FBtOuts$to)
  
  FBt_outs <- plotConnectivityMatrix(FBtOuts, byGroup = "id_sort",cmax=0.04)
  FBt_outs <- structureMatrixPlotByType(FBt_outs)
  FBt_outs <- FBt_outs + xlab("postsynaptic neuron") + ylab("presynaptic neuron")
  FBt_out_plts[[t]] <- FBt_outs
}

allFBt_out_plts <- FBt_out_plts[[1]]+FBt_out_plts[[2]]+FBt_out_plts[[3]]+FBt_out_plts[[4]]+FBt_out_plts[[5]]+FBt_out_plts[[6]]+FBt_out_plts[[7]] + 
  plot_layout(ncol=1, guides='collect')
ggsave("C:\\Users\\dantu\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_TanConnectivity\\IntraFB_FBt_outs.pdf",
       allFBt_out_plts,
       width=8,height=10.5,units="in")
```