---
title: "Input pathways summary (figure 5)"
output: html_notebook
---

## Prepare the environment
```{r}
#library(neuprintr)
#library(tidyverse)
#library(cowplot)
#library(patchwork)
#library(neuprintrExtra)
#library(nat)
#library(Cairo)
#library(paletteer)
#library(ggraph)
#ibrary(tidygraph)
```
Loading local functions:
```{r message=FALSE}
source(file.path("..","Outputs","outputFunctions-display.R"))
#source("../outputsFig/outputFunctions-core.R")
source(file.path("..","R","paperTheme.R"))
#source("../R/neuronMeshes.R")
#source("../R/table2ggraphUtils.R")
#outputsFolder <- "~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/Inputs/"

```
This is a folder where the figures will be saved if needed:
```{r}
outputsFolder <- "figure5-CXInputs"
if (!dir.exists(outputsFolder)) dir.create(outputsFolder)
```
Where the data has been saved (by "Inputs-Core.Rmd"):
```{r}
dataFolder="data"
```

```{r}
load(file.path(dataFolder,"inputsBasics.RData"))
#allNodes <-  readRDS(file.path(dataFolder,"all-nodes_Inputs.rds"))
endpointsInfluence <- readRDS(file.path(dataFolder,"endpoints-influence_Inputs.rds"))
mainEndpointInfluencers <- readRDS(file.path(dataFolder,"main-endpoints_Inputs.rds"))
load(file.path(dataFolder,"mainSourcesAndConns.Rdata"))
#CX_inGraph <- readRDS("input_graph.rds")
#knownTypesTable <- readRDS("known-table.rds")
#allKnownTypes <- unique(knownTypesTable$type) 
```


```{r}

#CX2CXExclusivePathways <- readRDS("cx2cx-pathways.rds")
#CXinFull <- readRDS("pathwayWeightsTable_Inputs.rds")
```

```{r}
endpointsPalette <- c("Unknown"="grey80",
                       "CX"=p36[2],
                        "5HT"=p36[14],
                        "OA"=p36[16],
                        "Peptidergic"=p36[28],
                        "DAN"=p36[29],
                       "MBON"=p36[4],
                       "LH"=p36[31],
                       "DN"=p36[24],
                       "Fru"=p36[30],
                       "KC"=p36[13],
                       "Antennal lobe"=p36[20],
                       "Clock"=p36[6],
                       "Visual PNs"=p36[32],
                       "Other Sensory"=p36[3])

endpointsLevels <- c(  "Unknown",
                       "CX",
                        "5HT",
                        "OA",
                        "Peptidergic",
                        "DAN",
                       "MBON",
                       "LH",
                       "DN",
                       "Fru",
                       "KC",
                       "Antennal lobe",
                       "Clock",
                       "Visual PNs",
                       "Other Sensory")
```

```{r}
endpointsInfluenceSummary <- group_by(filter(endpointsInfluence,type.to %in% mainFFConns$mainContributee),
                                      type.to,supertype3.to,supertype.from) %>% 
  summarize(Path_weight=sum(Path_weight)) %>% 
   mutate(supertype.from=factor(supertype.from,levels=endpointsLevels)) %>% 
  ungroup()

unknownInfluence <- group_by(endpointsInfluenceSummary,type.to,supertype3.to) %>%
  summarize(supertype.from="Unknown",Path_weight=1-sum(Path_weight)) %>% 
  ungroup()

endpointsInfluenceSummary <- rbind(endpointsInfluenceSummary,unknownInfluence)

endpointsInfluenceSummaryMainFF <- filter(endpointsInfluenceSummary,supertype.from != "CX" & 
                                            type.to %in% mainFFConns$mainContributee)

#FBtSummary <- filter(endpointsInfluenceSummaryMainFF,supertype3.to=="FB Tangential") %>% mutate(layer.to=gsub("FB","",str_extract(type.to,"FB[1-9]")))

#endpointsCompositionMainFB <- ggplot(FBtSummary,aes(x=type.to,y=Path_weight)) + geom_col(aes(fill=supertype.from)) + scale_fill_manual(name="Source supertype",values=endpointsPalette)+ theme_paper()+ theme(strip.text.x=element_blank(),axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+facet_grid(.~layer.to,scales = "free",space="free") + ylab("pathway weight") + xlab("CX input type")

endpointsCompositionMainFFOthers <- ggplot(filter(endpointsInfluenceSummaryMainFF,
                                                  !(supertype3.to %in% c("FB Tangential","SA",
                                                                         "FB Output",
                                                                         "FB Columnar"))),
                                                  aes(x=type.to,y=Path_weight)) + geom_col(aes(fill=supertype.from)) +
  scale_fill_manual(name="Source supertype",values=endpointsPalette)+
  theme_paper(strip.text.x=element_blank(),
              axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5))+ 
  facet_grid(.~supertype3.to,scales = "free",space="free") + 
  ylab("pathway weight") + xlab("CX input type")

endpointsCompositionMainFFOthers
```

```{r}
#save_plot(paste0(outputsFolder,"inputCompositionFBt.svg"),endpointsCompositionMainFB,base_width=10,base_height=3)
save_plot(file.path(outputsFolder,"inputCompositionOthers.svg"),
          endpointsCompositionMainFFOthers,base_width=7,base_height=3)
```

## Input synapses (figure 5 supplement 1)

### Synapse locations (panel A)
```{r}
CXInSyn <- readRDS(file.path(dataFolder,"CX-outsideSynapses_Inputs.rds"))
```

```{r}
displayAnatomies(synapses=filter(CXInSyn,!(supertype3 %in% c("FB Tangential"))),
                 ROIs=c("EB","FB","PB","NO","LAL(R)","BU(R)",
                        "CRE(R)","SMP(R)","WED(R)","SLP(R)","SIP(R)","SPS(R)","IPS(R)"),
                 saveName = "allIns-noFB",
                 saveFolder = outputsFolder,
                 synapsePalette = supertype3Palette,
                 synapseCluster = "supertype3",
                 size = c(3000,3000))
```

```{r}
legendSource <- cowplot::get_legend(ggplot(CXOutsideInnervation,aes(x=1,y=supertype3)) + geom_point(aes(color=supertype3)) + theme_paper_map() + scale_color_manual(name="supertype",values=supertype3Palette))
```

```{r}
save_plot(file.path(outputsFolder,"legend.svg"),legendSource,base_height = 3,base_width = 1)
```

### Synapse counts in different regions (panel B)
```{r}
roiH <- getRoiTree()
roisOut <- selectRoiSet(roiH,exceptions=list("LAL(R)"=4,"CRE(R)"=4))
roisOut <- roisOut %>% filter((!(level2 %in% c("ATL(L)","ICL(L)"))) & (!level1 %in% "CX") & side2 != "Left") 

CXOutsideInnervation <- getROISummary(CXOutsideNeurons,threshold=0) %>% 
  filter(roi %in% roisOut$roi) %>%
  mutate(region = case_when(
    supertype3 %in% c("ER","ExR","EB Columnar") ~ "EB",
    supertype3 %in% c("FB Tangential","FB Columnar","FB Output") ~ "FB",
    supertype3 == "LNO" ~ "NO",
    supertype3 == "PB Input" ~ "PB",
    supertype3 == "SA" ~ "SA"
  ))
```

```{r}
CXOutsideInnervationSummary <- group_by(CXOutsideInnervation,region,roi) %>% 
  summarize(totalDownstream=sum(downstream),totalUpstream=sum(upstream)) %>% 
  group_by(region) %>%
  mutate(downstreamRatio=totalDownstream/sum(totalDownstream),
         upstreamRatio=totalUpstream/sum(totalUpstream)
         ) %>%
  ungroup() %>%
  mutate(polarityRatio=totalDownstream/(totalUpstream+totalDownstream))
```
```{r}
inputTotals <- ggplot(filter(CXOutsideInnervationSummary,upstreamRatio>0.01),aes(x=roi,y=totalUpstream)) + geom_point() + facet_wrap(.~region,scales="free") + theme_paper_grid() + theme(axis.text.x = element_text(angle=90,hjust = 1,vjust=0.5)) + ylab("total # of input synapses")
inputTotals
```

```{r}
save_plot(file.path(outputsFolder,"inputsAll.svg"),inputTotals,base_width=6,base_height = 4)
```

