---
title: "EB Columnar Figure"
output: html_notebook
---


```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(neuprintrExtra)
library(reshape2)
library(patchwork)
library(ggnewscale)
library(gridExtra)
```

Specify plotting text sizes
```{r}
tickLabSz <- 6
axLabSz <- 8
legSz <- 6
legTitSz <- 8
pltTit <- 8

theme_set(theme(axis.title = element_text(size = axLabSz), 
      axis.text = element_text(size = tickLabSz),
      legend.text = element_text(size = legSz),
      legend.title = element_text(size = legTitSz),
      plot.title = element_text(size = pltTit)))

```

Order the columnar neurons by their location in the EB
```{r}
EBGlomOrder <- function(name,id){
  # Specify the order of glomeruli
  glomOrder <- list(
    EPG = c("R1","R2","R3","R4","R5","R6","R7","R8",
             "L8","L7","L6","L5","L4","L3","L2","L1"),
    # c("R1","L8","R2","L7","R3","L6","R4","L5","R5","L4","R6","L3","R7","L2","R8","L1"),
    PEG = c("R1","R2","R3","R4","R5","R6","R7","R8",
             "L8","L7","L6","L5","L4","L3","L2","L1"),
    # c("R1","L8","R2","L7","R3","L6","R4","L5","R5","L4","R6","L3","R7","L2","R8","L1"),
    EPGt = c("R9","L9"),
    PEN1 = c("R2","R3","R4","R5","R6","R7","R8","R9",
             "L9","L8","L7","L6","L5","L4","L3","L2"),
    #c("R2","L9","R3","L8","R4","L7","R5","L6","R6","L5","R7","L4","R8","L3","R9","L2")
    PEN2 = c("R2","R3","R4","R5","R6","R7","R8","R9",
             "L9","L8","L7","L6","L5","L4","L3","L2"))
    #c("R2","L9","R3","L8","R4","L7","R5","L6","R6","L5","R7","L4","R8","L3","R9","L2")
  
  # Form a unique nameid from the PB type, the PB gloms where it arborizes, and the bodyid
  name  <- gsub("\\s*\\([^\\)]+\\)","",as.character(name))
  name  <- gsub("PEN_a","PEN1",as.character(name))
  name  <- gsub("PEN_b","PEN2",as.character(name))
  nameid <- paste(name, as.character(id), sep='-')
  
  # Extract the unique names and types
  allNames <- nameid %>% unique() %>% sort()
  nameLabels = name %>% unique() %>% sort()
  types = strsplit(allNames,'_') %>% lapply(function(x){x[[1]]}) %>% unique() %>% unlist()
  types = gsub("([\\(\\)])", "\\\\\\1",types)
  
  # Sort the names by the order of the glomeruli in the PB and exchange the bodyid for a number
  newNames = c()
  for (tp in 1:length(types)){
    nmsNow <- allNames[which(grepl(paste0('^',types[tp],"_"),allNames))]
    gloms <- sapply(nmsNow,function(n) strsplit(n,'_')[[1]][2]) %>% unlist() %>% as.character() 
    gloms <- sapply(gloms,function(n) strsplit(n,'-')[[1]][1]) %>% unlist() %>% as.character() 
    glomSort <- sapply(as.character(unlist(glomOrder[types[tp]])),
                       function(g) which(grepl(g,gloms))) %>% unlist() %>% as.numeric()
    glomSort <- append(glomSort, which(!(gloms %in% as.character(unlist(glomOrder[types[tp]])))))
    nmOrder <- nmsNow[glomSort]
    allNames[which(grepl(paste0('^',types[tp],"_"),allNames))] <- nmOrder
    
    nms <- nameLabels[which(grepl(paste0('^',types[tp],"_"),nameLabels))]
    for (n in 1:length(nms)){
      nmsNow <- nmOrder[which(grepl(nms[n],nmOrder))]
      nmsNow <- paste(nms[n],seq(1:length(nmsNow)),sep='-')
      nmOrder[which(grepl(nms[n],nmOrder))] <- nmsNow
    }
    newNames = append(newNames,nmOrder)
  }
  # Create a lookup table between the old and new names
  nmSwap <- data.frame(oldNm = allNames, newNm = newNames)
  
  # Swap in the new names
  nameid <- lapply(nameid, function(x) nmSwap$newNm[match(x, nmSwap$oldNm)]) %>%
    factor(levels = nmSwap$newNm)
  
}
```

Get the connection matrix between the EPGs, EPGts, PEN1s, PEN2s, and PEGs in the EB
```{r}
neurons = c("EPG","EPGt","PEG","PEN_a(PEN1)","PEN_b(PEN2)")

EBColConTab <- getConnectionTable(getTypesTable(neurons)$bodyid,
  "POST",
  "EB")
EBColConTab <- EBColConTab %>% filter(type.to %in% neurons)
EBColConTab$id.from <- EBGlomOrder(EBColConTab$name.from,EBColConTab$from)
EBColConTab$id.to <- EBGlomOrder(EBColConTab$name.to,EBColConTab$to)

plotOrder <- c("EPG","EPGt","PEN1","PEN2","PEG")
fromLevelsOld <- levels(EBColConTab$id.from)
fromLevelsNew <-  c()
toLevelsOld <- levels(EBColConTab$id.to)
toLevelsNew <-  c()
for (p in 1:length(plotOrder)){
  fromLevelsNew <- fromLevelsNew %>%
    append(fromLevelsOld[which(grepl(paste0(plotOrder[p],'_'),fromLevelsOld))])
  toLevelsNew <- toLevelsNew %>%
    append(toLevelsOld[which(grepl(paste0(plotOrder[p],'_'),toLevelsOld))])
}
EBColConTab$id.from <- factor(EBColConTab$id.from,fromLevelsNew)
EBColConTab$id.to <- factor(EBColConTab$id.to,toLevelsNew)

conmatPlot <- ggplot(EBColConTab) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(EBColConTab$weightRelative),
                       limits=c(0,max(EBColConTab$weightRelative))) +
  geom_tile(aes(id.to,id.from,fill=weightRelative)) +
  theme_cowplot() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,size=4,hjust=1),
        axis.text.y = element_text(size=4)) +
  xlab("post-synaptic neuron") + ylab("pre-synaptic neuron")

offset <- 0.5
types <- c("EPG","EPGt","PEN_a(PEN1)","PEN_b(PEN2)","PEG")
for (t in 1:length(types)){
  numNrons <- nrow(EBColConTab %>% filter(type.from == types[t]) %>% select(id.from) %>% unique())
  offset <- offset + numNrons
  conmatPlot <- conmatPlot + geom_hline(yintercept = offset)
}

offset <- 0.5
types <- c("EPG","EPGt","PEN_a(PEN1)","PEN_b(PEN2)","PEG")
for (t in 1:length(types)){
  offset <- offset + nrow(EBColConTab %>% filter(type.to == types[t]) %>% select(id.to) %>% unique())
  conmatPlot <- conmatPlot + geom_vline(xintercept = offset)
}

print(conmatPlot)
```

```{r}
save_plot('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\EB\\columnarToColumnar\\EBColConmat.pdf',conmatPlot)
```

Look at the total number of input synapses by PB glom
```{r}
EBColConTab$glomname.from <- sapply(EBColConTab$id.from %>% as.character(),
                                    function(i) strsplit(i,'-')[[1]][1]) %>%
  unlist() %>% as.character()
EBColConTab$num.from <- sapply(EBColConTab$id.from %>% as.character(),
                                    function(i) strsplit(i,'-')[[1]][2]) %>%
  unlist() %>% as.character()
typesFrom <- c("EPG","PEG","PEN_a(PEN1)","PEN_b(PEN2)")
typesTo <- list()
typesTo[[1]] <- c("PEN_a(PEN1)","PEN_b(PEN2)","PEG")
typesTo[[2]] <- c("PEN_b(PEN2)")
typesTo[[3]] <- c("EPG")
typesTo[[4]] <- c("EPG")

g_synsIn <- list()
for (t in 1:length(typesToConsider)){
  g_synsIn[[t]] <- ggplot(EBColConTab %>% filter(type.from == typesFrom[t] & type.to %in% typesTo[[t]])) +
    geom_bar(stat='identity',aes(x = id.to, y = ROIweight, fill=id.from)) +
    theme_cowplot() + theme(axis.text.x = element_text(angle = 90)) + ggtitle(paste0('from ',typesFrom[t]))
  print(g_synsIn[[t]])
}

```

