---
title: "Hanesch old"
output: html_notebook
---

###OLD
```{r}
ExRTable <- neuprint_search("ExR.*",field="type") %>% mutate(databaseType = type) %>% lateralize_types(postfix = "raw") %>% filter(grepl("_R.*",type))
```

```{r}
ExRNeurons <- neuprint_read_neurons(ExRTable$bodyid,meta = FALSE,connectors = FALSE)
```
```{r}
ExRNeuronsXY <- neuron2polygon(ExRNeurons)
ExRNeuronsXZ <- neuron2polygon(ExRNeurons,axis=c("x","z"))
ExRNeurons <- bind_rows(ExRNeuronsXY[seq(1,by=2,to=nrow(ExRNeuronsXY)),],ExRNeuronsXZ[seq(1,by=2,to=nrow(ExRNeuronsXZ)),]) %>% mutate(type = ExRTable$type[match(bodyid,ExRTable$bodyid)])
```

```{r}
EBShape <- roiOutline("EB",alpha=200)
LALRShape <- roiOutline("LAL(-GA)(R)",alpha=200)
GAShape <- roiOutline("GA(R)")
BUShape <- roiOutline("BU(R)")
outlineRois <- selectRoiSet(roiH,exceptions=list("LAL(R)"=3))
roiShapes <- bind_rows(EBShape,LALRShape,GAShape,BUShape) %>% mutate(l4 = outlineRois$level4[match(roi,outlineRois$roi)],superroi = labelRoisEB$roi[match(l4,labelRoisEB$level4)])
```


```{r}
ExRAnatPlot <- ggplot() + geom_path(data=roiShapes,aes(x=x,y=y,group=roi),color="grey50") + geom_polygon(data=roiShapes,aes(x=x,y=y,group=roi,fill=superroi),alpha=0.3) + scale_fill_manual(values=roiPal) + geom_polygon_interactive(data=ExRNeurons,aes(x=x,y=y,group=bodyid,data_id=type),fill="grey80",alpha=0.2) + facet_grid(proj~.) + theme_void() + coord_fixed()  + scale_y_reverse()
```

```{r}
ExRSummaryPlot <- plot_grid(ExRAnatPlot + theme(legend.position = "none"),haneschExR)
```

```{r}
interExRSummary <- girafe(ggobj = ExRSummaryPlot, width_svg=14,height_svg=7,options = list(
    opts_hover(css= girafe_css(css = "stroke:red;",
                               area = "fill:black;stroke:none;fill-opacity:1;"
                               ))
  ))
```

```{r}
htmlwidgets::saveWidget(interExRSummary,paste0(NIPFolder,"EB/ExRSummary.html"))
```


```{r}
haneschExRFull <- haneschPlot(EBSummary %>% filter(startsWith(type,"ExR")),flip=T,roiSelect = EBRois,roiLabel = labelRoisEB,interactive=TRUE)
```

```{r}
ggsave(paste0(NIPFolder,"EB/ExRRight.svg"),haneschExR,width = 8,height=6)
ggsave(paste0(NIPFolder,"EB/ExRFull.svg"),haneschExRFull,width = 10,height=6)
```

```{r}
interHaneschExR <- girafe(ggobj = haneschExR, width_svg=8,height_svg=6,
  options = list(
    opts_sizing(width=0.7)
  ))
interHaneschExRFull <- girafe(ggobj = haneschExRFull, width_svg=8,height_svg=6,
  options = list(
    opts_sizing(width=0.7)
  ))
```

```{r}
htmlwidgets::saveWidget(interHaneschExR,paste0(NIPFolder,"EB/ExRRight.html"))
htmlwidgets::saveWidget(interHaneschExRFull,paste0(NIPFolder,"EB/ExRFull.html"))
```

How do those compare to the Brad Types
```{r}
load("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/EB/EB_Types.RData")
```

```{r}
EB_Type[!(EB_Type %in% EBTypes$databaseType)]
```
That's fine, EQ5 is not a type anymore (it's called EL now)
```{r}
EBTypes$databaseType[!(EBTypes$databaseType %in% EB_Type)]
```

```{r}
interHaneschExR <- girafe(ggobj = haneschExR, width_svg=6,height_svg=6)
htmlwidgets::saveWidget(interHaneschExR,paste0(NIPFolder,"EB/ExRs.html"))
```


```{r}
#haneschBUR <- haneschPlot(BUSummary %>% filter(type %in% BURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisBU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
#haneschBUR_ttF <- haneschPlot(BUSummary_ttFiltered %>% filter(type %in% BURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisBU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
```

## AOTU

```{r}
AOTUTypesTable <- getTypesInRoiTable("AOTU(R)",verbose=TRUE)

AOTURTypes <- typesInROI(AOTUTypesTable,ROI = "AOTU(R)")

AOTURois <- selectRoiSet(roiH,default_level = 2,exceptions = list("NO"=4,"LAL(R)"=4,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,2,1,1))

labelRoisAOTU <- selectRoiSet(roiH,default_level = 0,exceptions = list("NO"=2,"AL(R)"=1,"AL(L)"=1),exceptionLevelMatch = c(2,1,1))

AOTUSummary <- getROISummary(AOTUTypesTable,threshold=3)
AOTUSummary_ttFiltered <- filterROISummary(AOTUSummary,AOTUTypesTable,AOTURTypes,AOTURois)
```

```{r}
haneschAOTUR <- haneschPlot(AOTUSummary %>% filter(type %in% AOTURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisAOTU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschAOTUR_ttF <- haneschPlot(AOTUSummary_ttFiltered %>% filter(type %in% AOTURTypes$type),grouping="supertype2",flip=T,roiSelect = BURois,roiLabel = labelRoisAOTU,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschAOTUR
haneschAOTUR_ttF
```

```{r}
save_plot(paste0(NIPFolder,"AOTU/AOTU_RTypes.svg"),haneschAOTUR,ncol=8,nrow=1.5,base_width = 8.5/2)
save_plot(paste0(NIPFolder,"AOTU/AOTU_RTypes_filtered.svg"),haneschAOTUR_ttF,ncol=8,nrow=1.5,base_width = 8.5/2)
```

```{r}
#EBSummary <- EBSummary %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
save_plot(paste0(NIPFolder,"EB/EBTypesRightWidth2.svg"),haneschEB_R,nrow=1,ncol=2,base_width = 8.5/2)
save_plot(paste0(NIPFolder,"EB/EBTypesRightWidth25.svg"),haneschEB_R,nrow=2,ncol=2.5,base_width = 8.5/2.5)

save_plot(paste0(NIPFolder,"EB/EBTypesRightWidth25_filtered.svg"),haneschEB_R_ttF,nrow=2,ncol=2.5,base_width = 8.5/2.5)
```

```{r}
PBSummary <- getROISummary(PBTypesTable,threshold=0)
PBSummary_ttFiltered <- filterROISummary(PBSummary,PBTypesTable,PBTypes,PBRois) %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
PBSummary <- PBSummary %>%  mutate(type=stringr::str_replace(type,"Delta","\u0394"))
```

```{r}
haneschPB <- haneschPlot(PBSummary %>% filter(type %in% PBTypes$type & !(databaseType %in% "SIFa")),roiSelect = PBRois,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPB_ttF <- haneschPlot(PBSummary_ttFiltered %>% filter(type %in% PBTypes$type & !(databaseType %in% "SIFa")),roiSelect = PBRois,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPB
haneschPB_ttF
```

```{r}
interHaneschPB <- girafe(ggobj = haneschPB, width_svg=19,height_svg=8
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschPB,paste0(NIPFolder,"PB/PBTypes.html"))
```

```{r}
save_plot(paste0(NIPFolder,"PB/PBTypes.svg"),haneschPB,nrow=1,ncol=2.5,base_width = 8.5/2.5)
save_plot(paste0(NIPFolder,"PB/PBTypes_filtered.svg"),haneschPB_ttF,nrow=1,ncol=2.5,base_width = 8.5/2.5)
```

```{r}
#PBsummary <- PBSummary %>% filter((type %in% PBTypes$type) & 
#                                    ((supertype3 %in% c("PB Interneurons","PB Input")  & grepl("_R",type))  | 
#                                       (supertype3 == "EB Columnar" & !grepl("_R",type)) | (supertype2 %in% c("PFG","PFL","PFR") & !grepl("_R",type)) | 
#                                       (supertype2 == "PFN" & grepl("_R",type))))

#PBsummary$supertype2 <- factor(PBsummary$supertype2,levels=c("Δ7","P","LPsPB","SPS-PB","EPGt","EPG","PEN","PEG","PFG","PFL","PFR","PFN"))
#haneschPBRedux <- haneschPlot(PBsummary %>% filter(type %in% PBTypes$type & !(databaseType %in% "SIFa")),roiSelect = PBRois,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
```

```{r}
haneschPBLoc <- haneschPlot(PBSummary %>% filter(databaseType %in% c("Δ7","P1-9","LPsP","P6-8P9","SpsP")),roiSelect = PBRoisDetailed,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPBLoc_ttF <- haneschPlot(PBSummary_ttFiltered %>% filter(databaseType %in% c("Δ7","P1-9","LPsP","P6-8P9","SpsP")),roiSelect = PBRoisDetailed,flip = T,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschPBLoc
haneschPBLoc_ttF
```

```{r}
save_plot(paste0(NIPFolder,"PB/PBTypesLocal.svg"),haneschPBLoc,nrow=1,ncol=1,base_width = 8.5/2)
save_plot(paste0(NIPFolder,"PB/PBTypesLocal_filtered.svg"),haneschPBLoc_ttF,nrow=1,ncol=1,base_width = 8.5/2)
```

```{r}
PBSummaryNonLat_ttFiltered <- filterROISummary(PBSummaryNonLat,
                                               PBTypesTableNonLat,
                                               PBTypesNonLat,
                                               filter(PBRoisDetailed,startsWith(as.character(roi),"PB(")),
                                               renaming=NULL) %>% 
  mutate(roi = factor(roi,levels = c(paste0("PB(R",9:1,")"),
                                     paste0("PB(L",1:9,")")))) %>% 
  mutate(type=stringr::str_replace(type,"Delta","\u0394"))
#PBSummaryNonLat <- PBSummaryNonLat %>% mutate(type=stringr::str_replace(type,"Delta","\u0394"))
haneschPBLoc2_ttF <- haneschPlot(PBSummaryNonLat_ttFiltered %>% filter(databaseType %in% c("Delta7","P1-9","LPsP","P6-8P9","SpsP","EPGt")),roiSelect = PBRoisDetailedOnly,flip = F,grouping = "supertype2",roiLabel = labelRoisPB,interactive=TRUE,showCount = T,theme=theme_paper_grid(),regionOutlines = F)
```

```{r}
haneschPBDetails <- haneschPBLoc2 / haneschPBColumn + plot_layout(guides="collect",heights=c(1,4))
haneschPBDetails_ttF <- haneschPBLoc2_ttF / haneschPBColumn_ttF + plot_layout(guides="collect",heights=c(1,4))
haneschPBDetails
haneschPBDetails_ttF
```

```{r}
haneschNOR <- haneschPlot(NOSummary %>% filter(type %in% NORTypes$type),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNOR_ttF <- haneschPlot(NOSummary_ttFiltered %>% filter(type %in% NORTypes$type),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschNOR
haneschNOR_ttF
haneschNORF <- haneschPlot(NOSummary %>% filter((type %in% NORTypes$type) & (databaseType %in% CXTypes$databaseType)),grouping="supertype2",flip=T,roiSelect = NORois,roiLabel = labelRoisNO,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
```

```{r}
interHaneschNOR <- girafe(ggobj = haneschNOR, width_svg=15,height_svg=8,
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschNOR,paste0(NIPFolder,"NO/NO_RTypes.html"))
```

How do those compare to the Brad Types

```{r}
load("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/NO/NO_Types.RData")
```

```{r}
NO_Type[!(NO_Type %in% NORTypes$databaseType)]
```
```{r}
NORTypes$databaseType[!(NORTypes$databaseType %in% NO_Type)]
```


```{r}
interHaneschFBColL <- girafe(ggobj = haneschFBColL, width_svg=12,height_svg=8
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBColL,paste0(NIPFolder,"FB/FBColumnarLeft.html"))
```

```{r}
haneschFBColL <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Columnar") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
```

```{r}
haneschFBColL_ttF <- haneschPlot(FBSummary_ttFiltered %>% 
                                   filter((type %in% FBTypes$type) & 
                                            (supertype3 == "FB Columnar") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())

haneschFBColL_ttF
```
```{r}
save_plot(paste0(NIPFolder,"FB/FBColsLeft.svg"),haneschFBColL,nrow=1,ncol=1.5,base_width = 8.5/2)
save_plot(paste0(NIPFolder,"FB/FBColsLeft_filtered.svg"),haneschFBColL_ttF,nrow=1,ncol=1.5,base_width = 8.5/2)
```

```{r}
interHaneschDelta <- girafe(ggobj = haneschDeltas, width_svg=10,height_svg=7)
```

```{r}
htmlwidgets::saveWidget(interHaneschDelta,paste0(NIPFolder,"FB/FBDeltas.html"))
```

```{r}
haneschFBOutLay <- haneschPlot(FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBOutLay_ttF <- haneschPlot(FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output") & !grepl("_R",type)),roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBOutLay
haneschFBOutLay_ttF
```

```{r}
interHaneschFBQL <- girafe(ggobj = haneschFBOutLay, width_svg=12,height_svg=8,
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBQL,paste0(NIPFolder,"FB/FBQsLeft.html"))
```

```{r}
save_plot(paste0(NIPFolder,"FB/FBQsLeft.svg"),haneschFBOutLay,nrow=1,ncol=1.5,base_width=8.5/2)
save_plot(paste0(NIPFolder,"FB/FBQsLeft_filtered.svg"),haneschFBOutLay_ttF,nrow=1,ncol=1.5,base_width=8.5/2)
```





### Full FB schematic?

```{r}
summaryFB <- FBSummary %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output" | supertype3 == "FB Interneuron" | supertype3 == "FB Columnar") & !grepl("_R",type))
summaryFB$supertype2 <- factor(summaryFB$supertype2,levels=c("PFN","vΔ","hΔ","PFG","PFR","PFL","FC","FS","FR"))
summaryFB_ttF <- FBSummary_ttFiltered %>% filter((type %in% FBTypes$type) & (supertype3 == "FB Output" | supertype3 == "FB Interneuron" | supertype3 == "FB Columnar") & !grepl("_R",type))
summaryFB_ttF$supertype2 <- factor(summaryFB_ttF$supertype2,levels=c("PFN","vΔ","hΔ","PFG","PFR","PFL","FC","FS","FR"))
```


```{r}
haneschFBSummary <- haneschPlot(summaryFB,roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBSummary_ttF <- haneschPlot(summaryFB_ttF,roiSelect = FBRois,flip=T,roiLabel = labelRoisFB,grouping="supertype2",interactive=TRUE,showCount = T,theme=theme_paper_grid())
haneschFBSummary
haneschFBSummary_ttF
```

```{r}
save_plot(paste0(NIPFolder,"FB/FBSummary.svg"),haneschFBSummary,nrow=1,ncol=2,base_width=8.5/2)
save_plot(paste0(NIPFolder,"FB/FBSummary_filtered.svg"),haneschFBSummary_ttF,nrow=1,ncol=2,base_width=8.5/2)
```

```{r}
interHaneschFBSummary <- girafe(ggobj = haneschFBSummary, width_svg=13,height_svg=7
  )
```

```{r}
htmlwidgets::saveWidget(interHaneschFBSummary,paste0(NIPFolder,"FB/FBSummary.html"))
```

```{r}
haneschABRF <- haneschPlot(ABSummary %>% filter((type %in% ABTypes$type) & (databaseType %in% c("SA1_a", "SA1_b", "SA1_c", "SA2_a", "SA2_b", "SA3", "SAF"))),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABRF_ttF <- haneschPlot(ABSummary_ttFiltered %>% filter((type %in% ABTypes$type) & (databaseType %in% c("SA1_a", "SA1_b", "SA1_c", "SA2_a", "SA2_b", "SA3", "SAF"))),grouping="supertype2",flip=T,roiSelect = ABRois,roiLabel = labelRoisAB,interactive=TRUE,showCount = TRUE,theme=theme_paper_grid())
haneschABRF
haneschABRF_ttF
```

