---
title: "validationOldPanels"
author: "Romain Franconville"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Example outputs: EPG outputs in glom 4
```{r}
fitValsEPG4 <- filter(PBCompFits,databaseType=="EPG" & side=="outputs" & glomerulus ==4)
PBCompOut <- ggplot(filter(PB3Comp,databaseType=="EPG" & side=="outputs"),aes(x=R4,y=L4)) + geom_point(aes(color=supertype2.to)) + geom_smooth(formula=y~x,method="lm",color="grey70",alpha=0.1) + 
  geom_abline(linetype=2,lwd=0.2) + theme_paper()  + scale_color_CX_supertype(name="Supertype") + xlab("relative output weight in R4") + coord_fixed() +
  ylab("relative output weight in L4") + annotate(geom="text",x=0.25,y=0.05,label=paste0("s= ",format(fitValsEPG4$estimate,digits = 3),"\n r\u00b2= ",format(fitValsEPG4$adj.r.squared,digits=3)))


PBCompOut
```

### PB anatomies

```{r}
PBMesh <- neuprint_ROI_mesh("PB")
R3Mesh <- neuprint_ROI_mesh("PB(R3)")
L3Mesh <- neuprint_ROI_mesh("PB(L3)")
R4Mesh <- neuprint_ROI_mesh("PB(R4)")
L4Mesh <- neuprint_ROI_mesh("PB(L4)")
```

```{r}
R3Example <- unique(filter(PBreBag$inputs_raw,type.to=="PFNa_R3")$to)
L3Example <- unique(filter(PBreBag$inputs_raw,type.to=="PFNa_L3")$to)
R3ExampleAnat <- lapply(R3Example,getNeuronMesh,cloud=TRUE)
L3ExampleAnat <- lapply(L3Example,getNeuronMesh,cloud=TRUE)
R4Example <- unique(filter(PBreBag$outputs_raw,type.from=="EPG_R4")$from)
L4Example <- unique(filter(PBreBag$outputs_raw,type.from=="EPG_L4")$from)
R4ExampleAnat <- lapply(R4Example,getNeuronMesh,cloud=TRUE)
L4ExampleAnat <- lapply(L4Example,getNeuronMesh,cloud=TRUE)
```


```{r}
nopen3d()
par3d(windowRect = c(20, 30, 1500, 1500))
plot3d(PBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
plot3d(R3Mesh,color="#908827",add=TRUE,alpha=0.2)
plot3d(L3Mesh,color="grey30",add=TRUE,alpha=0.2)
shade3d(R3ExampleAnat[[1]],col="SteelBlue")
shade3d(R3ExampleAnat[[2]],col="SkyBlue")
shade3d(L3ExampleAnat[[1]],col="grey80")
shade3d(L3ExampleAnat[[2]],col="grey40")
nview3d("ventral")
rgl.snapshot(paste0(validationFolder,"frontPB3.png"))
```

```{r}
nopen3d()
par3d(windowRect = c(20, 30, 1500, 1500))
plot3d(PBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
plot3d(L4Mesh,color="#908827",add=TRUE,alpha=0.2)
plot3d(R4Mesh,color="grey30",add=TRUE,alpha=0.2)
shade3d(L4ExampleAnat[[1]],col="SteelBlue")
shade3d(L4ExampleAnat[[2]],col="SkyBlue")
shade3d(L4ExampleAnat[[3]],col="royalblue")
shade3d(R4ExampleAnat[[1]],col="grey80")
shade3d(R4ExampleAnat[[2]],col="grey40")
shade3d(R4ExampleAnat[[3]],col="grey60")
nview3d("ventral")
rgl.snapshot(paste0(validationFolder,"frontPB4.png"))
```

```{r}
PBFrame3 <- ggdraw() + draw_image(paste0(validationFolder,"frontPB3.png"),scale=1.4,vjust=0.05,clip="on") + theme_paper_map()  
PBFrame3 <- PBFrame3 + annotate(geom="text",x=0.4,y=0.4,label="R3") + annotate(geom="text",x=0.61,y=0.42,label="L3")
PBFrame3 <- PBFrame3 + annotate(geom="text",x=0.5,y=0.95,label="PFNa inputs in glomeruli 3")
PBFrame3
```

```{r}
PBFrame4 <- ggdraw() + draw_image(paste0(validationFolder,"frontPB4.png"),scale=1.8,clip="on") + theme_paper_map()
PBFrame4 <- PBFrame4 + annotate(geom="text",x=0.48,y=0.54,label="R4") + annotate(geom="text",x=0.65,y=0.55,label="L4")
PBFrame4 <- PBFrame4 + annotate(geom="text",x=0.5,y=0.95,label="EPG outputs in glomeruli 4")
PBFrame4
```

PB panel
```{r}
pbLayout <- c(
  area(t = 1, l = 1, b = 5, r = 5),
  area(t = 1, l = 6, b = 4, r = 10),
  area(t = 6, l = 2, b = 8, r = 4),
  area(t = 5, l = 6, b = 8, r = 10)
)


PBFigAlt <- (PBFrame3 + 
                         (PBSynapseCountDiffAlt + theme(legend.position="none")) + (PBCompIn+guides(color=FALSE)) + 
         (PBSlopesAlt + guides(color=FALSE)))  + plot_layout(design=pbLayout,guides="keep") + plot_annotation(tag_levels="i") 
PBFigAlt


```

PB SI fig
```{r}
layout <- "ACC
           BDD
           EEE
           FFF
           FFF
          "

PBControlFig <- 
            ((PBCompControlIn+guides(color=FALSE))
              +  PBCompControlOut  +
         (PBSynapseCountDiffControl + theme(legend.position="none")) + 
         (PBSlopesControl + guides(color=FALSE)) +
         PBCompSlopesComp + plot_spacer()) + plot_layout(design=layout,guides="keep") + plot_annotation(tag_levels="A",title= "Validation Figure 2 - Figure supplement 1: comparing PB glomeruli at equivalent tracing levels",theme=theme(title=element_text(size=12*1.111111,face="bold")))
PBControlFig 

save_plot(paste0(validationFolder,"validation-Figure2-SI1.svg"),PBControlFig,base_width = 8.5*1.333333,base_height=11*1.333333)
```


### Anatomy illustration of FB column 3
```{r}
FC3Mesh <- neuprintr::neuprint_ROI_mesh("FB-column3") #readobj::read.obj("~/Dropbox (HHMI)/FIBSEM CX Paper Jan 2020/Figures/validation/FB-column3.obj",convert.rgl = TRUE)[[1]]
FBMesh <- neuprintr::neuprint_ROI_mesh("FB")
```




```{r}
hDeltaA_C3 <- lapply(hDeltaA_C3Id,getNeuronMesh,cloud=TRUE)
hDeltaA_CX <- lapply(hDeltaA_CXId,getNeuronMesh,cloud=TRUE)
hDeltaA_C3Synapses <- neuprint_get_synapses(hDeltaA_C3Id,roi="FB") %>% filter(prepost==0)
hDeltaA_CXSynapses <- neuprint_get_synapses(hDeltaA_CXId,roi="FB") %>% filter(prepost==0)
```


```{r}
nopen3d()
par3d(windowRect = c(20, 30, 1500, 1500))
plot3d(FBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE,smooth=FALSE)
par3d(scale=c(1,1,1))
plot3d(FC3Mesh,color="#908827",add=TRUE,alpha=0.2,smooth=FALSE,shininess=100)
plot3d(hDeltaA_C3[[1]],color="SteelBlue",add=TRUE,smooth=FALSE,shininess=100)
plot3d(hDeltaA_C3Synapses[c("x","y","z")],add=TRUE,col="orange",size=5)
plot3d(hDeltaA_CX[[1]],color="grey80",add=TRUE,smooth=FALSE,shininess=100)
plot3d(hDeltaA_CX[[2]],color="grey60",add=TRUE,smooth=FALSE,shininess=100)
plot3d(hDeltaA_CX[[3]],color="grey40",add=TRUE,smooth=FALSE,shininess=100)
plot3d(hDeltaA_CXSynapses[c("x","y","z")],add=TRUE,col="orange",size=5)
nview3d("ventral")
rgl.snapshot(paste0(validationFolder,"frontC3.png"))
```

```{r}
FBC3Frame <- ggdraw() + draw_image(paste0(validationFolder,"frontC3.png"),scale=1.55,vjust=0,clip="on") + theme_paper_map()
FBC3Frame <- FBC3Frame + annotate(geom="text",x=0.35,y=0.62,label="Column 3",color="#908827")
FBC3Frame <- FBC3Frame + annotate(geom="text",x=0.4,y=0.84,label="hΔA outputing \n in other columns",color="grey20")
FBC3Frame <- FBC3Frame + annotate(geom="text",x=0.76,y=0.92,label="hΔA outputing \n in column 3",color="SteelBlue")
FBC3Frame <- FBC3Frame + annotate(geom="point",x=0.73,y=0.79,color="orange",size=1) + 
  annotate(geom="text",x=0.84,y=0.79,label="Output synapses")
FBC3Frame
```

FB panel

```{r}
fcLayout <- c(
  area(t = 1, l = 1, b = 5, r = 5),
  area(t = 1, l = 6, b = 4, r = 10),
  area(t = 6, l = 2, b = 8, r = 4),
  area(t = 5, l = 6, b = 8, r = 10)
)


FC3Panel <- (FBC3Frame + 
  (synapseDiffC3 + theme(legend.position = "none")) + (FBComp + theme(legend.position = "none")) + 
  FC3Slopes) + plot_layout(design = fcLayout) + plot_annotation(tag_levels=c("i"))
FC3Panel
```

### EB before/after comparison
```{r}
EBMesh <- neuprint_ROI_mesh("EB")
```

#### Comparing neuron to neuron connections
```{r}
exampleEPG <- 789126240
exampleEPGNew <- getNeuronMesh(exampleEPG,cloud=TRUE)
exampleEPGOld <- getNeuronMesh(exampleEPG,cloud=TRUE,node="34d7a")
epgInputSynapsesNew <- filter(neuprint_get_synapses(exampleEPG,roi="EB",conn=newConnection),prepost==1)# %>% select(x,y,z)
epgInputSynapsesOld <- filter(neuprint_get_synapses(exampleEPG,roi="EB",conn=oldConnection),prepost==1)# %>% select(x,y,z)
partnerListNew <- filter(neuprint_get_meta(unique(c(epgInputSynapsesNew$partner)),all_segments = FALSE,conn=newConnection),status=="Traced")
partnerListOld <- filter(neuprint_get_meta(unique(c(epgInputSynapsesOld$partner)),all_segments = FALSE,conn=oldConnection),status=="Traced")
epgInputSynapsesNew <-  filter(epgInputSynapsesNew,partner %in% partnerListNew$bodyid) %>% select(x,y,z)
epgInputSynapsesOld <- filter(epgInputSynapsesOld,partner %in% partnerListOld$bodyid) %>% select(x,y,z)
```


```{r}
nopen3d()
par3d(windowRect = c(30, 30, 1530, 1530))
plot3d(EBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
shade3d(exampleEPGOld,color="grey80")
shade3d(exampleEPGNew,color="red")
plot3d(epgInputSynapsesOld,add=T,col="#B32DB5")
plot3d(epgInputSynapsesNew,add=T,col="#053CFF")
nview3d("ventral")
zoom0View <- par3d("userProjection")
rgl.snapshot(paste0(validationFolder,"frontEBZoom1.png"))
```

```{r}
nopen3d()
par3d(windowRect = c(30, 30, 1530, 1530))
par3d(userProjection=translationMatrix(-1.2,1.6,0) %*% zoom0View)
plot3d(EBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
nview3d("ventral",zoom=0.1)
shade3d(addNormals(exampleEPGOld),color="grey80")
shade3d(addNormals(exampleEPGNew),color="red")


plot3d(epgInputSynapsesOld,add=T,col="#B32DB5",size=15)
plot3d(epgInputSynapsesNew,add=T,col="#053CFF",size=15)
```

```{r}
rgl.snapshot(paste0(validationFolder,"frontEBZoom2.png"))
```

```{r}
EPGViews <- ggdraw() + draw_image(paste0(validationFolder,"frontEBZoom1.png"),scale=1.6,clip="on") + draw_image(paste0(validationFolder,"frontEBZoom2.png"),scale=0.5,vjust=-0.23,hjust=0.05,clip="on") + theme_paper_map() + 
   annotate(geom="text",x=0.25,y=0.22,label="Synapses",hjust=0) +
  annotate(geom="point",x=0.25,y=0.18,color="#B32DB5",size=1) + 
  annotate(geom="point",x=0.25,y=0.14,color="#053CFF",size=1) +
  annotate(geom="text",x=0.26,y=0.18,label="Initially traced",hjust=0) +
  annotate(geom="text",x=0.26,y=0.14,label="New additions",hjust=0) +
  annotate(geom="text",x=0.33,y=0.68,label="*",hjust=0,size=8,color="red")
EPGViews
```

```{r}
ebLayout <- c(
  area(t = 1, l = 1, b = 5, r = 5),
  area(t = 1, l = 6, b = 4, r = 10),
  area(t = 6, l = 2, b = 8, r = 4),
  area(t = 5, l = 6, b = 8, r = 10)
)

EBFig <- (EPGViews + 
  synChangeEB  + (EBCompExample + theme(legend.position="none")) +
  (EBSlopes+ theme(legend.position="none"))) +plot_layout(design = ebLayout) #+ plot_annotation(tag_levels=c("A","i"))

EBFig
```

```{r}
mainFig <- (EBFig + plot_layout(tag_level = "new")) / (PBFigAlt + plot_layout(tag_level = "new"))/(FC3Panel + plot_layout(tag_level="new")) + plot_annotation(tag_levels=c("A","i"),tag_sep = "",title="Validation - Figure 1: tracing effect on connection weights",theme=theme(title=element_text(size=12,face="bold"))) 
mainFig

save_plot(paste0(validationFolder,"Validation-Figure1.pdf"),mainFig,nrow = 4,ncol=2,base_width = 8.5/2,base_height=11/3,device=cairo_pdf)
```

```{r}
EBCompFull <- ggplot(filter(EBAges_filtered),aes(x=old,y=new,fill=supertype2)) + geom_smooth(formula=y~x,aes(group=bodyid),method="lm",alpha=0.3,color="grey30",size=0.1) + 
  geom_abline(linetype=2,lwd=0.2) + scale_fill_CX_supertype(name="Supertype") + xlab("relative weight in the old dataset") + coord_fixed() +
  ylab("relative weight in the new dataset") + facet_wrap(supertype2~side)+ theme_paper() + ggtitle("Validation figure 1 - figure supplement 1: individual neuron to neuron fits")#+theme(panel.border = element_rect(color = "gray 50", fill = NA))
#EBCompFull
save_plot(paste0(validationFolder,"Validation-Figure1-SI1.pdf"),EBCompFull,nrow = 2,ncol=3,base_width = 8.5/3,device=cairo_pdf)
```