---
title: "FB bump tracking"
output: html_notebook
---


```{r}
library(neuprintr)
library(tidyverse)
library(cowplot)
library(neuprintrExtra)
library(reshape2)
library(patchwork)
library(gridExtra)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\PBAnalysisUtils.R")
```

Function to rename FB neurons
```{r}
FBRename <- function(name,id){
  
  # From a unique nameif from the PB type, the PB gloms where it arborizes, and the bodyid
  name  <- gsub("\\s*\\([^\\)]+\\)","",as.character(name))
  name  <- gsub("\\^","-",as.character(name))
  nameid <- paste(name, as.character(id), sep='-')
  
  # Extract the unique names and types
  allNames = nameid %>% unique() %>% sort()
  nameLabels = name %>% unique() %>% sort()
  types = strsplit(allNames,'_') %>% lapply(function(x){x[[1]]}) %>% unique() %>% unlist()
  types = gsub("([\\(\\)])", "\\\\\\1",types)
  
  # Sort the names by the order of the glomeruli in the PB and exchange the bodyid for a number
  newNames = c()
  for (tp in 1:length(types)){
    allNames[which(grepl(paste0('^',types[tp],"_"),allNames))] <- 
      allNames[which(grepl(paste0('^',types[tp],"_"),allNames))] %>% sort()
    nmOrder <- allNames[which(grepl(paste0('^',types[tp],"_"),allNames))] %>% sort()
    nms <- nameLabels[which(grepl(paste0('^',types[tp],"_"),nameLabels))]
    for (n in 1:length(nms)){
      nmsNow <- nmOrder[which(grepl(nms[n],nmOrder))]
      nmsNow <- paste(nms[n],seq(1:length(nmsNow)),sep='-')
      nmOrder[which(grepl(nms[n],nmOrder))] <- nmsNow
    }
    newNames = append(newNames,nmOrder)
  }
  # Create a lookup table between the old and new names
  nmSwap <- data.frame(oldNm = allNames, newNm = newNames)
  
  # Swap in the new names
  nameid <- lapply(nameid, function(x) nmSwap$newNm[match(x, nmSwap$oldNm)]) %>%
    factor(levels = nmSwap$newNm)
  
  return(nameid)
}
```

Create a bump in the EB
```{r}
gloms = c("R1","L8","R2","L7","R3","L6","R4","L5",
         "R5","L4","R6","L3","R7","L2","R8","L1")
actProfvM <- data.frame(act = vonMisesProf(),glom = gloms)
actProfvM <- rbind(actProfvM, data.frame(act = c(0,0), glom = c("L9","R9")))
```

Follow a bump from the EB to the PB to the FB (for a PFX type)
```{r}
# Specify the FB types of interest
nronTypes <- c("PFGs","PFNd","PFL2","PFL3")

# Create a list to hold the plots
p_list <- list()

for (t in 1:length(nronTypes)){
  # Get the type information
  typeDat <- getTypesTable(nronTypes[t])
  typeDat$gloms <- lapply(typeDat$name, function(n) strsplit(n,'_')[[1]][2]) %>% unlist() %>% as.character()
  typeDat$LR <- lapply(typeDat$gloms, function(g) substring(g,1,1)) %>% unlist() %>% as.factor()
  typeDat$cols <- lapply(typeDat$name, function(n) strsplit(n,'_')[[1]][3]) %>% unlist() %>% as.character()
  typeDat$cols <- factor(typeDat$cols, levels = unique(typeDat$cols) %>% sort())
  typeDat$id <- FBRename(typeDat$name,typeDat$bodyid)

  # Place the activity into the given type
  typeDat$act <- lapply(typeDat$gloms, function(g) actProfvM$act[which(actProfvM$glom == g)]) %>% unlist() %>% as.numeric()

  # Plot
  p_list[[t]] <- ggplot(typeDat) + geom_tile(aes(x=as.factor(id),y=LR,fill=act)) + 
    facet_grid(cols = vars(cols),scales = "free") + 
    theme_cowplot() + theme(axis.text.x = element_text(angle = 90,size=1)) +
    scale_fill_gradient(low="white", high="black") + 
    ggtitle(nronTypes[t])
}

pdf("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FBBumps_col.pdf")
grid.arrange(grobs = p_list,ncol = 1)
dev.off()

```

Copy the bump from a PFX neuron to a second neuron and Plot
Specify the presynaptic PFX type and plot its activity
```{r}
PFType <- "PFNd"

# Get the info for the PFX type
PFtypeDat <- getTypesTable(PFType)
PFtypeDat$gloms <- lapply(PFtypeDat$name, function(n) strsplit(n,'_')[[1]][2]) %>% unlist() %>% as.character()
PFtypeDat$LR <- lapply(PFtypeDat$gloms, function(g) substring(g,1,1)) %>% unlist() %>% as.factor()
PFtypeDat$cols <- lapply(PFtypeDat$name, function(n) strsplit(n,'_')[[1]][3]) %>% unlist() %>% as.character()
PFtypeDat$cols <- factor(PFtypeDat$cols, levels = unique(PFtypeDat$cols) %>% sort())
PFtypeDat$id <- FBRename(PFtypeDat$name,PFtypeDat$bodyid)

# Place the activity into the given type
PFtypeDat$act <- lapply(PFtypeDat$gloms, function(g) actProfvM$act[which(actProfvM$glom == g)]) %>% unlist() %>% as.numeric()

# Plot the presynaptic "activity"
g_pre <- ggplot(PFtypeDat) + geom_tile(aes(x=as.factor(id),y=LR,fill=act)) + 
    facet_grid(cols = vars(cols),scales = "free") + 
    theme_cowplot() + theme(axis.text.x = element_text(angle = 90,size=1)) +
    scale_fill_gradient(low="white", high="black") + 
    ggtitle(PFType)

print(g_pre)
```

Specify the postsynaptic type and plot its activity
```{r}
# Specify the postsynaptic FB type
FPost <- "hDeltaA"

# Get the info for the postsynaptic FB type
FPostDat <- getTypesTable(FPost)
FPostDat$cols <- lapply(FPostDat$name, function(n) strsplit(n,'_')[[1]][3]) %>% unlist() %>% as.character()
FPostDat$cols <- factor(FPostDat$cols, levels = as.factor(c("C1","C2","C3","C4","C5","C6","C7","C8","C9","C10","C11","C12")))
FPostDat$id <- FBRename(FPostDat$name,FPostDat$bodyid)
FPostDat$LR <- NA

# Get the connection table between the two types
conTab <- getConnectionTable(PFType,"POST","FB") %>% filter(type.to == FPost)
conTab$id.from <- FBRename(conTab$name.from,conTab$from)
conTab$id.to <- FBRename(conTab$name.to,conTab$to)

# Get info about the pre and post neurons
allPreIds = PFtypeDat$id
allPostIds = FPostDat$id

# Create a matrix of just the weights
justWeights = matrix(0L,nrow=length(allPreIds),ncol=length(allPostIds))
for (i in 1:length(allPreIds)){
  for (j in 1:length(allPostIds)){
    w = conTab[which(conTab$id.from == allPreIds[i] & conTab$id.to == allPostIds[j]),]$weight
    if (length(w) > 0)
      justWeights[i,j] = w
  }
}

# Use the weights to get the downstream "activity"
FPostDat$act <- PFtypeDat$act %*% justWeights %>% as.vector()

# Plot it
g_post <- ggplot(FPostDat) + geom_tile(aes(x=as.factor(id),y=LR,fill=act)) + 
    facet_grid(cols = vars(cols),scales = "free") + 
    theme_cowplot() + theme(axis.text.x = element_text(angle = 90,size=1)) +
    scale_fill_gradient(low="white", high="black") + 
    ggtitle(FPost)
```

Combine the pre and post plots and plot
```{r}
pdf("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FBBumps_within.pdf")
grid.arrange(grobs = list(g_pre,g_post),ncol = 1)
dev.off()
```
