---
title: "AB neurons"
output: html_notebook
---
Load the libraries
```{r}
library(nat)
library(neuprintr)
library(neuprintrExtra)
library(reshape2)
library(patchwork)
source("..\\R\\paperTheme.R")
source("FBNetworkVisUtils.R")
source("..\\R\\visualizeConnectivityTables.R")
```

Find all of the AB neurons
```{r}
ABNrons <- rbind(neuprint_bodies_in_ROI("AB(R)"),neuprint_bodies_in_ROI("AB(L)")) %>% mutate(type = neuprint_get_meta(bodyid)$type)
ABTypes <- ABNrons$type %>% unique()
ABTypes <- ABTypes[!is.na(ABTypes)]
ABROIDat <- neuprint_get_roiInfo(getTypesTable(ABTypes))
ABROIDat[is.na(ABROIDat)] <- 0
ABROIDat <- ABROIDat[(ABROIDat['AB(R).pre'] > 2) |
                       (ABROIDat['AB(R).post'] > 2) |
                       (ABROIDat['AB(L).pre'] > 2) |
                       (ABROIDat['AB(L).post'] > 2),] %>% 
  mutate(type = neuprint_get_meta(bodyid)$type)
ABTypes <- ABROIDat$type %>% unique()
```

Look at their connectivity in the AB
```{r}
conTab_AB_R <- getConnectionTable(getTypesTable(ABTypes),'POST','AB(R)') %>% filter(type.to %in% ABTypes)
conTab_AB_R$id.from <- FBRename(conTab_AB_R$name.from, conTab_AB_R$from)
conTab_AB_R$id.to <- FBRename(conTab_AB_R$name.to, conTab_AB_R$to)

T2T_AB_R <- getTypeToTypeTable(conTab_AB_R)

conTab_AB_L <- getConnectionTable(getTypesTable(ABTypes),'POST','AB(L)') %>% filter(type.to %in% ABTypes)
conTab_AB_L$id.from <- FBRename(conTab_AB_L$name.from, conTab_AB_L$from)
conTab_AB_L$id.to <- FBRename(conTab_AB_L$name.to, conTab_AB_L$to)

T2T_AB_L <- getTypeToTypeTable(conTab_AB_L)
```
```{r}
T2TPlt_AB_R <- plotConnectivityMatrix(T2T_AB_R, byGroup = "type") + 
    coord_equal(ratio=1) + xlab("postsynaptic type") + ylab("presynaptic type") + theme_paper() + theme(axis.text.x = element_text(angle=90)) +
    guides(fill = guide_colourbar(title = 'relative weight', title.position = 'left', title.theme = element_text(angle = 90), barwidth = 0.5, title.hjust = 0.5)) +
    ggtitle('AB(R)')

T2TPlt_AB_L <- plotConnectivityMatrix(T2T_AB_L, byGroup = "type") + 
    coord_equal(ratio=1) + xlab("postsynaptic type") + ylab("presynaptic type") + theme_paper() + theme(axis.text.x = element_text(angle=90)) +
    guides(fill = guide_colourbar(title = 'relative weight', title.position = 'left', title.theme = element_text(angle = 90), barwidth = 0.5, title.hjust = 0.5)) +
    ggtitle('AB(L)')

TCTPlt_AB <- T2TPlt_AB_R + T2TPlt_AB_L + plot_layout(ncol = 4)
print(TCTPlt_AB)
```

Look at inputs in FB to FB->AB neurons
```{r}
ABInsFromFB <- c('vDeltaA_a', 'FS4A', 'FB1B', 'FB1G')

conTab_ABFromFB <- getConnectionTable(getTypesTable(ABInsFromFB),'PRE','FB')
conTab_ABFromFB$id.from <- FBRename(conTab_ABFromFB$name.from, conTab_ABFromFB$from)
conTab_ABFromFB$id.to <- FBRename(conTab_ABFromFB$name.to, conTab_ABFromFB$to)
```
```{r}
T2T_ABFromFB <- getTypeToTypeTable(conTab_ABFromFB)
T2TPlt_ABFromFB <- plotConnectivityMatrix(T2T_ABFromFB, byGroup = "type") + 
    coord_equal(ratio=1) + xlab("postsynaptic type") + ylab("presynaptic type") + theme_paper() + theme(axis.text.x = element_text(angle=90, hjust=1,vjust=0)) +
    guides(fill = guide_colourbar(title = 'relative weight', title.position = 'left', title.theme = element_text(angle = 90), barwidth = 0.5, title.hjust = 0.5))
T2TPlt_ABFromFB
```

Look at outputs in FB from AB->FB neurons
```{r}
ABOutsInFB <- c('SA1_a','SA1_b','SA3','SAF','FS4A', 'FS4B', 'vDeltaA_a', 'vDeltaA_b')
conTab_ABToFB <- getConnectionTable(getTypesTable(ABOutsInFB),'POST','FB')
conTab_ABToFB$id.from <- FBRename(conTab_ABToFB$name.from, conTab_ABToFB$from)
conTab_ABToFB$id.to <- FBRename(conTab_ABToFB$name.to, conTab_ABToFB$to)
```

```{r}
T2T_ABToFB <- getTypeToTypeTable(conTab_ABToFB)
T2TPlt_ABToFB <- plotConnectivityMatrix(T2T_ABToFB, byGroup = "type") + 
    coord_equal(ratio=1) + xlab("postsynaptic type") + ylab("presynaptic type") + theme_paper() + theme(axis.text.x = element_text(angle=90, hjust=1,vjust=0)) +
    guides(fill = guide_colourbar(title = 'relative weight', direction = 'horizontal', title.position = 'top', barheight = 0.5))
T2TPlt_ABToFB
```

Plot the column specific connectivity between vDA_a, vDa_b, FS4A, and FS4B and the R or L AB
```{r}
nronTypes <- c('vDeltaA_a','vDeltaA_b','FS4A','FS4B')

ABROIs <- neuprint_get_roiInfo(getTypesTable(nronTypes)$bodyid) %>% 
  select("bodyid","AB(R).upstream","AB(R).downstream","AB(L).upstream","AB(L).downstream") %>%
  melt(id=c('bodyid')) %>%
  mutate(type = neuprint_get_meta(bodyid)$type, name = neuprint_get_meta(bodyid)$name) %>%
  as.data.frame()
ABROIs$id <- FBRename(ABROIs$name,ABROIs$bodyid)
ABROIs$roi <- lapply(ABROIs$variable, function(v) strsplit(as.character(v),'.',fixed=TRUE)[[1]][1]) %>% unlist()
ABROIs$updown <- lapply(ABROIs$variable, function(v) strsplit(as.character(v),'.',fixed=TRUE)[[1]][2]) %>% unlist()
ABROIs[which(is.na(ABROIs$value)),]$value <- 0
```
```{r}
col2ROI_plt_vDA_as <- ggplot(ABROIs %>% filter(type == "vDeltaA_a")) + geom_bar(aes(x=id, y = value, fill=roi),stat='identity') +
  facet_grid(rows = vars(updown), cols = vars(type), scale='free') + 
  theme_paper() + theme(axis.text.x = element_text(angle = 90)) + 
  ylab('mean # of synapses per neuron') + xlab('neuron name')
print(col2ROI_plt_vDA_as)
```
```{r}
ABROIave <- ABROIs %>% group_by(type,name,roi,updown) %>% summarize(meanCts = mean(value))
ABROIave$name <- lapply(ABROIave$name, function(n) gsub("\\s*\\([^\\)]+\\)","",n)) %>% unlist()
ABROIave$name <- factor(ABROIave$name, levels = ABROIave$name %>% unique() %>% sort())
col2ROI_plt <- ggplot(ABROIave) + geom_bar(aes(x=name, y = meanCts, fill=roi),stat='identity') +
  facet_grid(rows = vars(updown), cols = vars(type), scale='free') + 
  theme_paper() + theme(axis.text.x = element_text(angle = 90)) + 
  ylab('mean # of synapses per neuron') + xlab('neuron name')
```

```{r}
layout <- "
AB
"

ABROIplts <- col2ROI_plt_vDA_as + col2ROI_plt + plot_layout(design = layout)

print(ABROIplts)
```

