---
title: "FB Figure - FBt DAN analysis"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(gridExtra)
library(paletteer)
library(neuprintrExtra)
library(cowplot)
library(reshape2)
library(patchwork)
library(visNetwork)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\FBNetworkVisUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\R\\connectivityMatricesTools.R")
options(nat.plotengine = 'rgl')
```

Specify plotting parameters
```{r}
update_geom_defaults("text", list(size = 6*0.35))
theme_paper <- function(...){
  theme_cowplot(font_size=7,rel_small=6/7,rel_tiny = 5/7,rel_large = 8/7) + theme(strip.background = element_blank(),...)
}

stCols <- supertype2Palette()
stCols$breaks <- append(stCols$breaks,'OA-VPM3')
stCols$pal <- append(stCols$pal,'#000000FF')
```

Get the FB columnar types
```{r}
FBNrons <- neuprint_bodies_in_ROI("FB") %>% mutate(type = neuprint_get_meta(bodyid)$type)
FBTypes <- FBNrons$type %>% unique()
FBTypesCol <- FBTypes[which(grepl("PF",FBTypes) |
                           grepl("FS",FBTypes) |
                           grepl("FC",FBTypes) |
                           grepl("FR",FBTypes) |
                           grepl("vDelta",FBTypes) |
                           grepl("hDelta",FBTypes)
                           )]
```


Pull FBt DAN to FB columnar connections
```{r}
FBtDANs <- c("FB2A","FB3A","FB4K","FB4L","FB5H","FB6H","FB7B")
FBtDAN_POST <- getConnectionTable(getTypesTable(FBtDANs)$bodyid,"POST","FB")
FBtDAN_POST <- FBtDAN_POST %>% filter(type.to %in% FBTypesCol)

FBtDAN_POST$id.from <- FBRename(FBtDAN_POST$name.from,FBtDAN_POST$from)
FBtDAN_POST$id.to <- FBRename(FBtDAN_POST$name.to,FBtDAN_POST$to)
FBtDAN_POST$col.to <- FBtDAN_POST$id.to %>% 
  lapply(function(x) substr(x,
                            gregexpr(pattern ='_C',x)[[1]][1]+1,
                            gregexpr(pattern ='_C',x)[[1]][1]+2)) %>%
  unlist()
FBtDAN_POST$col.to <- factor(FBtDAN_POST$col.to,levels=sort(unique(FBtDAN_POST$col.to)))
```

Plot the neuron to neuron connectivity for each type
```{r}

for (t in 1:length(FBtDANs)){
  datNow <- FBtDAN_POST %>% filter(type.from == FBtDANs[t])
  datNow <- datNow %>% group_by(id.from,type.to,col.to) %>% summarise(meanOutputContribution = mean(outputContribution))
  
  FBtDAN_POST_Nron_Plt <- ggplot(datNow) + 
    scale_fill_gradient2(low="thistle", mid="blueviolet", high="black",
                         midpoint =0.5*max(datNow$meanOutputContribution),
                         limits=c(0,max(datNow$meanOutputContribution))) +
    geom_tile(aes(col.to,id.from,fill=meanOutputContribution)) +
    theme_paper() + coord_fixed(ratio = 1) + 
    theme(axis.text.x = element_text(angle = 90,hjust=1)) +
    xlab("FB column") + ylab("presynaptic type") + 
    facet_grid(rows=vars(type.to)) + 
    ggtitle(FBtDANs[t])
  
  print(FBtDAN_POST_Nron_Plt)

  ggsave(paste0('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_TanConnectivity\\',FBtDANs[t],"_NronToNron_byCol_Mean.pdf"),FBtDAN_POST_Nron_Plt)
    
  datNowNorm <- FBtDAN_POST %>% filter(type.from == FBtDANs[t])
  datNowNorm <- datNowNorm %>% group_by(type.to,col.to) %>% summarise(meanOutputContribution = mean(outputContribution))

  typesTo <- datNowNorm$type.to %>% unique() %>% sort()
  colsTo <- datNowNorm$col.to %>% unique() %>% sort()
  for (t in 1:length(typesTo)){
    for (c in 1:length(colsTo)){
      if (nrow(datNowNorm %>% filter(type.to == typesTo[t] & col.to == colsTo[c])) == 0){
        datNowNorm <- rbind(datNowNorm,data.frame(type.to=typesTo[t],
                                                  col.to = colsTo[c],
                                                  meanOutputContribution = 0))
      }
    }
  }
  
  for (t in 1:length(typesTo)){
    valsNow <- datNowNorm[which(datNowNorm$type.to == typesTo[t]),]$meanOutputContribution
    datNowNorm[which(datNowNorm$type.to == typesTo[t]),]$meanOutputContribution <- valsNow/max(valsNow)
  }
  
  FBtDAN_POST_Nron_Plt_Mean_Line <- ggplot(datNowNorm) +
    geom_line(aes(x=col.to,y=meanOutputContribution, group=type.to,color=type.to)) +
    theme_paper() +
    theme(axis.text.x = element_text(angle = 90,hjust=1)) +
    xlab("FB col") + ylab("presynaptic type")
  
  print(FBtDAN_POST_Nron_Plt_Mean_Line)

  ggsave(paste0('C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_TanConnectivity\\',FBtDANs[t],"_NronToNron_byCol_Mean_NormalizedLines.pdf"),FBtDAN_POST_Nron_Plt_Mean_Line)
}
```
