---
title: "FB Figure - vDelta subnetwork"
output: html_notebook
---

Load the libraries
```{r}
library(nat)
library(neuprintr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(gridExtra)
library(paletteer)
library(neuprintrExtra)
library(cowplot)
library(reshape2)
library(patchwork)
library(visNetwork)
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\FBNetworkVisUtils.R")
source("C:\\Users\\turnerevansd\\Documents\\FIBSEM\\neuprintR-notebooks\\R\\connectivityMatricesTools.R")
options(nat.plotengine = 'rgl')
```

Specify plotting parameters
```{r}
update_geom_defaults("text", list(size = 6*0.35))
theme_paper <- function(...){
  theme_cowplot(font_size=7,rel_small=6/7,rel_tiny = 5/7,rel_large = 8/7) + theme(strip.background = element_blank(),...)
}

stCols <- supertype2Palette()
stCols$breaks <- append(stCols$breaks,'OA-VPM3')
stCols$pal <- append(stCols$pal,'#000000FF')
```

Specify the neuron types to look at
```{r}
vDClust <- c('vDeltaF','vDeltaG','vDeltaH','vDeltaI')
```

Pull their neuron bag
```{r}
vDBag <- neuronBag(getTypesTable(vDClust),slctROI="FB")
```


Plot the neuron to neuron connections
```{r}
vDOuts <- vDBag$outputs_raw
vDOuts$id.from <- FBRename(vDOuts$name.from,vDOuts$from)
vDOuts$id.to <- FBRename(vDOuts$name.to,vDOuts$to)

txtLabsTo <- vDOuts$id.to %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsTo <- lapply(txtLabsTo,function(t) strsplit(t,'-')[[1]][1]) %>% unlist() %>% as.character() %>% unlist()
typLabsTo <- gsub("_R[0-9]","",as.character(typLabsTo))
typLabsTo <- gsub("_R","",as.character(typLabsTo))
typLabsTo <- gsub("_L[0-9]","",as.character(typLabsTo))
typLabsTo <- gsub("_L","",as.character(typLabsTo))
typLabsTo <- gsub("_C[0-9][0-9]","",as.character(typLabsTo))
typLabsTo <- gsub("_C[0-9]","",as.character(typLabsTo))
typLabsTo <- gsub("_[0-9][0-9]","",as.character(typLabsTo))
typLabsTo <- gsub("_irreg","",as.character(typLabsTo))
typLabsTo <- gsub("OA","OA-VPM3",as.character(typLabsTo))
txtColsTo <- lapply(typLabsTo,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

txtLabsFrom <- vDOuts$id.from %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsFrom <- lapply(txtLabsFrom,function(t) strsplit(t,'-')[[1]][1]) %>% unlist() %>% as.character() %>% unlist()
typLabsFrom <- gsub("_C[0-9]","",as.character(typLabsFrom))
txtColsFrom <- lapply(typLabsFrom,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

vDOuts_Plt <- ggplot(vDOuts) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(vDOuts$weightRelative),
                       limits=c(0,max(vDOuts$weightRelative))) +
  geom_tile(aes(id.to,id.from,fill=weightRelative)) +
  theme_paper() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,color=txtColsTo),
        axis.text.y = element_text(color=txtColsFrom)) +
  xlab("postsynaptic neuron") + ylab("presynaptic neuron")

offset <- 0.5
typesTo <- vDOuts$type.to %>% unique() %>% sort()
for (g in 1:length(typesTo)){
  offset <- offset + length(which(typesTo[g] == typLabsTo))
  vDOuts_Plt <- vDOuts_Plt + geom_vline(xintercept = offset)
}

offset <- 0.5
typesFrom <- vDClust
for (g in 1:length(typesFrom)){
  offset <- offset + length(which(typesFrom[g] == typLabsFrom))
  vDOuts_Plt <- vDOuts_Plt + geom_hline(yintercept = offset)
}

print(vDOuts_Plt)
ggsave("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_ColNronNetwork\\vDSubNet-outs.pdf",vDOuts_Plt)
```

```{r}
vDIns <- vDBag$inputs_raw
vDIns$id.from <- FBRename(vDIns$name.from,vDIns$from)
vDIns$id.to <- FBRename(vDIns$name.to,vDIns$to)

txtLabsFrom <- vDIns$id.from %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsFrom <- lapply(txtLabsFrom,function(t) strsplit(t,'-')[[1]][1]) %>% unlist() %>% as.character() %>% unlist()
typLabsFrom <- gsub("_R[0-9]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_R","",as.character(typLabsFrom))
typLabsFrom <- gsub("_L[0-9]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_L","",as.character(typLabsFrom))
typLabsFrom <- gsub("_C[0-9][0-9][a-z]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_C[0-9][0-9]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_C[0-9][a-z]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_C[0-9]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_[0-9][0-9]","",as.character(typLabsFrom))
typLabsFrom <- gsub("_irreg","",as.character(typLabsFrom))
typLabsFrom <- gsub("OA","OA-VPM3",as.character(typLabsFrom))
txtColsFrom <- lapply(typLabsFrom,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

txtLabsTo <- vDIns$id.to %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsTo <- lapply(txtLabsTo,function(t) strsplit(t,'-')[[1]][1]) %>% unlist() %>% as.character() %>% unlist()
typLabsTo <- gsub("_C[0-9]","",as.character(typLabsTo))
txtColsTo <- lapply(typLabsTo,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

vDIns_Plt <- ggplot(vDIns) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(vDIns$weightRelative),
                       limits=c(0,max(vDIns$weightRelative))) +
  geom_tile(aes(id.to,id.from,fill=weightRelative)) +
  theme_paper() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,color=txtColsTo),
        axis.text.y = element_text(color=txtColsFrom)) +
  xlab("postsynaptic neuron") + ylab("presynaptic neuron")

offset <- 0.5
typesTo <- vDIns$type.to %>% unique() %>% sort()
for (g in 1:length(typesTo)){
  offset <- offset + length(which(typesTo[g] == typLabsTo))
  vDIns_Plt <- vDIns_Plt + geom_vline(xintercept = offset)
}

offset <- 0.5
typesFrom <- vDIns$type.from %>% unique() %>% sort()
for (g in 1:length(typesFrom)){
  offset <- offset + length(which(typesFrom[g] == typLabsFrom))
  vDIns_Plt <- vDIns_Plt + geom_hline(yintercept = offset)
}

print(vDIns_Plt)
ggsave("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_ColNronNetwork\\vDSubNet-ins.pdf",vDIns_Plt)
```

Plot the type-to-type connections
```{r}
vDOuts_T2T<- vDBag$outputs

typesTo <- vDOuts_T2T$type.to %>% unlist() %>% unique() %>% as.character()
toLevels <- c(typesTo[which(grepl('PFN',typesTo))],
              sort(typesTo[which(!grepl('PFN',typesTo) & 
                                  !grepl('PFR_b',typesTo) &
                                  !grepl('FC',typesTo) &
                                   !grepl('FR',typesTo) &
                                   !grepl('FS',typesTo) &
                                   !grepl('PFL',typesTo))]),
              typesTo[which(grepl('FC',typesTo))],
              typesTo[which(grepl('FS',typesTo))],
              typesTo[which(grepl('PFR_b',typesTo))],
              typesTo[which(grepl('FR1',typesTo))],
              typesTo[which(grepl('PFL',typesTo))]
              )
vDOuts_T2T$type.to <- factor(vDOuts_T2T$type.to,
                              levels = toLevels)

txtLabsTo <- toLevels
typLabsTo <- txtLabsTo
txtColsTo <- lapply(typLabsTo,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

txtLabsFrom <- vDOuts_T2T$type.from %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsFrom <- txtLabsFrom
txtColsFrom <- lapply(typLabsFrom,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

vDOuts_T2T_Plt <- ggplot(vDOuts_T2T) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(vDOuts_T2T$weightRelative),
                       limits=c(0,max(vDOuts_T2T$weightRelative))) +
  geom_tile(aes(type.to,type.from,fill=weightRelative)) +
  theme_paper() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,color=txtColsTo),
        axis.text.y = element_text(color=txtColsFrom)) +
  xlab("postsynaptic neuron") + ylab("presynaptic neuron")

offset <- 0.5
typesTo <- vDOuts_T2T$type.to %>% unique() %>% sort() %>% as.character()
stTo <- supertype(typesTo) %>% unique()
for (g in 1:length(stTo)){
  offset <- offset + length(which(stTo[g] == supertype(typesTo)))
  vDOuts_T2T_Plt <- vDOuts_T2T_Plt + geom_vline(xintercept = offset)
}

offset <- 0.5
typesFrom <- vDOuts_T2T$type.from %>% unique() %>% sort()
stFrom <- supertype(typesFrom) %>% unique()
for (g in 1:length(stFrom)){
  offset <- offset + length(which(stFrom[g] == supertype(typesFrom)))
  vDOuts_T2T_Plt <- vDOuts_T2T_Plt + geom_hline(yintercept = offset)
}

print(vDOuts_T2T_Plt)
ggsave("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_ColNronNetwork\\vDSubNet-outs_type-to-type.pdf",vDOuts_T2T_Plt)
```


```{r}
vDIns_T2T<- vDBag$inputs

txtLabsTo <- vDIns_T2T$type.to %>% unlist() %>% unique() %>% as.character() %>% sort()
typLabsTo <- txtLabsTo
txtColsTo <- lapply(typLabsTo,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

typesFrom <- vDIns_T2T$type.from %>% unlist() %>% unique() %>% as.character()
fromLevels <- c(typesFrom[which(!grepl('PFN',typesFrom))],
                typesFrom[which(grepl('PFN',typesFrom))])
vDIns_T2T$type.from <- factor(vDIns_T2T$type.from,
                              levels = fromLevels)

txtLabsFrom <- fromLevels
typLabsFrom <- txtLabsFrom
txtColsFrom <- lapply(typLabsFrom,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

vDIns_T2T_Plt <- ggplot(vDIns_T2T) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(vDIns_T2T$weightRelative),
                       limits=c(0,max(vDIns_T2T$weightRelative))) +
  geom_tile(aes(type.to,type.from,fill=weightRelative)) +
  theme_paper() + coord_fixed(ratio = 1) + 
  theme(axis.text.x = element_text(angle = 90,color=txtColsTo),
        axis.text.y = element_text(color=txtColsFrom)) +
  xlab("postsynaptic neuron") + ylab("presynaptic neuron")

offset <- 0.5
typesTo <- vDIns_T2T$type.to %>% unique() %>% sort()
stTo <- supertype(typesTo) %>% unique()
for (g in 1:length(stTo)){
  offset <- offset + length(which(stTo[g] == supertype(typesTo)))
  vDIns_T2T_Plt <- vDIns_T2T_Plt + geom_vline(xintercept = offset)
}

offset <- 0.5
typesFrom <- vDIns_T2T$type.from %>% unique() %>% sort() %>% as.character()
stFrom <- supertype(typesFrom) %>% unique()
for (g in 1:length(stFrom)){
  offset <- offset + length(which(stFrom[g] == supertype(typesFrom)))
  vDIns_T2T_Plt <- vDIns_T2T_Plt + geom_hline(yintercept = offset)
}

print(vDIns_T2T_Plt)
ggsave("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_ColNronNetwork\\vDSubNet-ins_type-to-type.pdf",vDIns_T2T_Plt)
```

Look at the type-to-type connection among shared partners
```{r}
subNrons <- c(vDClust,vDIns_T2T$type.from %>% as.character(),vDOuts_T2T$type.to %>% as.character()) %>% unique()
subCT <- getConnectionTable(getTypesTable(subNrons)$bodyid,'POST',slctROI='FB') %>% filter(type.to %in% subNrons)
subCT_T2T <- getTypeToTypeTable(subCT)
```

```{r}

typesFrom <- subCT_T2T$type.from %>% unlist() %>% unique() %>% as.character()
fromLevels <- c(typesFrom[which(!grepl('PFN',typesFrom))],
                typesFrom[which(grepl('PFN',typesFrom))])
subCT_T2T$type.from <- factor(subCT_T2T$type.from,
                              levels = fromLevels)

txtLabsFrom <- fromLevels
typLabsFrom <- txtLabsFrom
txtColsFrom <- lapply(typLabsFrom,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()

typesTo <- subCT_T2T$type.to %>% unlist() %>% unique() %>% as.character()
toLevels <- c(typesTo[which(grepl('PFN',typesTo))],
              sort(typesTo[which(!grepl('PFN',typesTo) & 
                                  !grepl('PFR_b',typesTo) &
                                  !grepl('FC',typesTo) &
                                   !grepl('FR1',typesTo) &
                                   !grepl('FS',typesTo) &
                                   !grepl('PFL',typesTo))]),
              typesTo[which(grepl('FC',typesTo))],
              typesTo[which(grepl('FS',typesTo))],
              typesTo[which(grepl('PFR_b',typesTo))],
              typesTo[which(grepl('FR1',typesTo))],
              typesTo[which(grepl('PFL',typesTo))]
              )
subCT_T2T$type.to <- factor(subCT_T2T$type.to,
                              levels = toLevels)

txtLabsTo <- toLevels
typLabsTo <- txtLabsTo
txtColsTo <- lapply(typLabsTo,
                  function(t)
                    stCols$pal[
                      which(stCols$breaks == 
                              supertype(t))]) %>% unlist()


sub_T2T_Plt <- ggplot(subCT_T2T) + 
  scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", midpoint =0.5*max(subCT_T2T$weightRelative),
                       limits=c(0,max(subCT_T2T$weightRelative))) +
  geom_tile(aes(type.to,type.from,fill=weightRelative)) +
  theme_paper() + coord_fixed(ratio = 1)  + 
  theme(axis.text.x = element_text(angle = 90,color=txtColsTo),
        axis.text.y = element_text(color=txtColsFrom)) +
  xlab("postsynaptic neuron") + ylab("presynaptic neuron")

offset <- 0.5
stTo <- supertype(toLevels) %>% unique()
for (g in 1:length(stTo)){
  offset <- offset + length(which(stTo[g] == supertype(toLevels)))
  sub_T2T_Plt <- sub_T2T_Plt + geom_vline(xintercept = offset)
}

offset <- 0.5
stFrom <- supertype(fromLevels) %>% unique()
for (g in 1:length(stFrom)){
  offset <- offset + length(which(stFrom[g] == supertype(fromLevels)))
  sub_T2T_Plt <- sub_T2T_Plt + geom_hline(yintercept = offset)
}

print(sub_T2T_Plt)
ggsave("C:\\Users\\turnerevansd\\Dropbox (HHMI)\\FIBSEM CX Paper Jan 2020\\Figures\\FirstDraftFigs\\FB\\FIGURE_FB_ColNronNetwork\\vDSubNet-all_type-to-type.pdf",sub_T2T_Plt)
```

