---
title: "Notebook for plotting FB column-to-column connectivity motifs "
output:
  html_document:
    df_print: paged
---

### Load libraries
```{r message=FALSE, warning=FALSE}
library(nat)
library(neuprintr)
library(tidyverse)
library(dplyr)
library(matlib)
library(RColorBrewer)
library(ggraph)
library(robustbase)
require(alphahull)
library(zoo)
library(ggpubr)
library(ggraph)
library(igraph)
library(tidygraph)
library(xlsx)
library(dtplyr)
library(neuprintrExtra)
library("xlsx")
library(tidyselect)
library(paletteer)
library(quantmod)
library(prismatic)
library(svglite)
library(reshape2)
library(scales)
options(nat.plotengine = 'rgl')
```

### Make directories where figures will be saved to
```{r}

# Directory where synapse location data is stored (output of FB_GetAndSave_Synapses.Rmd)
SaveDir="C:/Users/labadmin/Documents/Cx_EM_Analysis/BradData/FB_Analysis/"

# Directory to save plots to.
PlotDir=paste(SaveDir, "/Figure_Motifs/",sep="")

# Create save/plot directories if they dont exists yet
if (!dir.exists(SaveDir)){dir.create(SaveDir)}
if (!dir.exists(PlotDir)){dir.create(PlotDir)}

```

### Connect to neuprint server.
```{r}
neuprint_login()
```

### Get general functions
```{r}

source("FB_Analysis_Utils.r")

```


# Get all FB bodies and columnar types
```{r message=FALSE, warning=FALSE}

NamedBodies=getNeuronsInRoiTable("FB",0)
Columnar_Types=sort(unique( NamedBodies$type[ startsWith(NamedBodies$type, "PF" ) | startsWith(NamedBodies$type, "FR" ) | 
                                                    startsWith(NamedBodies$type, "FS" ) | startsWith(NamedBodies$type, "FC" ) | 
                                                    startsWith(NamedBodies$type, "vDelta" ) | startsWith(NamedBodies$type, "hDelta")] ))
FBBodyCount=NamedBodies %>% group_by(type) %>% summarize(NumofNeurons=n())
FBColumnarBodyCount=subset(FBBodyCount, type %in% Columnar_Types)

```




# Plot intra-FB connectivity matrices and assign to motifs
```{r message=FALSE, warning=FALSE}


# Get columnar output connectivity table
FB_Bag=neuronBag(Columnar_Types, slctROI="FB")
FB_Outputs_All=FB_Bag[["outputs_raw"]]


# Assign PBglom, FBcol, and Side from neuron names
FB_Outputs_All=Assign_FBcol_PBglom(FB_Outputs_All, "name.from", "Side.from", "PBglom.from", "FBcol.from")
FB_Outputs_All=Assign_FBcol_PBglom(FB_Outputs_All, "name.to", "Side.to", "PBglom.to", "FBcol.to")


# Set FB column factor level
FB_Outputs_All$FBcol.from=factor(FB_Outputs_All$FBcol.from, levels = rev(c("C12","C11","C10","C9","C8","C7","C6","C5","C4","C3","C2","C1","C0")))
FB_Outputs_All$FBcol.to=factor(FB_Outputs_All$FBcol.to, levels = rev(c("C12","C11","C10","C9","C8","C7","C6","C5","C4","C3","C2","C1","C0")))


# Get the number of columns for each neuron type
ColumnarBodies=subset(NamedBodies, type %in% Columnar_Types)
ColumnarBodies=Assign_FBcol_PBglom(ColumnarBodies, "name", "Side", "PBglom", "FBcol") 
ColumnCounts=ColumnarBodies %>% group_by(type) %>% summarize(Columns = length(unique(FBcol)))
ColumnCounts$Columns[ !(startsWith(ColumnCounts$type,"hDelta"))]=9 # Not all types have neurons in each column (e.g. vDelta)
ColumnCounts_from=ColumnCounts
colnames(ColumnCounts_from)<-c("type.from","ColNum.from")
ColumnCounts_to=ColumnCounts_from
colnames(ColumnCounts_to)<-c("type.to","ColNum.to")
FB_Outputs_All=inner_join(FB_Outputs_All, ColumnCounts_to, by="type.to")
FB_Outputs_All=inner_join(FB_Outputs_All, ColumnCounts_from, by="type.from")
remove(ColumnCounts_from, ColumnCounts_to)


# Map all neurons into 9 column space, including C0 column (C0 to C9)
FB_Outputs_All$FBcol.from9=FB_Outputs_All$FBcol.from
FB_Outputs_All$FBcol.from9=as.numeric(sapply(FB_Outputs_All$FBcol.from9, substring, 2, 4))
FB_Outputs_All$FBcol.from9=round(FB_Outputs_All$FBcol.from9/FB_Outputs_All$ColNum.from*9)
FB_Outputs_All$FBcol.from9=paste("C",FB_Outputs_All$FBcol.from9,sep="")
FB_Outputs_All$FBcol.from9=factor(FB_Outputs_All$FBcol.from9, levels = rev(c("C9","C8","C7","C6","C5","C4","C3","C2","C1","C0")))

FB_Outputs_All$FBcol.to9=FB_Outputs_All$FBcol.to
FB_Outputs_All$FBcol.to9=as.numeric(sapply(FB_Outputs_All$FBcol.to9, substring, 2, 4))
FB_Outputs_All$FBcol.to9=round(FB_Outputs_All$FBcol.to9/FB_Outputs_All$ColNum.to*9)
FB_Outputs_All$FBcol.to9=paste("C",FB_Outputs_All$FBcol.to9,sep="")
FB_Outputs_All$FBcol.to9=factor(FB_Outputs_All$FBcol.to9, levels = rev(c("C9","C8","C7","C6","C5","C4","C3","C2","C1","C0")))


# Loop over all Pre-Post connectivity tables, map each pair into a 9 column space, and convert that matrix to a vector
# In this way, each column-to-column connectivity table becomes a vector in "connectivity space", which we'll perform PCA on.
Pre_Post=distinct(FB_Outputs_All[c("type.from","type.to")])
Vectors=matrix(data=NA,nrow=length(Pre_Post$type.from),ncol=100)
for (ppp in 1:length(Pre_Post$type.from)){

  # Get connectivity table for this Pre-Post pair
  Temp_PFX_Out=subset(FB_Outputs_All, (type.from==Pre_Post$type.from[ppp]) & (type.to==Pre_Post$type.to[ppp]))
  
  # Subset data and name neurons by column/glom and bodyid for a fully connected 9 column scheme
  Temp_ColumnTable9=Temp_PFX_Out %>% group_by(FBcol.from9,FBcol.to9) %>% summarize(weightRelative=mean(weightRelative))
  
  # Turn dataframe into a matrix, where implicitly missing connections have 0 weight. Store as vector.
  all <- Temp_ColumnTable9 %>% expand(FBcol.from9, FBcol.to9) %>% distinct()
  Temp_ColumnTable9_Full = Temp_ColumnTable9 %>% dplyr::right_join(all, by = c("FBcol.from9", "FBcol.to9"))
  Temp_ColumnTable9_Full$weightRelative[is.na( Temp_ColumnTable9_Full$weightRelative)]=0
  TempMatrix <- reshape2::acast(Temp_ColumnTable9_Full, FBcol.from9 ~ FBcol.to9, value.var="weightRelative")
  TempVector = c(TempMatrix)
  Vectors[ppp,]=TempVector
}


## Perform PCA on binarized data
OUT=motifPCA(Vectors, "Binary", Pre_Post)
Columnar_PC_Motifs=OUT[[1]]
covEigen=OUT[[2]]
Var_Explained=sum(covEigen$values[c(1,2)])/sum(covEigen$values)
sum(covEigen$values[c(3)])/sum(covEigen$values)


# Plot PCs and their variance
PC_Var=data.frame(PC=seq(from=1,to=length(covEigen$values),by=1), PropVar=covEigen$values/sum(covEigen$values))
P0=ggplot() + geom_line(data=PC_Var[1:10,], aes(x=PC, y=PropVar),color='blueviolet') + 
  geom_point(data=PC_Var[1:10,], aes(x=PC, y=PropVar),color='blueviolet',size=2) + 
  scale_x_continuous(limits = c(0.5, 10.5), expand = c(0,0),  breaks = c(1:10)) +
  scale_y_continuous(limits = c(0, 0.4), expand = c(0,0),  breaks = c(0,0.2,0.4)) + theme_classic()
P0
ggsave(paste(PlotDir, "PC_Variance.png",sep=""),
       plot = P0, device='png', scale = 1, width =5, height = 4, units ="in", dpi = 500, limitsize = TRUE)


# Get the first 6 PCs as column-to-column connectivity matrices 
PC1=GetPC(covEigen,1)
PC2=GetPC(covEigen,2)
PC3=GetPC(covEigen,3)
PC4=GetPC(covEigen,4)
PC5=GetPC(covEigen,5)
PC6=GetPC(covEigen,6)


# Make plot of first 6 PCs
P1=ggplot(PC1) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC1", round(PC_Var$PropVar[1]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")
P2=ggplot(PC2) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC2", round(PC_Var$PropVar[2]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")
P3=ggplot(PC3) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC3", round(PC_Var$PropVar[3]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")
P4=ggplot(PC4) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC4", round(PC_Var$PropVar[4]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")
P5=ggplot(PC5) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC5", round(PC_Var$PropVar[5]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")
P6=ggplot(PC6) + theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_gradient2(low="blue", high="red", limits=c(-0.5,0.5), oob=squish) + coord_fixed() +
  geom_tile(aes(Var2,Var1,fill=value)) + ggtitle(paste("PC6", round(PC_Var$PropVar[6]*1000)/1000)) + theme(legend.position="none") +
  xlab("post column") + ylab("pre column")

PAll=ggarrange(P1,P2,P3,P4,P5,P6,nrow=2,ncol=3)
PAll
ggsave(paste(PlotDir, "Top_PCs.png",sep=""),
       plot = PAll, device='png', scale = 1, width =7, height = 4, units ="in", dpi = 500, limitsize = TRUE)



```




# Plot intra-FB connectivity matrices and assign to motifs
```{r message=FALSE, warning=FALSE}


# Make supertypes
Columnar_PC_Motifs$Motif=NA
hDeltaTypes=Columnar_Types[startsWith(Columnar_Types,'hDelta')]
VDeltaTypes=Columnar_Types[!startsWith(Columnar_Types,'hDelta') ]
Columnar_PC_Motifs$Motif[ (Columnar_PC_Motifs$type.from %in% hDeltaTypes) & (Columnar_PC_Motifs$type.to %in% hDeltaTypes)] = "H to H"
Columnar_PC_Motifs$Motif[ (Columnar_PC_Motifs$type.from %in% VDeltaTypes) & (Columnar_PC_Motifs$type.to %in% VDeltaTypes)] = "V to V"
Columnar_PC_Motifs$Motif[ (Columnar_PC_Motifs$type.from %in% VDeltaTypes) & (Columnar_PC_Motifs$type.to %in% hDeltaTypes)] = "V to H"
Columnar_PC_Motifs$Motif[ (Columnar_PC_Motifs$type.from %in% hDeltaTypes) & (Columnar_PC_Motifs$type.to %in% VDeltaTypes)] = "H to V"
Columnar_PC_Motifs$Motif=factor(Columnar_PC_Motifs$Motif, levels=unique(Columnar_PC_Motifs$Motif))

# Get colors
pcCols <- paletteer_d("Polychrome::palette36")
pcCols=pcCols[c(26,6,32,25)]

# Loop over and plot every neurons matrix along with its place in the PCA space
for (ppp in 1:length(Pre_Post$type.from)){
  print(ppp)
  
  # Average across columns and plot (using all columns)
  Temp_PFX_Out=subset(FB_Outputs_All, (type.from==Pre_Post$type.from[ppp]) & (type.to==Pre_Post$type.to[ppp]))
  
  
  # Average across columns and plot (using all columns)
  Temp_ColumnTable=Temp_PFX_Out %>% group_by(FBcol.from,FBcol.to) %>% summarize(weightRelative=mean(weightRelative))
  
  # Calculate number of pre and post neurons
  PreNum=length(unique(Temp_PFX_Out$from))
  PostNum=length(unique(Temp_PFX_Out$to))
  PreNum_All=FBColumnarBodyCount$NumofNeurons[FBColumnarBodyCount$type == Pre_Post$type.from[ppp]]
  PostNum_All=FBColumnarBodyCount$NumofNeurons[FBColumnarBodyCount$type == Pre_Post$type.to[ppp]]
  FBColtoNum=length(unique(Temp_PFX_Out$FBcol.to))
  
  P1=ggplot(Temp_ColumnTable) + 
    theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
    scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", 
                         midpoint =0.5*max(Temp_ColumnTable$weightRelative), limits=c(0,max(Temp_ColumnTable$weightRelative))) +
    geom_tile(aes(FBcol.to,FBcol.from,fill=weightRelative)) + ylab(Pre_Post$type.from[ppp]) + xlab(Pre_Post$type.to[ppp])
  
  
  # Do the same, but for a fully connected 9 column scheme
  Temp_ColumnTable9=Temp_PFX_Out %>% group_by(FBcol.from9,FBcol.to9) %>% summarize(weightRelative=mean(weightRelative))
  
  # Turn dataframe into a matrix, where implicitly missing connections have 0 weight. Store as vector.
  all <- Temp_ColumnTable9 %>% expand(FBcol.from9, FBcol.to9) %>% distinct()
  Temp_ColumnTable9_Full = Temp_ColumnTable9 %>% dplyr::right_join(all, by = c("FBcol.from9", "FBcol.to9"))
  Temp_ColumnTable9_Full$weightRelative[is.na( Temp_ColumnTable9_Full$weightRelative)]=0
  
  P2=ggplot(Temp_ColumnTable9_Full) + 
    theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
    scale_fill_gradient2(low="thistle", mid="blueviolet", high="black", 
                         midpoint =0.5*max(Temp_ColumnTable9_Full$weightRelative), limits=c(0,max(Temp_ColumnTable9_Full$weightRelative))) +
    geom_tile(aes(FBcol.to9,FBcol.from9,fill=weightRelative)) + ylab(Pre_Post$type.from[ppp]) + xlab(Pre_Post$type.to[ppp])
  

  # Plot PCA space
  CCC=pcCols[which(Columnar_PC_Motifs$Motif[ppp] == levels(Columnar_PC_Motifs$Motif))]
  P3=ggplot()  + geom_point(data=Columnar_PC_Motifs,aes(x=V1, y=V2, color=Motif),alpha=0.5,size=2) + 
    geom_point(data=Columnar_PC_Motifs[ppp,],aes(x=V1, y=V2),color="red", fill=CCC, alpha=1,size=5,shape = 21) +
    xlab("PC 1") + ylab("PC 2") + coord_fixed() +  theme_classic() + theme(text = element_text(size=12)) +
    xlim(-4.25,4.25) + ylim(0,8) + scale_color_manual(values=pcCols)

  P4=ggarrange(P1,P2,P3,nrow=1,ncol=3)
  ggsave(paste(PFX_Dir_Connectivity, Pre_Post$type.from[ppp],"_to_", Pre_Post$type.to[ppp], "_", as.character(ppp),"_inFB.png",sep=""), plot = P4, device='png', scale = 1, width =15, height = 3.5, units ="in", dpi = 250, limitsize = TRUE)
  
}


# Make plot with all examples shown
Example_Inds=c(11,23,47,14,10,229,24,3)

CCC1=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[1]] == levels(Columnar_PC_Motifs$Motif))]   # PFNd --> hDeltaB #
CCC2=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[2]] == levels(Columnar_PC_Motifs$Motif))]   # PFNv --> hDebtaB # 
CCC3=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[3]] == levels(Columnar_PC_Motifs$Motif))]   # PFNa --> FC1B #
CCC4=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[4]] == levels(Columnar_PC_Motifs$Motif))]   # hDeltaB --> hDeltaK #
CCC5=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[5]] == levels(Columnar_PC_Motifs$Motif))]   # hDeltaB --> hDeltaI # 
CCC6=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[6]] == levels(Columnar_PC_Motifs$Motif))]   # hDeltaG --> vDeltaE #
CCC7=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[7]] == levels(Columnar_PC_Motifs$Motif))]   # hDeltaB --> hDeltaA #
CCC8=pcCols[which(Columnar_PC_Motifs$Motif[Example_Inds[8]] == levels(Columnar_PC_Motifs$Motif))]   # PFGs --> hDeltaK #

P3=ggplot()  + geom_point(data=Columnar_PC_Motifs,aes(x=V1, y=V2, color=Motif),alpha=0.5,size=2, shape = 16) + 
  geom_point(data=Columnar_PC_Motifs[Example_Inds[1],],aes(x=V1, y=V2),color="red", fill=CCC1, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[2],],aes(x=V1, y=V2),color="red", fill=CCC2, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[3],],aes(x=V1, y=V2),color="red", fill=CCC3, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[4],],aes(x=V1, y=V2),color="red", fill=CCC4, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[5],],aes(x=V1, y=V2),color="red", fill=CCC5, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[6],],aes(x=V1, y=V2),color="red", fill=CCC6, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[7],],aes(x=V1, y=V2),color="red", fill=CCC7, alpha=1,size=5,shape = 21) +
  geom_point(data=Columnar_PC_Motifs[Example_Inds[8],],aes(x=V1, y=V2),color="red", fill=CCC8, alpha=1,size=5,shape = 21) +
  xlab("PC 1") + ylab("PC 2") + coord_fixed() +  theme_classic() + theme(text = element_text(size=12)) +
  xlim(-4,4) + ylim(0,8) + scale_color_manual(values=pcCols)
ggsave(paste(PFX_Dir_Connectivity, "PCA_Scatter_Examples.pdf",sep=""), plot = P3, device='pdf', scale = 1, width =6, height = 4, units ="in", dpi = 250, limitsize = TRUE)


# Loop over chosen examples and save connectivity matrices as PDFs
library(scales)
for (exex in 1:length(Example_Inds)){
  
  ppp=Example_Inds[exex]
  print(ppp)
  
  # Average across columns and plot (using all columns)
  Temp_PFX_Out=subset(FB_Outputs_All, (type.from==Pre_Post$type.from[ppp]) & (type.to==Pre_Post$type.to[ppp]))
  
  # Average across columns and plot (using all columns)
  Temp_ColumnTable=Temp_PFX_Out %>% group_by(FBcol.from,FBcol.to) %>% summarize(weightRelative=mean(weightRelative))
  
  # Make plot
  P1=ggplot(Temp_ColumnTable) + 
    theme_classic() + theme(axis.text.x = element_text(angle = 90)) +
    scale_fill_gradient2(low="gray30", high="black", 
                        limits=c(0,0.04), oob=squish) + coord_fixed() +
    geom_tile(aes(FBcol.to,FBcol.from,fill=weightRelative)) + ylab(Pre_Post$type.from[ppp]) + xlab(Pre_Post$type.to[ppp])
  ggsave(paste(PFX_Dir_Connectivity, "FIGURE_", Pre_Post$type.from[ppp],"_to_", Pre_Post$type.to[ppp], "_", as.character(ppp),"_inFB.pdf",sep=""),
         plot = P1, device='pdf', scale = 1, width =6, height = 4, units ="in", dpi = 500, limitsize = TRUE)
  
}
  
  



```






















































