---
title: "validation-Figure3"
author: "Romain Franconville"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### EB before/after comparison
```{r}
EBMesh <- neuprint_ROI_mesh("EB")
```

```{r}
newConnection <- neuprint_login(server="https://neuprint.janelia.org",token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbWFpbi5mcmFuY29udmlsbGVAZ21haWwuY29tIiwibGV2ZWwiOiJyZWFkd3JpdGUiLCJpbWFnZS11cmwiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLWdtUDkxREF4LTNvL0FBQUFBQUFBQUFJL0FBQUFBQUFBQUFBL0FDSGkzcmRaaThLWElURkNhTWpzQldIZUFqcTZ6SkdtX2cvcGhvdG8uanBnP3N6PTUwP3N6PTUwIiwiZXhwIjoxNzYzMzY1MTMyfQ.yCthFpsDrQJLl41WjLf3U-iN-21x_opCXDcnhbizC_g",Force = T)
```

```{r}
oldConnection <- neuprint_login(server="https://emdata1.int.janelia.org:11000/",token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbWFpbi5mcmFuY29udmlsbGVAZ21haWwuY29tIiwibGV2ZWwiOiJyZWFkd3JpdGUiLCJpbWFnZS11cmwiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLWdtUDkxREF4LTNvL0FBQUFBQUFBQUFJL0FBQUFBQUFBQUFBL0FBS1dKSk14RURObVNiekk5TjNULWw2RkRySWhHdG5LNncvcGhvdG8uanBnP3N6PTUwP3N6PTUwIiwiZXhwIjoxNzY2NDY0NjI2fQ.HsBHKOqeLUUcBcOY-GwzbCHrBMdCBesaICM4UUQSH_k",config=httr::config(ssl_verifypeer=0L),dataset="hemibrain:v0.9pre_dense",Force=T)
```

Select EB neurons for inputs/outputs
```{r}
ebNeurons <- neuprint_bodies_in_ROI("EB",all_segments = FALSE,conn = newConnection)
ebInfo <- filter(getRoiInfo(ebNeurons$bodyid,conn=newConnection),roi=="EB")
ebInfo[is.na(ebInfo)] <- 0
```

```{r}
ebIns <- filter(ebInfo,upstream>200)
ebOuts <- filter(ebInfo,downstream>200)
```

#### Comparing neuron to neuron connections
```{r}
exampleEPG <- 789126240
exampleEPGNew <- getNeuronMesh(exampleEPG,cloud=TRUE)
exampleEPGOld <- getNeuronMesh(exampleEPG,cloud=TRUE,node="34d7a")
epgInputSynapsesNew <- filter(neuprint_get_synapses(exampleEPG,roi="EB",conn=newConnection),prepost==1)# %>% select(x,y,z)
epgInputSynapsesOld <- filter(neuprint_get_synapses(exampleEPG,roi="EB",conn=oldConnection),prepost==1)# %>% select(x,y,z)
partnerListNew <- filter(neuprint_get_meta(unique(c(epgInputSynapsesNew$partner)),all_segments = FALSE,conn=newConnection),status=="Traced")
partnerListOld <- filter(neuprint_get_meta(unique(c(epgInputSynapsesOld$partner)),all_segments = FALSE,conn=oldConnection),status=="Traced")
epgInputSynapsesNew <-  filter(epgInputSynapsesNew,partner %in% partnerListNew$bodyid) %>% select(x,y,z)
epgInputSynapsesOld <- filter(epgInputSynapsesOld,partner %in% partnerListOld$bodyid) %>% select(x,y,z)
```


```{r}
nopen3d()
par3d(windowRect = c(30, 30, 1530, 1530))
plot3d(EBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
shade3d(exampleEPGOld,color="grey80")
shade3d(exampleEPGNew,color="red")
plot3d(epgInputSynapsesOld,add=T,col="#B32DB5")
plot3d(epgInputSynapsesNew,add=T,col="#053CFF")
nview3d("ventral")
zoom0View <- par3d("userProjection")
rgl.snapshot(paste0(validationFolder,"frontEBZoom1.png"))
```

```{r}
nopen3d()
par3d(windowRect = c(30, 30, 1530, 1530))
par3d(userProjection=translationMatrix(-1.2,1.6,0) %*% zoom0View)
plot3d(EBMesh,color="white",alpha=0.2,xlab="",ylab="",zlab="",box=FALSE,axes=FALSE)
par3d(scale=c(1,1,1))
nview3d("ventral",zoom=0.1)
shade3d(addNormals(exampleEPGOld),color="grey80")
shade3d(addNormals(exampleEPGNew),color="red")


plot3d(epgInputSynapsesOld,add=T,col="#B32DB5",size=15)
plot3d(epgInputSynapsesNew,add=T,col="#053CFF",size=15)
```

```{r}
rgl.snapshot(paste0(validationFolder,"frontEBZoom2.png"))
```

```{r}
EPGViews <- ggdraw() + draw_image(paste0(validationFolder,"frontEBZoom1.png"),scale=1.6,clip="on") + draw_image(paste0(validationFolder,"frontEBZoom2.png"),scale=0.5,vjust=-0.23,hjust=0.05,clip="on") + theme_paper_map() + 
   annotate(geom="text",x=0.25,y=0.22,label="Synapses",hjust=0) +
  annotate(geom="point",x=0.25,y=0.18,color="#B32DB5",size=1) + 
  annotate(geom="point",x=0.25,y=0.14,color="#053CFF",size=1) +
  annotate(geom="text",x=0.26,y=0.18,label="Initially traced",hjust=0) +
  annotate(geom="text",x=0.26,y=0.14,label="New additions",hjust=0) +
  annotate(geom="text",x=0.33,y=0.68,label="*",hjust=0,size=8,color="red")
EPGViews
```


```{r}
EBAges <- getCompConnectionTable(ebIns$bodyid,ebOuts$bodyid,"EB",newConnection,oldConnection)
```

```{r}
EBAges_filtered <- filter(EBAges,known_synapses_ratio>0.1)
EBAges_summary <-distinct(EBAges_filtered,bodyid,side,.keep_all = TRUE) 
synChangeEB <- ggplot(EBAges_summary,aes(x=databaseType,y=known_synapses_ratio*100,color=supertype2)) + geom_jitter(width=0.25,size=0.4) + 
     scale_color_CX_supertype(name="Supertype") + theme_paper() + facet_grid(.~side,scales="free_x") + xlab("") + ylab("known synapses change (%)") +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) + ylim(c(0,120))+ggforce::geom_mark_circle(aes(filter = (bodyid == exampleEPG & side=="inputs")),color="black",expand=0.03)
synChangeEB
```

```{r}
synChangeEBTot <- ggplot(distinct(EBAges,bodyid,side,.keep_all = TRUE),aes(x=databaseType,y=known_synapses_ratio*100,color=supertype2)) + geom_jitter(width=0.2,size=1) + scale_color_CX_supertype(name="Type") + theme_paper() + facet_grid(.~side,scales="free_x")+ xlab("") + ylab("known synapses change (%)") + theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) + geom_hline(yintercept = 10,linetype=2,color="grey") + ggforce::geom_mark_circle(aes(filter = (bodyid == exampleEPG & side =="inputs")),color="black",expand=0.03)
synChangeEBTot
```
```{r}
EBFits <- getFit(EBAges,groups = c("bodyid","databaseType","supertype2","side"),predicted="new",predictor="old")
EBFits <- left_join(EBFits,distinct(EBAges,bodyid,databaseType,supertype2,side,known_synapses_ratio,known_synapses.old,known_synapses.new),by=c("bodyid","databaseType","supertype2","side"))
```



```{r}
EBSlopes <- ggplot(filter(EBFits,paste(bodyid,side) %in% paste(EBAges_summary$bodyid,EBAges_summary$side)),aes(x=databaseType,y=estimate,ymin=estimate-std.error,ymax=estimate+std.error,color=supertype2)) + geom_pointrange(size=0.4/20,position=position_jitter(width=0.2)) + scale_color_CX_supertype(name="Supertype") + facet_grid(.~side,scales = "free_x") + theme_paper() +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) +xlab("") +ylab("slope estimate") + ggforce::geom_mark_circle(aes(filter = (bodyid == exampleEPG & side=="inputs")),color="black",expand=0.03) + geom_hline(yintercept = 1,lty=2)
EBSlopes
```

```{r}
fitValsEPG <- filter(EBFits,bodyid==exampleEPG & side=="Inputs")
EBCompExample <- ggplot(filter(EBAges_filtered,bodyid==exampleEPG & side=="inputs"),aes(x=old,y=new)) + geom_point(aes(color=supertype2.from),size=0.4) + geom_smooth(formula=y~x,method="lm",color="grey70",alpha=0.1) + 
  geom_abline(linetype=2,lwd=0.2) + theme_paper()  + scale_color_CX_supertype(name="Supertype") + xlab("relative weight in the old dataset") + coord_fixed() +
  ylab("relative weight in the new dataset") + annotate(geom="text",x=0.015,y=0.002,label=paste0("s= ",format(fitValsEPG$estimate,digits = 3),"\n r\u00b2= ",format(fitValsEPG$adj.r.squared,digits=3)))

EBCompExample
```

```{r}
save_plot(paste0(validationFolder,"EBCounts.svg"),synChangeEB,base_width=6.5,base_height=2.25)
save_plot(paste0(validationFolder,"EBSlopes.svg"),EBSlopes,base_width=6.5,base_height=2.25)
save_plot(paste0(validationFolder,"EBExampleFit.svg"),EBCompExample,base_width=3,base_height=3)


ebLayout <- c(
  area(t = 1, l = 1, b = 5, r = 5),
  area(t = 1, l = 6, b = 4, r = 10),
  area(t = 6, l = 2, b = 8, r = 4),
  area(t = 5, l = 6, b = 8, r = 10)
)

EBFig <- (EPGViews + 
  synChangeEB  + (EBCompExample + theme(legend.position="none")) +
  (EBSlopes+ theme(legend.position="none"))) +plot_layout(design = ebLayout) #+ plot_annotation(tag_levels=c("A","i"))

EBFig
```

```{r}
mainFig <- (EBFig + plot_layout(tag_level = "new")) / (PBFigAlt + plot_layout(tag_level = "new"))/(FC3Panel + plot_layout(tag_level="new")) + plot_annotation(tag_levels=c("A","i"),tag_sep = "",title="Validation - Figure 1: tracing effect on connection weights",theme=theme(title=element_text(size=12,face="bold"))) 
mainFig

save_plot(paste0(validationFolder,"Validation-Figure1.pdf"),mainFig,nrow = 4,ncol=2,base_width = 8.5/2,base_height=11/3,device=cairo_pdf)
```

#### EB SI
```{r}
EBCompFull <- ggplot(filter(EBAges_filtered),aes(x=old,y=new,fill=supertype2)) + geom_smooth(formula=y~x,aes(group=bodyid),method="lm",alpha=0.3,color="grey30",size=0.1) + 
  geom_abline(linetype=2,lwd=0.2) + scale_fill_CX_supertype(name="Supertype") + xlab("relative weight in the old dataset") + coord_fixed() +
  ylab("relative weight in the new dataset") + facet_wrap(supertype2~side)+ theme_paper() + ggtitle("Validation figure 1 - figure supplement 1: individual neuron to neuron fits")#+theme(panel.border = element_rect(color = "gray 50", fill = NA))
#EBCompFull
save_plot(paste0(validationFolder,"Validation-Figure1-SI1.pdf"),EBCompFull,nrow = 2,ncol=3,base_width = 8.5/3,device=cairo_pdf)
```

```{r}
incSlope <-  ggplot(filter(EBFits,paste(bodyid,side) %in% paste(EBAges_summary$bodyid,EBAges_summary$side)),aes(x=known_synapses_ratio*100,y=estimate,ymin=estimate-std.error,ymax=estimate+std.error,color=supertype2)) + geom_pointrange(size=0.2/3) + scale_color_CX_supertype(name="Supertype") + facet_grid(.~side,scales = "free_x") + theme_paper() +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) +xlab("known synapse increase") +ylab("slope estimate") + geom_hline(yintercept=1,lty=2)
incSlope
```
```{r}
incRS <-  ggplot(filter(EBFits,paste(bodyid,side) %in% paste(EBAges_summary$bodyid,EBAges_summary$side)),aes(x=known_synapses_ratio*100,y=adj.r.squared,color=supertype2)) + geom_point(size=1) + scale_color_CX_supertype(name="Supertype") + facet_grid(.~side,scales = "free_x") + theme_paper() +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333))  +xlab("known synapse increase") +ylab("adjusted r\u00b2") + geom_hline(yintercept=1,lty=2)
incRS
```


```{r}
nSlope <-  ggplot(filter(EBFits,paste(bodyid,side) %in% paste(EBAges_summary$bodyid,EBAges_summary$side)),aes(x=known_synapses.new,y=estimate,ymin=estimate-std.error,ymax=estimate+std.error,color=supertype2)) + geom_pointrange(size=0.2/3) + scale_color_CX_supertype(name="Supertype") + facet_grid(.~side,scales = "free_x") + theme_paper() +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) +xlab("# synapses") +ylab("slope estimate")  + geom_hline(yintercept=1,lty=2)
nSlope
```
```{r}
nRS <-  ggplot(filter(EBFits,paste(bodyid,side) %in% paste(EBAges_summary$bodyid,EBAges_summary$side)),aes(x=known_synapses.new,y=adj.r.squared,color=supertype2)) + geom_point(size=1) + scale_color_CX_supertype(name="Supertype") + facet_grid(.~side,scales = "free_x") + theme_paper() +theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust=0.5),strip.background = element_rect(color="black"),strip.text = element_text(family="arial",size=6*1.333333)) +xlab("# synapses") +ylab("adjusted r\u00b2") +geom_hline(yintercept=1,lty=2)
nRS
```